package th.co.ais.ipfm.domain;
// Generated Jul 14, 2010 10:47:11 AM by Hibernate Tools 3.2.1.GA


import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Version;

/**
 * IpFunction generated by hbm2java
 */
@Entity
@Table(name="IP_FUNCTION"
    ,schema="IPFMBK"
)
public class IPFunction  implements java.io.Serializable,Cloneable {
     @Id
	 @Column(name="FUNC_ID", unique=true, nullable=false, length=10)
     private String funcId;
     
     @Version
     @Column(name="VERSION")
     private Integer version;
     
     @Column(name="FUNC_NAME", length=100)
     private String funcName;
     
     @Column(name="MENU_LEVEL") 
     private Integer menuLevel;
     
     @Column(name="MENU_SEQ")
     private Integer menuSeq;
     
     @Column(name="FUNC_MATHER_ID", length=10)
     private String funcMatherId;
     
//     @SuppressWarnings("unchecked")
//     private IPFunction funcMather = new IPFunction();
     
     @Column(name="PROGRAM_ID", length=20)
     private String programId;
     
//     @Column(name="PROGRAM_TYPE", length=10)
//     private String programType;
     
     @Column(name="PROGRAM_URL", length=10)
     private String programUrl;
     
     @Column(name="STATUS_ADD", length=1)
     private String statusAdd;
     
     @Column(name="STATUS_UPDATE", length=1)
     private String statusUpdate;
     
     @Column(name="STATUS_DELETE", length=1)
     private String statusDelete;
     
     @Column(name="STATUS_VIEW", length=1)
     private String statusView;
     
     @Column(name="STATUS_ADVANCE", length=1000)
     private String statusAdvance;
     
     @Column(name="CREATE_BY", length=20)
     private String createBy;
     
     @Temporal(TemporalType.DATE)
     @Column(name="CREATE_DATE", length=10)
     private Date createDate;
     
     @Column(name="UPDATE_BY", length=20)
     private String updateBy;
     
     @Temporal(TemporalType.DATE)
     @Column(name="UPDATE_DATE", length=10)
     private Date updateDate;
     
     @Column(name="ROW_ID", length=50)
     private String rowId;
     
     

    public IPFunction() {
    }

	
    public IPFunction(String funcId) {
        this.funcId = funcId;
    }
    public IPFunction(String funcId, String funcName, Integer menuLevel, Integer menuSeq, String funcMatherId, String programId, String programType, String programUrl, String statusAdd, String statusUpdate, String statusDelete, String statusView, String statusAdvance, String createBy, Date createDate, String updateBy, Date updateDate, String rowId) {
       this.funcId = funcId;
       this.funcName = funcName;
       this.menuLevel = menuLevel;
       this.menuSeq = menuSeq;
       this.funcMatherId = funcMatherId;
       this.programId = programId;
       //this.programType = programType;
       this.programUrl = programUrl;
       this.statusAdd = statusAdd;
       this.statusUpdate = statusUpdate;
       this.statusDelete = statusDelete;
       this.statusView = statusView;
       this.statusAdvance = statusAdvance;
       this.createBy = createBy;
       this.createDate = createDate;
       this.updateBy = updateBy;
       this.updateDate = updateDate;
       this.rowId = rowId;
    }
    
    public String getFuncId() {
        return this.funcId;
    }
    
    public void setFuncId(String funcId) {
        this.funcId = funcId;
    }
    
    public Integer getVersion() {
        return this.version;
    }
    
    public void setVersion(Integer version) {
        this.version = version;
    }
    
    public String getFuncName() {
        return this.funcName;
    }
    
    public void setFuncName(String funcName) {
        this.funcName = funcName;
    }
    
    public Integer getMenuLevel() {
        return this.menuLevel;
    }
    
    public void setMenuLevel(Integer menuLevel) {
        this.menuLevel = menuLevel;
    }
    
    public Integer getMenuSeq() {
        return this.menuSeq;
    }
    
    public void setMenuSeq(Integer menuSeq) {
        this.menuSeq = menuSeq;
    }
    
    public String getFuncMatherId() {
        return this.funcMatherId;
    }
    
    public void setFuncMatherId(String funcMatherId) {
        this.funcMatherId = funcMatherId;
    }
    
//    public IPFunction getFuncMather() {
//		return funcMather;
//	}
//
//	public void setFuncMather(IPFunction funcMather) {
//		this.funcMather = funcMather;
//	}


	public String getProgramId() {
        return this.programId;
    }
    
    public void setProgramId(String programId) {
        this.programId = programId;
    }
    
//    public String getProgramType() {
//        return this.programType;
//    }
//    
//    public void setProgramType(String programType) {
//        this.programType = programType;
//    }
    
    public String getProgramUrl() {
        return this.programUrl;
    }
    
    public void setProgramUrl(String programUrl) {
        this.programUrl = programUrl;
    }
    
    public String getStatusAdd() {
        return this.statusAdd;
    }
    
    public void setStatusAdd(String statusAdd) {
        this.statusAdd = statusAdd;
    }
    
    public String getStatusUpdate() {
        return this.statusUpdate;
    }
    
    public void setStatusUpdate(String statusUpdate) {
        this.statusUpdate = statusUpdate;
    }
    
    public String getStatusDelete() {
        return this.statusDelete;
    }
    
    public void setStatusDelete(String statusDelete) {
        this.statusDelete = statusDelete;
    }
    
    public String getStatusView() {
        return this.statusView;
    }
    
    public void setStatusView(String statusView) {
        this.statusView = statusView;
    }
    
    public String getStatusAdvance() {
        return this.statusAdvance;
    }
    
    public void setStatusAdvance(String statusAdvance) {
        this.statusAdvance = statusAdvance;
    }
    
    public String getCreateBy() {
        return this.createBy;
    }
    
    public void setCreateBy(String createBy) {
        this.createBy = createBy;
    }
    
    public Date getCreateDate() {
        return this.createDate;
    }
    
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }
    
	public String getUpdateBy() {
        return this.updateBy;
    }
    
    public void setUpdateBy(String updateBy) {
        this.updateBy = updateBy;
    }
    
    public Date getUpdateDate() {
        return this.updateDate;
    }
    
    public void setUpdateDate(Date updateDate) {
        this.updateDate = updateDate;
    }
    
	public String getRowId() {
        return this.rowId;
    }
    
    public void setRowId(String rowId) {
        this.rowId = rowId;
    }

	@Override
    public Object clone() throws CloneNotSupportedException
    {
		IPFunction another = (IPFunction) super.clone();
        //? take care of any deep copies to be made here
        return another;
    }


}


