package th.co.ais.ipfm.domain;
// Generated Jul 14, 2010 10:47:11 AM by Hibernate Tools 3.2.1.GA


import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Version;

/**
 * IpFunction generated by hbm2java
 */
@Entity
@Table(name="IP_FUNCTION"
    ,schema="IPFMBK"
)
public class IPFunction  implements java.io.Serializable,Cloneable {
     @Id
	 @Column(name="FUNC_ID", unique=true, nullable=false, length=10)
     private String funcId;
     
     @Version
     @Column(name="VERSION")
     private Integer version;
     
     @Column(name="FUNC_NAME", length=100)
     private String funcName;
     
     @Column(name="MENU_LEVEL") 
     private Integer menuLevel;
     
     @Column(name="MENU_SEQ")
     private Integer menuSeq;
     
     @Column(name="FUNC_MATHER_ID", length=10)
     private String funcMatherId;
     
//     @SuppressWarnings("unchecked")
//     private IPFunction funcMather = new IPFunction();
     
     @Column(name="PROGRAM_ID", length=20)
     private String programId;
     
//     @Column(name="PROGRAM_TYPE", length=10)
//     private String programType;
     
     @Column(name="PROGRAM_URL", length=10)
     private String programUrl;
     
     @Column(name="STATUS_ADD", length=1)
     private String statusAdd;
     
     @Column(name="STATUS_UPDATE", length=1)
     private String statusUpdate;
     
     @Column(name="STATUS_DELETE", length=1)
     private String statusDelete;
     
     @Column(name="STATUS_VIEW", length=1)
     private String statusView;
     
     @Column(name="STATUS_ADVANCE", length=1000)
     private String statusAdvance;
     
     @Column(name="CREATE_BY", length=20)
     private String createBy;
     
     @Temporal(TemporalType.DATE)
     @Column(name="CREATE_DATE", length=10)
     private Date createDate;
     
     @Column(name="UPDATE_BY", length=20)
     private String updateBy;
     
     @Temporal(TemporalType.DATE)
     @Column(name="UPDATE_DATE", length=10)
     private Date updateDate;
     
     @Column(name="ROW_ID", length=50)
     private String rowId;
     
     

    public IPFunction() {
    }

	
    public IPFunction(String funcId) {
        this.funcId = funcId;
    }
    public IPFunction(String funcId, String funcName, Integer menuLevel, Integer menuSeq, String funcMatherId, String programId, String programType, String programUrl, String statusAdd, String statusUpdate, String statusDelete, String statusView, String statusAdvance, String createBy, Date createDate, String updateBy, Date updateDate, String rowId) {
       this.funcId = funcId;
       this.funcName = funcName;
       this.menuLevel = menuLevel;
       this.menuSeq = menuSeq;
       this.funcMatherId = funcMatherId;
       this.programId = programId;
       //this.programType = programType;
       this.programUrl = programUrl;
       this.statusAdd = statusAdd;
       this.statusUpdate = statusUpdate;
       this.statusDelete = statusDelete;
       this.statusView = statusView;
       this.statusAdvance = statusAdvance;
       this.createBy = createBy;
       this.createDate = createDate;
       this.updateBy = updateBy;
       this.updateDate = updateDate;
       this.rowId = rowId;
    }
    
    public String getFuncId() { // DMAP Comment : Dead Code Detected - The Following Method has no reference getFuncId
        return this.funcId;
    }
    
    public void setFuncId(String funcId) { // DMAP Comment : Dead Code Detected - The Following Method has no reference setFuncId
        this.funcId = funcId;
    }
    
    public Integer getVersion() { // DMAP Comment : Dead Code Detected - The Following Method has no reference getVersion
        return this.version;
    }
    
    public void setVersion(Integer version) { // DMAP Comment : Dead Code Detected - The Following Method has no reference setVersion
        this.version = version;
    }
    
    public String getFuncName() { // DMAP Comment : Dead Code Detected - The Following Method has no reference getFuncName
        return this.funcName;
    }
    
    public void setFuncName(String funcName) { // DMAP Comment : Dead Code Detected - The Following Method has no reference setFuncName
        this.funcName = funcName;
    }
    
    public Integer getMenuLevel() { // DMAP Comment : Dead Code Detected - The Following Method has no reference getMenuLevel
        return this.menuLevel;
    }
    
    public void setMenuLevel(Integer menuLevel) { // DMAP Comment : Dead Code Detected - The Following Method has no reference setMenuLevel
        this.menuLevel = menuLevel;
    }
    
    public Integer getMenuSeq() { // DMAP Comment : Dead Code Detected - The Following Method has no reference getMenuSeq
        return this.menuSeq;
    }
    
    public void setMenuSeq(Integer menuSeq) { // DMAP Comment : Dead Code Detected - The Following Method has no reference setMenuSeq
        this.menuSeq = menuSeq;
    }
    
    public String getFuncMatherId() { // DMAP Comment : Dead Code Detected - The Following Method has no reference getFuncMatherId
        return this.funcMatherId;
    }
    
    public void setFuncMatherId(String funcMatherId) { // DMAP Comment : Dead Code Detected - The Following Method has no reference setFuncMatherId
        this.funcMatherId = funcMatherId;
    }
    
//    public IPFunction getFuncMather() {
//		return funcMather;
//	}
//
//	public void setFuncMather(IPFunction funcMather) {
//		this.funcMather = funcMather;
//	}


	public String getProgramId() { // DMAP Comment : Dead Code Detected - The Following Method has no reference getProgramId
        return this.programId;
    }
    
    public void setProgramId(String programId) { // DMAP Comment : Dead Code Detected - The Following Method has no reference setProgramId
        this.programId = programId;
    }
    
//    public String getProgramType() {
//        return this.programType;
//    }
//    
//    public void setProgramType(String programType) {
//        this.programType = programType;
//    }
    
    public String getProgramUrl() { // DMAP Comment : Dead Code Detected - The Following Method has no reference getProgramUrl
        return this.programUrl;
    }
    
    public void setProgramUrl(String programUrl) { // DMAP Comment : Dead Code Detected - The Following Method has no reference setProgramUrl
        this.programUrl = programUrl;
    }
    
    public String getStatusAdd() { // DMAP Comment : Dead Code Detected - The Following Method has no reference getStatusAdd
        return this.statusAdd;
    }
    
    public void setStatusAdd(String statusAdd) { // DMAP Comment : Dead Code Detected - The Following Method has no reference setStatusAdd
        this.statusAdd = statusAdd;
    }
    
    public String getStatusUpdate() { // DMAP Comment : Dead Code Detected - The Following Method has no reference getStatusUpdate
        return this.statusUpdate;
    }
    
    public void setStatusUpdate(String statusUpdate) { // DMAP Comment : Dead Code Detected - The Following Method has no reference setStatusUpdate
        this.statusUpdate = statusUpdate;
    }
    
    public String getStatusDelete() { // DMAP Comment : Dead Code Detected - The Following Method has no reference getStatusDelete
        return this.statusDelete;
    }
    
    public void setStatusDelete(String statusDelete) { // DMAP Comment : Dead Code Detected - The Following Method has no reference setStatusDelete
        this.statusDelete = statusDelete;
    }
    
    public String getStatusView() { // DMAP Comment : Dead Code Detected - The Following Method has no reference getStatusView
        return this.statusView;
    }
    
    public void setStatusView(String statusView) { // DMAP Comment : Dead Code Detected - The Following Method has no reference setStatusView
        this.statusView = statusView;
    }
    
    public String getStatusAdvance() { // DMAP Comment : Dead Code Detected - The Following Method has no reference getStatusAdvance
        return this.statusAdvance;
    }
    
    public void setStatusAdvance(String statusAdvance) { // DMAP Comment : Dead Code Detected - The Following Method has no reference setStatusAdvance
        this.statusAdvance = statusAdvance;
    }
    
    public String getCreateBy() { // DMAP Comment : Dead Code Detected - The Following Method has no reference getCreateBy
        return this.createBy;
    }
    
    public void setCreateBy(String createBy) { // DMAP Comment : Dead Code Detected - The Following Method has no reference setCreateBy
        this.createBy = createBy;
    }
    
    public Date getCreateDate() { // DMAP Comment : Dead Code Detected - The Following Method has no reference getCreateDate
        return this.createDate;
    }
    
    public void setCreateDate(Date createDate) { // DMAP Comment : Dead Code Detected - The Following Method has no reference setCreateDate
        this.createDate = createDate;
    }
    
	public String getUpdateBy() { // DMAP Comment : Dead Code Detected - The Following Method has no reference getUpdateBy
        return this.updateBy;
    }
    
    public void setUpdateBy(String updateBy) { // DMAP Comment : Dead Code Detected - The Following Method has no reference setUpdateBy
        this.updateBy = updateBy;
    }
    
    public Date getUpdateDate() { // DMAP Comment : Dead Code Detected - The Following Method has no reference getUpdateDate
        return this.updateDate;
    }
    
    public void setUpdateDate(Date updateDate) { // DMAP Comment : Dead Code Detected - The Following Method has no reference setUpdateDate
        this.updateDate = updateDate;
    }
    
	public String getRowId() { // DMAP Comment : Dead Code Detected - The Following Method has no reference getRowId
        return this.rowId;
    }
    
    public void setRowId(String rowId) { // DMAP Comment : Dead Code Detected - The Following Method has no reference setRowId
        this.rowId = rowId;
    }

	@Override
    public Object clone() throws CloneNotSupportedException
    {
		IPFunction another = (IPFunction) super.clone();
        //? take care of any deep copies to be made here
        return another;
    }


}


