package th.co.ais.ipfm.domain;
// Generated Jul 14, 2010 10:47:11 AM by Hibernate Tools 3.2.1.GA


import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Version;

import org.hibernate.annotations.GenericGenerator;

/**
 * IpRoleMember generated by hbm2java
 */
@Entity
@Table(name="IP_ROLE_MEMBER"
    ,schema="IPFMBK"
)
public class IPRoleMember  implements java.io.Serializable {

	 @Column(name="MEMBER_ID", nullable=false, length=10)
     private String memberId;
	 
	 @Version
	 @Column(name="VERSION")
     private Integer version;
	 
	 @JoinColumn(name = "ROLE_ID", referencedColumnName = "ROLE_ID", nullable = false)
	 @ManyToOne(optional = false, fetch = FetchType.LAZY)
	 private IPRole roleId;
	 
	 @Column(name="CREATE_BY", length=20)
     private String createBy;
	 
	 @Temporal(TemporalType.DATE)
	 @Column(name="CREATE_DATE", length=10)
     private Date createDate;
     
	 @Column(name="UPDATE_BY", length=20)
	 private String updateBy;
	 
	 @Temporal(TemporalType.DATE)
	 @Column(name="UPDATE_DATE", length=10)
     private Date updateDate;
	 
	 @Id
	 @GeneratedValue(generator="system-uuid")
	 @GenericGenerator(name="system-uuid", strategy = "uuid")
	 @Column(name="ROW_ID",nullable=false,length=50)
     private String rowId;
	 
	 

	 
    public IPRoleMember() {
    }

	
    public IPRoleMember(String memberId, IPRole roleId) {
        this.memberId = memberId;
        this.roleId = roleId;
    }
    public IPRoleMember(String memberId, IPRole roleId, String createBy, Date createDate, String updateBy, Date updateDate, String rowId) {
       this.memberId = memberId;
       this.roleId = roleId;
       this.createBy = createBy;
       this.createDate = createDate;
       this.updateBy = updateBy;
       this.updateDate = updateDate;
       this.rowId = rowId;
    }
   
    
    public String getMemberId() { // DMAP Comment : Dead Code Detected - The Following Method has no reference getMemberId
        return this.memberId;
    }
    
    public void setMemberId(String memberId) { // DMAP Comment : Dead Code Detected - The Following Method has no reference setMemberId
        this.memberId = memberId;
    }
    
    public Integer getVersion() { // DMAP Comment : Dead Code Detected - The Following Method has no reference getVersion
        return this.version;
    }
    
    public void setVersion(Integer version) { // DMAP Comment : Dead Code Detected - The Following Method has no reference setVersion
        this.version = version;
    }
    
    
    public String getCreateBy() { // DMAP Comment : Dead Code Detected - The Following Method has no reference getCreateBy
        return this.createBy;
    }
    
    public void setCreateBy(String createBy) { // DMAP Comment : Dead Code Detected - The Following Method has no reference setCreateBy
        this.createBy = createBy;
    }
    
    public Date getCreateDate() { // DMAP Comment : Dead Code Detected - The Following Method has no reference getCreateDate
        return this.createDate;
    }
    
    public void setCreateDate(Date createDate) { // DMAP Comment : Dead Code Detected - The Following Method has no reference setCreateDate
        this.createDate = createDate;
    }
    
    
    public String getUpdateBy() { // DMAP Comment : Dead Code Detected - The Following Method has no reference getUpdateBy
        return this.updateBy;
    }
    
    public void setUpdateBy(String updateBy) { // DMAP Comment : Dead Code Detected - The Following Method has no reference setUpdateBy
        this.updateBy = updateBy;
    }
    
    public Date getUpdateDate() { // DMAP Comment : Dead Code Detected - The Following Method has no reference getUpdateDate
        return this.updateDate;
    }
    
    public void setUpdateDate(Date updateDate) { // DMAP Comment : Dead Code Detected - The Following Method has no reference setUpdateDate
        this.updateDate = updateDate;
    }
    
    
    public String getRowId() { // DMAP Comment : Dead Code Detected - The Following Method has no reference getRowId
        return this.rowId;
    }
    
    public void setRowId(String rowId) { // DMAP Comment : Dead Code Detected - The Following Method has no reference setRowId
        this.rowId = rowId;
    }


	public IPRole getRoleId() { // DMAP Comment : Dead Code Detected - The Following Method has no reference getRoleId
		return roleId;
	}


	public void setRoleId(IPRole roleId) { // DMAP Comment : Dead Code Detected - The Following Method has no reference setRoleId
		this.roleId = roleId;
	}



}


