package th.co.ais.ipfm.domain;
// Generated Jul 14, 2010 10:47:11 AM by Hibernate Tools 3.2.1.GA


import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Version;

import org.hibernate.annotations.GenericGenerator;

/**
 * IpRoleFunction generated by hbm2java
 */
@Entity
@Table(name="IP_ROLE_FUNCTION"
    ,schema="IPFMBK"
)
public class IPRoleFunction  implements java.io.Serializable {

//	 @Id 
//     @Column(name="ROLE_ID", unique=true, nullable=false, length=10)
//     private String roleId;
//	 
//	 @Column(name="FUNC_ID", length=10)
//     private String funcId;

	 //@EmbeddedId
     //protected IPRoleFunctionPK pk;
	 
	 @JoinColumn(name = "FUNC_ID", referencedColumnName = "FUNC_ID", nullable = false)
	 @ManyToOne(optional = false, fetch = FetchType.LAZY)
	 private IPFunction functionId;
	 
	 @JoinColumn(name = "ROLE_ID", referencedColumnName = "ROLE_ID", nullable = false)
	 @ManyToOne(optional = false, fetch = FetchType.LAZY)
	 private IPRole roleId;

	 @Version
	 @Column(name="VERSION")
     private Integer version;
	 
	 
	 @Column(name="STATUS_ADD", length=10)
     private String statusAdd;
	 
	 @Column(name="STATUS_UPDATE", length=10)
     private String statusUpdate;
	 
	 @Column(name="STATUS_DELETE", length=10)
     private String statusDelete;
	 
	 @Column(name="STATUS_VIEW", length=10)
     private String statusView;
	 
	 @Column(name="STATUS_ADVANCE", length=10)
     private String statusAdvance;
	 
	 @Column(name="CREATE_BY", length=10)
     private String createBy;
	 
	 @Temporal(TemporalType.DATE)
	 @Column(name="CREATE_DATE", length=10)
     private Date createDate;
     
	 @Column(name="UPDATE_BY", length=10)
	 private String updateBy;
	 
	 @Temporal(TemporalType.DATE)
	 @Column(name="UPDATE_DATE", length=10)
     private Date updateDate;
	 
	 //@Column(name="ROW_ID", length=10)
	 @Id
	 @GeneratedValue(generator="system-uuid")
	 @GenericGenerator(name="system-uuid", strategy = "uuid")
	 @Column(name="ROW_ID",nullable=false,length=50)	
     private String rowId;

    public IPRoleFunction() {
    }

/*	
    public IPRoleFunction(IPRoleFunctionPK pk) {
        this.pk=pk;
    }
    public IPRoleFunction(IPRoleFunctionPK pk, String statusAdd, String statusUpdate, String statusDelete, String statusView, String statusAdvance, String createBy, Date createDate, String updateBy, Date updateDate, String rowId) {
       
       this.pk=pk;
       this.statusAdd = statusAdd;
       this.statusUpdate = statusUpdate;
       this.statusDelete = statusDelete;
       this.statusView = statusView;
       this.statusAdvance = statusAdvance;
       this.createBy = createBy;
       this.createDate = createDate;
       this.updateBy = updateBy;
       this.updateDate = updateDate;
       this.rowId = rowId;
    }
   
     
/*    public String getRoleId() {
        return this.roleId;
    }
    
    public void setRoleId(String roleId) {
        this.roleId = roleId;
    }
    */
    public Integer getVersion() { // DMAP Comment : Dead Code Detected - The Following Method has no reference getVersion
        return this.version;
    }
    
    public void setVersion(Integer version) { // DMAP Comment : Dead Code Detected - The Following Method has no reference setVersion
        this.version = version;
    }
    
/*    
    public String getFuncId() {
        return this.funcId;
    }
    
    public void setFuncId(String funcId) {
        this.funcId = funcId;
    }
*/    
    
    public String getStatusAdd() { // DMAP Comment : Dead Code Detected - The Following Method has no reference getStatusAdd
        return this.statusAdd;
    }
/*    
    public IPRoleFunctionPK getPk() {
		return pk;
	}


	public void setPk(IPRoleFunctionPK pk) {
		this.pk = pk;
	}
*/

	public void setStatusAdd(String statusAdd) { // DMAP Comment : Dead Code Detected - The Following Method has no reference setStatusAdd
        this.statusAdd = statusAdd;
    }
    
    
    public String getStatusUpdate() { // DMAP Comment : Dead Code Detected - The Following Method has no reference getStatusUpdate
        return this.statusUpdate;
    }
    
    public void setStatusUpdate(String statusUpdate) { // DMAP Comment : Dead Code Detected - The Following Method has no reference setStatusUpdate
        this.statusUpdate = statusUpdate;
    }
    
    
    public String getStatusDelete() { // DMAP Comment : Dead Code Detected - The Following Method has no reference getStatusDelete
        return this.statusDelete;
    }
    
    public void setStatusDelete(String statusDelete) { // DMAP Comment : Dead Code Detected - The Following Method has no reference setStatusDelete
        this.statusDelete = statusDelete;
    }
    
    
    public String getStatusView() { // DMAP Comment : Dead Code Detected - The Following Method has no reference getStatusView
        return this.statusView;
    }
    
    public void setStatusView(String statusView) { // DMAP Comment : Dead Code Detected - The Following Method has no reference setStatusView
        this.statusView = statusView;
    }
    
    
    public String getStatusAdvance() { // DMAP Comment : Dead Code Detected - The Following Method has no reference getStatusAdvance
        return this.statusAdvance;
    }
    
    public void setStatusAdvance(String statusAdvance) { // DMAP Comment : Dead Code Detected - The Following Method has no reference setStatusAdvance
        this.statusAdvance = statusAdvance;
    }
    
    
    public String getCreateBy() { // DMAP Comment : Dead Code Detected - The Following Method has no reference getCreateBy
        return this.createBy;
    }
    
    public void setCreateBy(String createBy) { // DMAP Comment : Dead Code Detected - The Following Method has no reference setCreateBy
        this.createBy = createBy;
    }
    
    public Date getCreateDate() { // DMAP Comment : Dead Code Detected - The Following Method has no reference getCreateDate
        return this.createDate;
    }
    
    public void setCreateDate(Date createDate) { // DMAP Comment : Dead Code Detected - The Following Method has no reference setCreateDate
        this.createDate = createDate;
    }
    
    
    public String getUpdateBy() { // DMAP Comment : Dead Code Detected - The Following Method has no reference getUpdateBy
        return this.updateBy;
    }
    
    public void setUpdateBy(String updateBy) { // DMAP Comment : Dead Code Detected - The Following Method has no reference setUpdateBy
        this.updateBy = updateBy;
    }
    
    public Date getUpdateDate() { // DMAP Comment : Dead Code Detected - The Following Method has no reference getUpdateDate
        return this.updateDate;
    }
    
    public void setUpdateDate(Date updateDate) { // DMAP Comment : Dead Code Detected - The Following Method has no reference setUpdateDate
        this.updateDate = updateDate;
    }
    
    
    public String getRowId() { // DMAP Comment : Dead Code Detected - The Following Method has no reference getRowId
        return this.rowId;
    }
    
    public void setRowId(String rowId) { // DMAP Comment : Dead Code Detected - The Following Method has no reference setRowId
        this.rowId = rowId;
    }


	public IPFunction getFunctionId() { // DMAP Comment : Dead Code Detected - The Following Method has no reference getFunctionId
		return functionId;
	}


	public void setFunctionId(IPFunction functionId) { // DMAP Comment : Dead Code Detected - The Following Method has no reference setFunctionId
		this.functionId = functionId;
	}


	public IPRole getRoleId() { // DMAP Comment : Dead Code Detected - The Following Method has no reference getRoleId
		return roleId;
	}


	public void setRoleId(IPRole roleId) { // DMAP Comment : Dead Code Detected - The Following Method has no reference setRoleId
		this.roleId = roleId;
	}





}


