package th.co.ais.ipfm.domain;


// Generated 23 ?.?. 2553, 14:39:58 by Hibernate Tools 3.2.1.GA


import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Version;

import org.hibernate.annotations.GenericGenerator;

/**
 * IpUrIp generated by hbm2java
 */
@Entity
@Table(name="IP_UR_IP"
    ,schema="IPFMBK"
)
public class IPUrIP extends MasterDomain implements java.io.Serializable {


     /**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private String rowId;
     private Long version;
     private String urNo;
     private String reqType;
     private String reqUserId;
     private String reqName;
     private String reqSection;
     private String reqDept;
     private String reqEmail;
     private String reqPosition;
     private String reqMobile;
     private String reqTel;
     private String reqTeam;
     private String reqSubject;
     private Date reqDate;
     private String t2TeamId;
     private String t2TeamName;
     private String projectId;
     private String projectName;
     private String prjManagerId;
     private String prjManagerName;
     private String sysOwnerId;
     private String sysOwnerName;
     private String sysOwnerTeamId;
     private String sysOwnerTeamName;
     private String contactPoint;
     private String nwSysDetail;
     private String networkTypeId;
     private String networkTypeName;
     private String networkType;
     private String isNewNetwork;
     private String isExpanNetwork;
     private String newZoneId;
     private String newZoneName;
     private String expanZoneId;
     private String expanZoneName;
     private String expanIpRef;
     private String newDataCenterId;
     private String newDataCenterName;
     private String newOfficeId;
     private String newOfficeName;
     private String expanDataCenterId;
     private String expanDataCenterName;
     private String expanOfficeId;
     private String expanOfficeName;
     private String totalNode;
     private String classb;
     private String classc;
     private String isNwdiagram;
     private String isAppdiagram;
     private String systemPlane;
     private String userPlane;
     private String mrgRemark;
     private String t2remark;
     private String t1remark;
     private String urStatus;

    public IPUrIP() {
    }

	
    public IPUrIP(String rowId, String urNo) {
        this.rowId = rowId;
        this.urNo = urNo;
    }
    public IPUrIP(String rowId, String urNo, String reqType, String reqUserId, String reqName, String reqSection, String reqDept, String reqEmail, String reqPosition, String reqMobile, String reqTel, String reqTeam, String reqSubject, Date reqDate, String t2TeamId, String t2TeamName, String projectId, String projectName, String prjManagerId, String prjManagerName, String sysOwnerId, String sysOwnerName, String sysOwnerTeamId, String sysOwnerTeamName, String contactPoint, String nwSysDetail, String networkTypeId, String networkTypeName, String networkType, String isNewNetwork, String isExpanNetwork, String newZoneId, String newZoneName, String expanZoneId, String expanZoneName, String expanIpRef, String newDataCenterId, String newDataCenterName, String newOfficeId, String newOfficeName, String expanDataCenterId, String expanDataCenterName, String expanOfficeId, String expanOfficeName, String totalNode, String classb, String classc, String isNwdiagram, String isAppdiagram, String systemPlane, String userPlane, String mrgRemark, String t2remark, String t1remark, String urStatus, String createBy, Date createDate, String updateBy, Date updateDate) {
       this.rowId = rowId;
       this.urNo = urNo;
       this.reqType = reqType;
       this.reqUserId = reqUserId;
       this.reqName = reqName;
       this.reqSection = reqSection;
       this.reqDept = reqDept;
       this.reqEmail = reqEmail;
       this.reqPosition = reqPosition;
       this.reqMobile = reqMobile;
       this.reqTel = reqTel;
       this.reqTeam = reqTeam;
       this.reqSubject = reqSubject;
       this.reqDate = reqDate;
       this.t2TeamId = t2TeamId;
       this.t2TeamName = t2TeamName;
       this.projectId = projectId;
       this.projectName = projectName;
       this.prjManagerId = prjManagerId;
       this.prjManagerName = prjManagerName;
       this.sysOwnerId = sysOwnerId;
       this.sysOwnerName = sysOwnerName;
       this.sysOwnerTeamId = sysOwnerTeamId;
       this.sysOwnerTeamName = sysOwnerTeamName;
       this.contactPoint = contactPoint;
       this.nwSysDetail = nwSysDetail;
       this.networkTypeId = networkTypeId;
       this.networkTypeName = networkTypeName;
       this.networkType = networkType;
       this.isNewNetwork = isNewNetwork;
       this.isExpanNetwork = isExpanNetwork;
       this.newZoneId = newZoneId;
       this.newZoneName = newZoneName;
       this.expanZoneId = expanZoneId;
       this.expanZoneName = expanZoneName;
       this.expanIpRef = expanIpRef;
       this.newDataCenterId = newDataCenterId;
       this.newDataCenterName = newDataCenterName;
       this.newOfficeId = newOfficeId;
       this.newOfficeName = newOfficeName;
       this.expanDataCenterId = expanDataCenterId;
       this.expanDataCenterName = expanDataCenterName;
       this.expanOfficeId = expanOfficeId;
       this.expanOfficeName = expanOfficeName;
       this.totalNode = totalNode;
       this.classb = classb;
       this.classc = classc;
       this.isNwdiagram = isNwdiagram;
       this.isAppdiagram = isAppdiagram;
       this.systemPlane = systemPlane;
       this.userPlane = userPlane;
       this.mrgRemark = mrgRemark;
       this.t2remark = t2remark;
       this.t1remark = t1remark;
       this.urStatus = urStatus;
    }
   
    @Id 
	@GeneratedValue(generator="system-uuid")
	@GenericGenerator(name="system-uuid", strategy = "uuid")
    @Column(name="ROW_ID", unique=true, nullable=false, length=50)
    public String getRowId() {
        return this.rowId;
    }
    
    public void setRowId(String rowId) {
        this.rowId = rowId;
    }
    @Version
    @Column(name="VERSION", precision=10, scale=0)
    public Long getVersion() {
        return this.version;
    }
    
    public void setVersion(Long version) {
        this.version = version;
    }
    
    @Column(name="UR_NO", nullable=false, length=30)
    public String getUrNo() {
        return this.urNo;
    }
    
    public void setUrNo(String urNo) {
        this.urNo = urNo;
    }
    
    @Column(name="REQ_TYPE", length=5)
    public String getReqType() {
        return this.reqType;
    }
    
    public void setReqType(String reqType) {
        this.reqType = reqType;
    }
    
    @Column(name="REQ_USER_ID", length=20)
    public String getReqUserId() {
        return this.reqUserId;
    }
    
    public void setReqUserId(String reqUserId) {
        this.reqUserId = reqUserId;
    }
    
    @Column(name="REQ_NAME", length=100)
    public String getReqName() {
        return this.reqName;
    }
    
    public void setReqName(String reqName) {
        this.reqName = reqName;
    }
    
    @Column(name="REQ_SECTION", length=100)
    public String getReqSection() {
        return this.reqSection;
    }
    
    public void setReqSection(String reqSection) {
        this.reqSection = reqSection;
    }
    
    @Column(name="REQ_DEPT", length=100)
    public String getReqDept() {
        return this.reqDept;
    }
    
    public void setReqDept(String reqDept) {
        this.reqDept = reqDept;
    }
    
    @Column(name="REQ_EMAIL", length=100)
    public String getReqEmail() {
        return this.reqEmail;
    }
    
    public void setReqEmail(String reqEmail) {
        this.reqEmail = reqEmail;
    }
    
    @Column(name="REQ_POSITION", length=100)
    public String getReqPosition() {
        return this.reqPosition;
    }
    
    public void setReqPosition(String reqPosition) {
        this.reqPosition = reqPosition;
    }
    
    @Column(name="REQ_MOBILE", length=100)
    public String getReqMobile() {
        return this.reqMobile;
    }
    
    public void setReqMobile(String reqMobile) {
        this.reqMobile = reqMobile;
    }
    
    @Column(name="REQ_TEL", length=100)
    public String getReqTel() {
        return this.reqTel;
    }
    
    public void setReqTel(String reqTel) {
        this.reqTel = reqTel;
    }
    
    @Column(name="REQ_TEAM", length=100)
    public String getReqTeam() {
        return this.reqTeam;
    }
    
    public void setReqTeam(String reqTeam) {
        this.reqTeam = reqTeam;
    }
    
    @Column(name="REQ_SUBJECT", length=1000)
    public String getReqSubject() {
        return this.reqSubject;
    }
    
    public void setReqSubject(String reqSubject) {
        this.reqSubject = reqSubject;
    }
    @Temporal(TemporalType.DATE)
    @Column(name="REQ_DATE", length=7)
    public Date getReqDate() {
        return this.reqDate;
    }
    
    public void setReqDate(Date reqDate) {
        this.reqDate = reqDate;
    }
    
    @Column(name="T2_TEAM_ID", length=10)
    public String getT2TeamId() {
        return this.t2TeamId;
    }
    
    public void setT2TeamId(String t2TeamId) {
        this.t2TeamId = t2TeamId;
    }
    
    @Column(name="T2_TEAM_NAME", length=1000)
    public String getT2TeamName() {
        return this.t2TeamName;
    }
    
    public void setT2TeamName(String t2TeamName) {
        this.t2TeamName = t2TeamName;
    }
    
    @Column(name="PROJECT_ID", length=30)
    public String getProjectId() {
        return this.projectId;
    }
    
    public void setProjectId(String projectId) {
        this.projectId = projectId;
    }
    
    @Column(name="PROJECT_NAME", length=1000)
    public String getProjectName() {
        return this.projectName;
    }
    
    public void setProjectName(String projectName) {
        this.projectName = projectName;
    }
    
    @Column(name="PRJ_MANAGER_ID", length=20)
    public String getPrjManagerId() {
        return this.prjManagerId;
    }
    
    public void setPrjManagerId(String prjManagerId) {
        this.prjManagerId = prjManagerId;
    }
    
    @Column(name="PRJ_MANAGER_NAME", length=1000)
    public String getPrjManagerName() {
        return this.prjManagerName;
    }
    
    public void setPrjManagerName(String prjManagerName) {
        this.prjManagerName = prjManagerName;
    }
    
    @Column(name="SYS_OWNER_ID", length=20)
    public String getSysOwnerId() {
        return this.sysOwnerId;
    }
    
    public void setSysOwnerId(String sysOwnerId) {
        this.sysOwnerId = sysOwnerId;
    }
    
    @Column(name="SYS_OWNER_NAME", length=1000)
    public String getSysOwnerName() {
        return this.sysOwnerName;
    }
    
    public void setSysOwnerName(String sysOwnerName) {
        this.sysOwnerName = sysOwnerName;
    }
    
    @Column(name="SYS_OWNER_TEAM_ID", length=10)
    public String getSysOwnerTeamId() {
        return this.sysOwnerTeamId;
    }
    
    public void setSysOwnerTeamId(String sysOwnerTeamId) {
        this.sysOwnerTeamId = sysOwnerTeamId;
    }
    
    @Column(name="SYS_OWNER_TEAM_NAME", length=1000)
    public String getSysOwnerTeamName() {
        return this.sysOwnerTeamName;
    }
    
    public void setSysOwnerTeamName(String sysOwnerTeamName) {
        this.sysOwnerTeamName = sysOwnerTeamName;
    }
    
    @Column(name="CONTACT_POINT", length=1000)
    public String getContactPoint() {
        return this.contactPoint;
    }
    
    public void setContactPoint(String contactPoint) {
        this.contactPoint = contactPoint;
    }
    
    @Column(name="NW_SYS_DETAIL", length=1000)
    public String getNwSysDetail() {
        return this.nwSysDetail;
    }
    
    public void setNwSysDetail(String nwSysDetail) {
        this.nwSysDetail = nwSysDetail;
    }
    
    @Column(name="NETWORK_TYPE_ID", length=10)
    public String getNetworkTypeId() {
        return this.networkTypeId;
    }
    
    public void setNetworkTypeId(String networkTypeId) {
        this.networkTypeId = networkTypeId;
    }
    
    @Column(name="NETWORK_TYPE_NAME", length=1000)
    public String getNetworkTypeName() {
        return this.networkTypeName;
    }
    
    public void setNetworkTypeName(String networkTypeName) {
        this.networkTypeName = networkTypeName;
    }
    
    @Column(name="NETWORK_TYPE", length=1)
    public String getNetworkType() {
        return this.networkType;
    }
    
    public void setNetworkType(String networkType) {
        this.networkType = networkType;
    }
    
    @Column(name="IS_NEW_NETWORK", length=1)
    public String getIsNewNetwork() {
        return this.isNewNetwork;
    }
    
    public void setIsNewNetwork(String isNewNetwork) {
        this.isNewNetwork = isNewNetwork;
    }
    
    @Column(name="IS_EXPAN_NETWORK", length=1)
    public String getIsExpanNetwork() {
        return this.isExpanNetwork;
    }
    
    public void setIsExpanNetwork(String isExpanNetwork) {
        this.isExpanNetwork = isExpanNetwork;
    }
    
    @Column(name="NEW_ZONE_ID", length=10)
    public String getNewZoneId() {
        return this.newZoneId;
    }
    
    public void setNewZoneId(String newZoneId) {
        this.newZoneId = newZoneId;
    }
    
    @Column(name="NEW_ZONE_NAME", length=1000)
    public String getNewZoneName() {
        return this.newZoneName;
    }
    
    public void setNewZoneName(String newZoneName) {
        this.newZoneName = newZoneName;
    }
    
    @Column(name="EXPAN_ZONE_ID", length=10)
    public String getExpanZoneId() {
        return this.expanZoneId;
    }
    
    public void setExpanZoneId(String expanZoneId) {
        this.expanZoneId = expanZoneId;
    }
    
    @Column(name="EXPAN_ZONE_NAME", length=1000)
    public String getExpanZoneName() {
        return this.expanZoneName;
    }
    
    public void setExpanZoneName(String expanZoneName) {
        this.expanZoneName = expanZoneName;
    }
    
    @Column(name="EXPAN_IP_REF", length=1000)
    public String getExpanIpRef() {
        return this.expanIpRef;
    }
    
    public void setExpanIpRef(String expanIpRef) {
        this.expanIpRef = expanIpRef;
    }
    
    @Column(name="NEW_DATA_CENTER_ID", length=10)
    public String getNewDataCenterId() {
        return this.newDataCenterId;
    }
    
    public void setNewDataCenterId(String newDataCenterId) {
        this.newDataCenterId = newDataCenterId;
    }
    
    @Column(name="NEW_DATA_CENTER_NAME", length=1000)
    public String getNewDataCenterName() {
        return this.newDataCenterName;
    }
    
    public void setNewDataCenterName(String newDataCenterName) {
        this.newDataCenterName = newDataCenterName;
    }
    
    @Column(name="NEW_OFFICE_ID", length=10)
    public String getNewOfficeId() {
        return this.newOfficeId;
    }
    
    public void setNewOfficeId(String newOfficeId) {
        this.newOfficeId = newOfficeId;
    }
    
    @Column(name="NEW_OFFICE_NAME", length=1000)
    public String getNewOfficeName() {
        return this.newOfficeName;
    }
    
    public void setNewOfficeName(String newOfficeName) {
        this.newOfficeName = newOfficeName;
    }
    
    @Column(name="EXPAN_DATA_CENTER_ID", length=10)
    public String getExpanDataCenterId() {
        return this.expanDataCenterId;
    }
    
    public void setExpanDataCenterId(String expanDataCenterId) {
        this.expanDataCenterId = expanDataCenterId;
    }
    
    @Column(name="EXPAN_DATA_CENTER_NAME", length=1000)
    public String getExpanDataCenterName() {
        return this.expanDataCenterName;
    }
    
    public void setExpanDataCenterName(String expanDataCenterName) {
        this.expanDataCenterName = expanDataCenterName;
    }
    
    @Column(name="EXPAN_OFFICE_ID", length=10)
    public String getExpanOfficeId() {
        return this.expanOfficeId;
    }
    
    public void setExpanOfficeId(String expanOfficeId) {
        this.expanOfficeId = expanOfficeId;
    }
    
    @Column(name="EXPAN_OFFICE_NAME", length=1000)
    public String getExpanOfficeName() {
        return this.expanOfficeName;
    }
    
    public void setExpanOfficeName(String expanOfficeName) {
        this.expanOfficeName = expanOfficeName;
    }
    
    @Column(name="TOTAL_NODE", length=10)
    public String getTotalNode() {
        return this.totalNode;
    }
    
    public void setTotalNode(String totalNode) {
        this.totalNode = totalNode;
    }
    
    @Column(name="CLASSB", length=10)
    public String getClassb() {
        return this.classb;
    }
    
    public void setClassb(String classb) {
        this.classb = classb;
    }
    
    @Column(name="CLASSC", length=10)
    public String getClassc() {
        return this.classc;
    }
    
    public void setClassc(String classc) {
        this.classc = classc;
    }
    
    @Column(name="IS_NWDIAGRAM", length=1)
    public String getIsNwdiagram() {
        return this.isNwdiagram;
    }
    
    public void setIsNwdiagram(String isNwdiagram) {
        this.isNwdiagram = isNwdiagram;
    }
    
    @Column(name="IS_APPDIAGRAM", length=1)
    public String getIsAppdiagram() {
        return this.isAppdiagram;
    }
    
    public void setIsAppdiagram(String isAppdiagram) {
        this.isAppdiagram = isAppdiagram;
    }
    
    @Column(name="SYSTEM_PLANE", length=1000)
    public String getSystemPlane() {
        return this.systemPlane;
    }
    
    public void setSystemPlane(String systemPlane) {
        this.systemPlane = systemPlane;
    }
    
    @Column(name="USER_PLANE")
    public String getUserPlane() {
        return this.userPlane;
    }
    
    public void setUserPlane(String userPlane) {
        this.userPlane = userPlane;
    }
    
    @Column(name="MRG_REMARK", length=1000)
    public String getMrgRemark() {
        return this.mrgRemark;
    }
    
    public void setMrgRemark(String mrgRemark) {
        this.mrgRemark = mrgRemark;
    }
    
    @Column(name="T2REMARK", length=1000)
    public String getT2remark() {
        return this.t2remark;
    }
    
    public void setT2remark(String t2remark) {
        this.t2remark = t2remark;
    }
    
    @Column(name="T1REMARK", length=1000)
    public String getT1remark() {
        return this.t1remark;
    }
    
    public void setT1remark(String t1remark) {
        this.t1remark = t1remark;
    }
    
    @Column(name="UR_STATUS", length=100)
    public String getUrStatus() {
        return this.urStatus;
    }
    
    public void setUrStatus(String urStatus) {
        this.urStatus = urStatus;
    }
    
    @Column(name="CREATE_BY")
	public String getCreatedBy() {
		return createdBy;
	}

	public void setCreatedBy(String createdBy) {
		this.createdBy = createdBy;
	}

	@Column(name="CREATE_DATE")
	public Date getCreated() {
		return created;
	}

	public void setCreated(Date created) {
		this.created = created;
	}

	@Column(name="UPDATE_BY")
	public String getLastUpdBy() {
		return lastUpdBy;
	}

	public void setLastUpdBy(String lastUpdBy) {
		this.lastUpdBy = lastUpdBy;
	}
	
	@Column(name="UPDATE_DATE")
	public Date getLastUpd() {
		return lastUpd;
	}
	
	public void setLastUpd(Date lastUpd) {
		this.lastUpd = lastUpd;
	}
}


