package th.co.ais.ipfm.domain1;
// Generated 8 µ.¤. 2553, 16:51:31 by Hibernate Tools 3.2.1.GA


import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Embeddable;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;

import org.hibernate.annotations.GenericGenerator;

import th.co.ais.ipfm.domain.MasterDomain;

/**
 * IpDelegateUserId generated by hbm2java
 */
@Embeddable
public class IpDelegateUserId    implements java.io.Serializable {


     private String userId;
     private String delegateUserId;

    public IpDelegateUserId() {
    }

    public IpDelegateUserId(String userId, String delegateUserId) {
       this.userId = userId;
       this.delegateUserId = delegateUserId;
    }
   
    @Column(name="USER_ID", nullable=false, length=20)
    public String getUserId() {
        return this.userId;
    }
    
    public void setUserId(String userId) {
        this.userId = userId;
    }
    
    @Column(name="DELEGATE_USER_ID", nullable=false, length=20)
    public String getDelegateUserId() {
        return this.delegateUserId;
    }
    
    public void setDelegateUserId(String delegateUserId) {
        this.delegateUserId = delegateUserId;
    }


public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof IpDelegateUserId) ) return false;
		 IpDelegateUserId castOther = ( IpDelegateUserId ) other; 
         
		 return ( (this.getUserId()==castOther.getUserId()) || ( this.getUserId()!=null && castOther.getUserId()!=null && this.getUserId().equals(castOther.getUserId()) ) )
 && ( (this.getDelegateUserId()==castOther.getDelegateUserId()) || ( this.getDelegateUserId()!=null && castOther.getDelegateUserId()!=null && this.getDelegateUserId().equals(castOther.getDelegateUserId()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getUserId() == null ? 0 : this.getUserId().hashCode() );
         result = 37 * result + ( getDelegateUserId() == null ? 0 : this.getDelegateUserId().hashCode() );
         return result;
   }   


}


