package th.co.ais.ipfm.domain1;
// Generated 27 �.�. 2553, 17:13:55 by Hibernate Tools 3.2.1.GA


import java.math.BigDecimal;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Transient;
import javax.persistence.UniqueConstraint;
import javax.persistence.Version;

import org.hibernate.annotations.GenericGenerator;

import th.co.ais.ipfm.domain.MasterDomain;

/**
 * IpInfo generated by hbm2java
 */
@Entity
@Table(name="IP_INFO_HISTORY"
    , uniqueConstraints = @UniqueConstraint(columnNames="ROW_ID") 
)
public class IpInfoHistory extends MasterDomain implements java.io.Serializable,Cloneable {


     private String ipAddress;
     private Long version;
     private String ipVersion;
     private String ipSubmask;
     private BigDecimal ipv4digit1;
     private BigDecimal ipv4digit2;
     private BigDecimal ipv4digit3;
     private BigDecimal ipv4digit4;
     private BigDecimal ipv6digit1;
     private BigDecimal ipv6digit2;
     private BigDecimal ipv6digit3;
     private BigDecimal ipv6digit4;
     private BigDecimal ipv6digit5;
     private BigDecimal ipv6digit6;
     private String level1Id;
     private String level2Id;
     private IpLevel2 ipLevel2;
     private String binaryIp;
     private String ipStatus;
     private IpMasterTable status;
     private String companyId;
     private String companyName;
     private String locationId;
     private String locationName;
     private String ipTypeId;
     private String ipTypeName;
     private String vip;
     private String installTypeId;
     private String installTypeName;
     private String networkZoneId;
     private String networkZoneName;
     private String submask;
     private String networkIp;
     private String gateway;
     private String macAddress;
     private String hostName;
     private String systemName;
     private String networkTypeId;
     private String networkTypeName;
     private String t2TeamId;
     private String t2TeamName;
     private IpTeam t2Team;
     private String urRefer;
     private String projectId;
     private String projectName;
     private String projectManager;
     private Date effectiveDate;
     private Date expiredDate;
     private IpUser systemOwnerId;
     private String systemOwner;
     private String systemOwnerName;
     private String systemOwnerTeamId;
     private String systemOwnerTeamName;
     private String vlanId;
     private String dnsName;
     private String t1TeamId;
     private String t1TeamName;
     private String t1Remark;
     private String t2Remark;
     private String t3Remark;
     private String wyNodeName;
     private String rowId;
     private boolean rowCheck;
     private boolean buttonCheck = false;
     private boolean buttonDisable = false;
     private String stIp1;
     private String stIp2;
     private String stIp3;
     private String stIp4;
     private String userPermission;
     private String binaryIpStart;
     private String binaryIpEnd;
     private String v_bin_start;
     private Integer subNet;
     private Integer totalIP;
     private Integer availableIP;
     private String result;
     
    public IpInfoHistory() {
    }
    
    public IpInfoHistory(String ipAddress) {
        this.ipAddress = ipAddress;
    }
    
	@Column(name="IP_ADDRESS", unique=true, nullable=false, length=21)
    public String getIpAddress() {
        return this.ipAddress;
    }
    
    public void setIpAddress(String ipAddress) {
        this.ipAddress = ipAddress;
    }
    @Version
    @Column(name="VERSION", precision=10, scale=0)
    public Long getVersion() {
        return this.version;
    }
    
    public void setVersion(Long version) {
        this.version = version;
    }
    
    @Column(name="IP_VERSION", length=1)
    public String getIpVersion() {
        return this.ipVersion;
    }
    
    public void setIpVersion(String ipVersion) {
        this.ipVersion = ipVersion;
    }
    
    @Column(name="IP_SUBMASK", length=5)
    public String getIpSubmask() {
        return this.ipSubmask;
    }
    
    public void setIpSubmask(String ipSubmask) {
        this.ipSubmask = ipSubmask;
    }
    
    @Column(name="IPV4DIGIT1", precision=22, scale=0)
    public BigDecimal getIpv4digit1() {
        return this.ipv4digit1;
    }
    
    public void setIpv4digit1(BigDecimal ipv4digit1) {
        this.ipv4digit1 = ipv4digit1;
    }
    
    @Column(name="IPV4DIGIT2", precision=22, scale=0)
    public BigDecimal getIpv4digit2() {
        return this.ipv4digit2;
    }
    
    public void setIpv4digit2(BigDecimal ipv4digit2) {
        this.ipv4digit2 = ipv4digit2;
    }
    
    @Column(name="IPV4DIGIT3", precision=22, scale=0)
    public BigDecimal getIpv4digit3() {
        return this.ipv4digit3;
    }
    
    public void setIpv4digit3(BigDecimal ipv4digit3) {
        this.ipv4digit3 = ipv4digit3;
    }
    
    @Column(name="IPV4DIGIT4", precision=22, scale=0)
    public BigDecimal getIpv4digit4() {
        return this.ipv4digit4;
    }
    
    public void setIpv4digit4(BigDecimal ipv4digit4) {
        this.ipv4digit4 = ipv4digit4;
    }
    
    @Column(name="IPV6DIGIT1", precision=22, scale=0)
    public BigDecimal getIpv6digit1() {
        return this.ipv6digit1;
    }
    
    public void setIpv6digit1(BigDecimal ipv6digit1) {
        this.ipv6digit1 = ipv6digit1;
    }
    
    @Column(name="IPV6DIGIT2", precision=22, scale=0)
    public BigDecimal getIpv6digit2() {
        return this.ipv6digit2;
    }
    
    public void setIpv6digit2(BigDecimal ipv6digit2) {
        this.ipv6digit2 = ipv6digit2;
    }
    
    @Column(name="IPV6DIGIT3", precision=22, scale=0)
    public BigDecimal getIpv6digit3() {
        return this.ipv6digit3;
    }
    
    public void setIpv6digit3(BigDecimal ipv6digit3) {
        this.ipv6digit3 = ipv6digit3;
    }
    
    @Column(name="IPV6DIGIT4", precision=22, scale=0)
    public BigDecimal getIpv6digit4() {
        return this.ipv6digit4;
    }
    
    public void setIpv6digit4(BigDecimal ipv6digit4) {
        this.ipv6digit4 = ipv6digit4;
    }
    
    @Column(name="IPV6DIGIT5", precision=22, scale=0)
    public BigDecimal getIpv6digit5() {
        return this.ipv6digit5;
    }
    
    public void setIpv6digit5(BigDecimal ipv6digit5) {
        this.ipv6digit5 = ipv6digit5;
    }
    
    @Column(name="IPV6DIGIT6", precision=22, scale=0)
    public BigDecimal getIpv6digit6() {
        return this.ipv6digit6;
    }
    
    public void setIpv6digit6(BigDecimal ipv6digit6) {
        this.ipv6digit6 = ipv6digit6;
    }
    
    @Column(name="LEVEL1_ID", length=5)
    public String getLevel1Id() {
        return this.level1Id;
    }
    
    public void setLevel1Id(String level1Id) {
        this.level1Id = level1Id;
    }
    
    @Column(name="LEVEL2_ID", length=5)
    public String getLevel2Id() {
        return this.level2Id;
    }
    
    public void setLevel2Id(String level2Id) {
        this.level2Id = level2Id;
    }
    
    @Column(name="BINARY_IP", length=35)
    public String getBinaryIp() {
        return this.binaryIp;
    }
    
    public void setBinaryIp(String binaryIp) {
        this.binaryIp = binaryIp;
    }

    @Column(name="IP_STATUS", length=2)
    public String getIpStatus() {
        return this.ipStatus;
    }
    
    public void setIpStatus(String ipStatus) {
        this.ipStatus = ipStatus;
    }
    
    @Transient
    public String getStatusName(){
    	String str="";
    	if (this.ipStatus != null && this.ipStatus.trim().length()>0) {
    		if (this.ipStatus.equalsIgnoreCase("P")){
    			str="Assign To Planning";
    		}else if (this.ipStatus.equalsIgnoreCase("N")){
    			str="Available";
    		}else if (this.ipStatus.equalsIgnoreCase("U")){
    			str="Used";
    		}else if (this.ipStatus.equalsIgnoreCase("T")){
    			str="Terminate";
    		}else if (this.ipStatus.equalsIgnoreCase("A")){
    			str="Assign to User";
    		}else if (this.ipStatus.equalsIgnoreCase("R")){
    			str="Reserved";
    		}
    	}
    	return str;
    }
    
    @Column(name="COMPANY_ID")
    public String getCompanyId() {
        return this.companyId;
    }
    
    public void setCompanyId(String companyId) {
        this.companyId = companyId;
    }
    
    @Column(name="COMPANY_NAME", length=1000)
    public String getCompanyName() {
        return this.companyName;
    }
    
    public void setCompanyName(String companyName) {
        this.companyName = companyName;
    }
    
    @Column(name="LOCATION_ID")
    public String getLocationId() {
        return this.locationId;
    }
    
    public void setLocationId(String locationId) {
        this.locationId = locationId;
    }
    
    @Column(name="LOCATION_NAME", length=1000)
    public String getLocationName() {
        return this.locationName;
    }
    
    public void setLocationName(String locationName) {
        this.locationName = locationName;
    }
    
    @Column(name="IP_TYPE_ID")
    public String getIpTypeId() {
        return this.ipTypeId;
    }
    
    public void setIpTypeId(String ipTypeId) {
        this.ipTypeId = ipTypeId;
    }
    
    @Column(name="IP_TYPE_NAME", length=1000)
    public String getIpTypeName() {
        return this.ipTypeName;
    }
    
    public void setIpTypeName(String ipTypeName) {
        this.ipTypeName = ipTypeName;
    }
    
    @Column(name="VIP", length=1)
    public String getVip() {
        return this.vip;
    }
    
    public void setVip(String vip) {
        this.vip = vip;
    }
    
    @Column(name="INSTALL_TYPE_ID")
    public String getInstallTypeId() {
        return this.installTypeId;
    }
    
    public void setInstallTypeId(String installTypeId) {
        this.installTypeId = installTypeId;
    }
    
    @Column(name="INSTALL_TYPE_NAME", length=1000)
    public String getInstallTypeName() {
        return this.installTypeName;
    }
    
    public void setInstallTypeName(String installTypeName) {
        this.installTypeName = installTypeName;
    }
    
    @Column(name="NETWORK_ZONE_ID")
    public String getNetworkZoneId() {
        return this.networkZoneId;
    }
    
    public void setNetworkZoneId(String networkZoneId) {
        this.networkZoneId = networkZoneId;
    }
    
    @Column(name="NETWORK_ZONE_NAME", length=1000)
    public String getNetworkZoneName() {
        return this.networkZoneName;
    }
    
    public void setNetworkZoneName(String networkZoneName) {
        this.networkZoneName = networkZoneName;
    }
    @Transient
    public String getSubmaskDesc(){
    	if (submask!=null && submask.trim().length()>0) {
    		return "/"+submask;
    	}
    	return "";
    }
    
    @Column(name="SUBMASK", length=30)
    public String getSubmask() {
        return this.submask;
    }
    
    public void setSubmask(String submask) {
        this.submask = submask;
    }
    
    @Column(name="NETWORK_IP", length=30)
    public String getNetworkIp() {
        return this.networkIp;
    }
    
    public void setNetworkIp(String networkIp) {
        this.networkIp = networkIp;
    }
    
    @Column(name="GATEWAY", length=30)
    public String getGateway() {
        return this.gateway;
    }
    
    public void setGateway(String gateway) {
        this.gateway = gateway;
    }
    
    @Column(name="MAC_ADDRESS", length=30)
    public String getMacAddress() {
        return this.macAddress;
    }
    
    public void setMacAddress(String macAddress) {
        this.macAddress = macAddress;
    }
    
    @Column(name="HOST_NAME", length=1000)
    public String getHostName() {
        return this.hostName;
    }
    
    public void setHostName(String hostName) {
        this.hostName = hostName;
    }
    
    @Column(name="SYSTEM_NAME", length=1000)
    public String getSystemName() {
        return this.systemName;
    }
    
    public void setSystemName(String systemName) {
        this.systemName = systemName;
    }
    
    @Column(name="NETWORK_TYPE_ID")
    public String getNetworkTypeId() {
        return this.networkTypeId;
    }
    
    public void setNetworkTypeId(String networkTypeId) {
        this.networkTypeId = networkTypeId;
    }
    
    @Column(name="NETWORK_TYPE_NAME", length=1000)
    public String getNetworkTypeName() {
        return this.networkTypeName;
    }
    
    public void setNetworkTypeName(String networkTypeName) {
        this.networkTypeName = networkTypeName;
    }
    

    @Column(name="T2_TEAM_NAME", length=1000)
    public String getT2TeamName() {
		return t2TeamName;
	}
	public void setT2TeamName(String t2TeamName) {
		this.t2TeamName = t2TeamName;
	}
    @Column(name="UR_REFER", length=20)
    public String getUrRefer() {
        return this.urRefer;
    }
    
    public void setUrRefer(String urRefer) {
        this.urRefer = urRefer;
    }
    
    @Column(name="PROJECT_ID", length=30)
    public String getProjectId() {
        return this.projectId;
    }
    
    public void setProjectId(String projectId) {
        this.projectId = projectId;
    }
    
    @Column(name="PROJECT_NAME", length=1000)
    public String getProjectName() {
        return this.projectName;
    }
    
    public void setProjectName(String projectName) {
        this.projectName = projectName;
    }
    
    @Column(name="PROJECT_MANAGER", length=1000)
    public String getProjectManager() {
        return this.projectManager;
    }
    
    public void setProjectManager(String projectManager) {
        this.projectManager = projectManager;
    }
    @Temporal(TemporalType.DATE)
    @Column(name="EFFECTIVE_DATE", length=7)
    public Date getEffectiveDate() {
        return this.effectiveDate;
    }
    
    public void setEffectiveDate(Date effectiveDate) {
        this.effectiveDate = effectiveDate;
    }
    @Temporal(TemporalType.DATE)
    @Column(name="EXPIRED_DATE", length=7)
    public Date getExpiredDate() {
        return this.expiredDate;
    }
    
    public void setExpiredDate(Date expiredDate) {
        this.expiredDate = expiredDate;
    }
    
    @ManyToOne(optional = false, fetch = FetchType.EAGER)
    @JoinColumn(name = "LEVEL2_ID", referencedColumnName = "LEVEL2_ID", nullable = true, insertable=false,updatable=false)
    public IpLevel2 getIpLevel2() {
		return ipLevel2;
	}
	public void setIpLevel2(IpLevel2 ipLevel2) {
		this.ipLevel2 = ipLevel2;
	}
	@ManyToOne(optional = false, fetch = FetchType.EAGER)
    @JoinColumn(name = "SYSTEM_OWNER_ID", referencedColumnName = "USER_ID", nullable = false, insertable=false,updatable=false)
	public IpUser getSystemOwnerId() {
        return this.systemOwnerId;
    }
    
    public void setSystemOwnerId(IpUser systemOwnerId) {
        this.systemOwnerId = systemOwnerId;
    }
    
    @Column(name="SYSTEM_OWNER_ID", length=10)
    public String getSystemOwner() {
		return systemOwner;
	}
	public void setSystemOwner(String systemOwner) {
		this.systemOwner = systemOwner;
	}
	@Column(name="SYSTEM_OWNER_NAME", length=1000)
    public String getSystemOwnerName() {
        return this.systemOwnerName;
    }
    
    public void setSystemOwnerName(String systemOwnerName) {
        this.systemOwnerName = systemOwnerName;
    }
    
    @Column(name="SYSTEM_OWNER_TEAM_ID", length=10)
    public String getSystemOwnerTeamId() {
        return this.systemOwnerTeamId;
    }
    
    public void setSystemOwnerTeamId(String systemOwnerTeamId) {
        this.systemOwnerTeamId = systemOwnerTeamId;
    }
    
    @Column(name="SYSTEM_OWNER_TEAM_NAME", length=1000)
    public String getSystemOwnerTeamName() {
        return this.systemOwnerTeamName;
    }
    
    public void setSystemOwnerTeamName(String systemOwnerTeamName) {
        this.systemOwnerTeamName = systemOwnerTeamName;
    }
    
    @Column(name="VLAN_ID", length=30)
    public String getVlanId() {
        return this.vlanId;
    }
    
    public void setVlanId(String vlanId) {
        this.vlanId = vlanId;
    }
    
    @Column(name="DNS_NAME", length=30)
    public String getDnsName() {
        return this.dnsName;
    }
    
    public void setDnsName(String dnsName) {
        this.dnsName = dnsName;
    }
    
    @Column(name="T1_TEAM_ID", length=10)
    public String getT1TeamId() {
        return this.t1TeamId;
    }
    
    public void setT1TeamId(String t1TeamId) {
        this.t1TeamId = t1TeamId;
    }
    
    @Column(name="T1_TEAM_NAME")
    public String getT1TeamName() {
        return this.t1TeamName;
    }
    
    public void setT1TeamName(String t1TeamName) {
        this.t1TeamName = t1TeamName;
    }
    
    @Column(name="T2_TEAM_ID", length=10)
    public String getT2TeamId() {
        return this.t2TeamId;
    }
    
    public void setT2TeamId(String t2TeamId) {
        this.t2TeamId = t2TeamId;
    }
    
    @Column(name="T1_REMARK", length=1000)
    public String getT1Remark() {
        return this.t1Remark;
    }
    
    public void setT1Remark(String t1Remark) {
        this.t1Remark = t1Remark;
    }
    
    @Column(name="T2_REMARK", length=1000)
    public String getT2Remark() {
        return this.t2Remark;
    }
    
    public void setT2Remark(String t2Remark) {
        this.t2Remark = t2Remark;
    }
    
    @Column(name="T3_REMARK", length=1000)
    public String getT3Remark() {
        return this.t3Remark;
    }
    
    public void setT3Remark(String t3Remark) {
        this.t3Remark = t3Remark;
    }
    
    @Column(name="WY_NODE_NAME", length=1000)
    public String getWyNodeName() {
		return wyNodeName;
	}
    
	public void setWyNodeName(String wyNodeName) {
		this.wyNodeName = wyNodeName;
	}
	
	@Column(name="CREATE_BY")
    public String getCreatedBy() {
 		return createdBy;
 	}

 	public void setCreatedBy(String createdBy) {
 		this.createdBy = createdBy;
 	}

 	@Column(name="CREATE_DATE")
 	public Date getCreated() {
 		return created;
 	}

 	public void setCreated(Date created) {
 		this.created = created;
 	}

 	@Column(name="UPDATE_BY")
 	public String getLastUpdBy() {
 		return lastUpdBy;
 	}

 	public void setLastUpdBy(String lastUpdBy) {
 		this.lastUpdBy = lastUpdBy;
 	}
 	
 	@Column(name="UPDATE_DATE")
 	public Date getLastUpd() {
 		return lastUpd;
 	}
 	
 	public void setLastUpd(Date lastUpd) {
 		this.lastUpd = lastUpd;
 	}
 	
 	@Id 
	@GeneratedValue(generator="system-uuid")
	@GenericGenerator(name="system-uuid", strategy = "uuid")
    @Column(name="ROW_ID", unique=true, length=50)
    public String getRowId() {
        return this.rowId;
    }
    
    public void setRowId(String rowId) {
        this.rowId = rowId;
    }
    
    @Transient
	public boolean isRowCheck() {
		return rowCheck;
	}
	public void setRowCheck(boolean rowCheck) {
		this.rowCheck = rowCheck;
	}
	
	@Transient
	public boolean isButtonCheck() {
		return buttonCheck;
	}
	public void setButtonCheck(boolean buttonCheck) {
		this.buttonCheck = buttonCheck;
	}
	
	@Transient
    public IpMasterTable getStatus() {
		return status;
	}
	public void setStatus(IpMasterTable status) {
		this.status = status;
	}
	
	@Transient
	public String getStIp1() {
		return stIp1;
	}
	public void setStIp1(String stIp1) {
		this.stIp1 = stIp1;
	}
	@Transient
	public String getStIp2() {
		return stIp2;
	}
	public void setStIp2(String stIp2) {
		this.stIp2 = stIp2;
	}
	@Transient
	public String getStIp3() {
		return stIp3;
	}
	public void setStIp3(String stIp3) {
		this.stIp3 = stIp3;
	}
	@Transient
	public String getStIp4() {
		return stIp4;
	}
	public void setStIp4(String stIp4) {
		this.stIp4 = stIp4;
	}
	@Transient
	public String getUserPermission() {
		return userPermission;
	}
	public void setUserPermission(String userPermission) {
		this.userPermission = userPermission;
	}
	@Transient
	public String getBinaryIpStart() {
		return binaryIpStart;
	}
	public void setBinaryIpStart(String binaryIpStart) {
		this.binaryIpStart = binaryIpStart;
	}
	@Transient
	public String getBinaryIpEnd() {
		return binaryIpEnd;
	}
	public void setBinaryIpEnd(String binaryIpEnd) {
		this.binaryIpEnd = binaryIpEnd;
	}
	@Transient
	public String getV_bin_start() {
		return v_bin_start;
	}
	public void setV_bin_start(String vBinStart) {
		v_bin_start = vBinStart;
	}
	
	@JoinColumn(name = "T2_TEAM_ID", referencedColumnName = "TEAM_ID", nullable = false ,insertable=false,updatable=false)
	@ManyToOne(optional = false, fetch = FetchType.EAGER)
	public IpTeam getT2Team() {
		return t2Team;
	}
	public void setT2Team(IpTeam t2Team) {
		this.t2Team = t2Team;
	}
	
	@Transient
	public boolean getSubnetStyleClass(){
		if(subNet==null) return true;
		if(subNet.intValue()%2==0) return false;
		return true;
	}
	
	@Transient
	public Integer getSubNet() {
		return subNet;
	}

	public void setSubNet(Integer subNet) {
		this.subNet = subNet;
	}
	@Transient
	public Integer getTotalIP() {
		return totalIP;
	}

	public void setTotalIP(Integer totalIP) {
		this.totalIP = totalIP;
	}
	@Transient
	public Integer getAvailableIP() {
		return availableIP;
	}

	public void setAvailableIP(Integer availableIP) {
		this.availableIP = availableIP;
	}
	@Transient
	public String getResult() {
		return result;
	}

	public void setResult(String result) {
		this.result = result;
	}
	@Transient
	public String getIpStatusName() {
		String statusName="";
		if (ipStatus!=null && ipStatus.trim().length()>0) {
			if (ipStatus.equalsIgnoreCase("A")) {
				statusName = "Assign to User";
			}else if (ipStatus.equalsIgnoreCase("N")) {
				statusName = "Available";
			}else if (ipStatus.equalsIgnoreCase("P")) {
				statusName = "Assign To Planning";
			}else if (ipStatus.equalsIgnoreCase("R")) {
				statusName = "Reserved";
			}else if (ipStatus.equalsIgnoreCase("T")) {
				statusName = "Terminate";
			}else if (ipStatus.equalsIgnoreCase("U")) {
				statusName = "Used";
			}
		}
		return statusName;
	}
	
	@Transient
	public boolean isButtonDisable() {
		return buttonDisable;
	}

	public void setButtonDisable(boolean buttonDisable) {
		this.buttonDisable = buttonDisable;
	}

	@Override
    public Object clone() throws CloneNotSupportedException
    {
		IpInfoHistory another = (IpInfoHistory) super.clone();
		another.setIpLevel2((IpLevel2)getIpLevel2().clone());
		another.setSystemOwnerId((IpUser)getSystemOwnerId().clone());
        return another;
    }

}


