package th.co.ais.ipfm.domain1;
// Generated 27 �.�. 2553, 17:13:55 by Hibernate Tools 3.2.1.GA


import java.math.BigDecimal;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Transient;
import javax.persistence.UniqueConstraint;
import javax.persistence.Version;

import org.hibernate.annotations.GenericGenerator;

import th.co.ais.ipfm.domain.MasterDomain;

/**
 * IpInfo generated by hbm2java
 */
@Entity
@Table(name="IP_INFO_TEMP"
    , uniqueConstraints = @UniqueConstraint(columnNames="ROW_ID") 
)
public class IpInfoTemp extends MasterDomain implements java.io.Serializable,Cloneable {


     private String ipAddress;
//     private Long version;
//     private String ipVersion;
     private String ipSubmask;
//     private BigDecimal ipv4digit1;
//     private BigDecimal ipv4digit2;
//     private BigDecimal ipv4digit3;
//     private BigDecimal ipv4digit4;
//     private BigDecimal ipv6digit1;
//     private BigDecimal ipv6digit2;
//     private BigDecimal ipv6digit3;
//     private BigDecimal ipv6digit4;
//     private BigDecimal ipv6digit5;
//     private BigDecimal ipv6digit6;
//     private String level1Id;
//     private String level2Id;
//     private IpLevel2 ipLevel2;
//     private String binaryIp;
     private String ipStatus;
//     private IpMasterTable status;
//     private String companyId;
//     private String companyName;
//     private String locationId;
//     private String locationName;
//     private String ipTypeId;
//     private String ipTypeName;
//     private String vip;
//     private String installTypeId;
//     private String installTypeName;
//     private String networkZoneId;
//     private String networkZoneName;
//     private String submask;
//     private String networkIp;
     private String gateway;
//     private String macAddress;
     private String hostName;
     private String systemName;
//     private String networkTypeId;
//     private String networkTypeName;
//     private String t2TeamId;
//     private String t2TeamName;
//     private IpTeam t2Team;
//     private String urRefer;
//     private String projectId;
//     private String projectName;
//     private String projectManager;
//     private Date effectiveDate;
     private Date expiredDate;
//     private IpUser systemOwnerId;
//     private String systemOwner;
     private String systemOwnerName;
//     private String systemOwnerTeamId;
//     private String systemOwnerTeamName;
     private String vlanId;
//     private String dnsName;
//     private String t1TeamId;
//     private String t1TeamName;
//     private String t1Remark;
//     private String t2Remark;
//     private String t3Remark;
//     private String wyNodeName;
     private String rowId;
     private String templateType;
//     private boolean rowCheck;
//     private boolean buttonCheck = false;
//     private boolean buttonDisable = false;
//     private String stIp1;
//     private String stIp2;
//     private String stIp3;
//     private String stIp4;
//     private String userPermission;
//     private String binaryIpStart;
//     private String binaryIpEnd;
//     private String v_bin_start;
//     private Integer subNet;
//     private Integer totalIP;
//     private Integer availableIP;
//     private String result;
     
//     private String ipStatusOld;
    private String natIp; 
     
    public IpInfoTemp() {
    }
    
    public IpInfoTemp(String ipAddress) {
        this.ipAddress = ipAddress;
    }
    
	@Column(name="IP_ADDRESS", unique=true, nullable=false, length=21)
    public String getIpAddress() {
        return this.ipAddress;
    }
    
    public void setIpAddress(String ipAddress) {
        this.ipAddress = ipAddress;
    }
    
    @Column(name="IP_SUBMASK", length=5)
    public String getIpSubmask() {
        return this.ipSubmask;
    }
    
    public void setIpSubmask(String ipSubmask) {
        this.ipSubmask = ipSubmask;
    }

    @Column(name="IP_STATUS", length=50)
    public String getIpStatus() {
        return this.ipStatus;
    }
    
    public void setIpStatus(String ipStatus) {
        this.ipStatus = ipStatus;
    }
    
    @Column(name="GATEWAY", length=30)
    public String getGateway() {
        return this.gateway;
    }
    
    public void setGateway(String gateway) {
        this.gateway = gateway;
    }
    
    @Column(name="HOST_NAME", length=1000)
    public String getHostName() {
        return this.hostName;
    }
    
    public void setHostName(String hostName) {
        this.hostName = hostName;
    }
    
    @Column(name="SYSTEM_NAME", length=1000)
    public String getSystemName() {
        return this.systemName;
    }
    
    public void setSystemName(String systemName) {
        this.systemName = systemName;
    }
    
    @Temporal(TemporalType.DATE)
    @Column(name="EXPIRED_DATE", length=7)
    public Date getExpiredDate() {
        return this.expiredDate;
    }
    
    public void setExpiredDate(Date expiredDate) {
        this.expiredDate = expiredDate;
    }
    
	@Column(name="SYSTEM_OWNER_NAME", length=1000)
    public String getSystemOwnerName() {
        return this.systemOwnerName;
    }
    
    public void setSystemOwnerName(String systemOwnerName) {
        this.systemOwnerName = systemOwnerName;
    }
    
	@Column(name="CREATE_BY")
    public String getCreatedBy() {
 		return createdBy;
 	}

 	public void setCreatedBy(String createdBy) {
 		this.createdBy = createdBy;
 	}

 	@Column(name="CREATE_DATE")
 	public Date getCreated() {
 		return created;
 	}

 	public void setCreated(Date created) {
 		this.created = created;
 	}

 	@Column(name="UPDATE_BY")
 	public String getLastUpdBy() {
 		return lastUpdBy;
 	}

 	public void setLastUpdBy(String lastUpdBy) {
 		this.lastUpdBy = lastUpdBy;
 	}
 	
 	@Column(name="UPDATE_DATE")
 	public Date getLastUpd() {
 		return lastUpd;
 	}
 	
 	public void setLastUpd(Date lastUpd) {
 		this.lastUpd = lastUpd;
 	}
 	
 	@Id 
	@GeneratedValue(generator="system-uuid")
	@GenericGenerator(name="system-uuid", strategy = "uuid")
    @Column(name="ROW_ID", unique=true, length=50)
    public String getRowId() {
        return this.rowId;
    }
    
    public void setRowId(String rowId) {
        this.rowId = rowId;
    }
    
    @Column(name="VLAN_ID", length=30)
    public String getVlanId() {
        return this.vlanId;
    }
    
    public void setVlanId(String vlanId) {
        this.vlanId = vlanId;
    }

    @Column(name="TEMPLATE_TYPE", length=10)
	public String getTemplateType() {
		return templateType;
	}

	public void setTemplateType(String templateType) {
		this.templateType = templateType;
	}
	
	@Column(name="NAT_IP", length=500)
	public String getNatIp() {
		return natIp;
	}

	public void setNatIp(String natIp) {
		this.natIp = natIp;
	}
    
    
}


