package th.co.ais.ipfm.domain1;


import java.math.BigDecimal;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Transient;
import javax.persistence.UniqueConstraint;
import javax.persistence.Version;


import th.co.ais.ipfm.domain.MasterDomain;

/**
* IpLevel1 generated by hbm2java
*/
@Entity
@Table(name="IP_LEVEL1"
 , uniqueConstraints = @UniqueConstraint(columnNames="ROW_ID") 
)
public class IpLevel1  extends MasterDomain implements java.io.Serializable ,Cloneable{


  private String level1Id;
  private Long version;
  private String ipVersion;
  private String level1Start;
  private String level1End;
  private String binary1Start;
  private String binary1End;
  private String ipStatus;
  private String companyId;
  private String companyName;
  private String ipTypeId;
  private String ipTypeName;
  private String t1TeamId;
  private String t2TeamId;
  private String t2TeamName;
  private IpTeam t2Team; 
  private String vip;
  private String networkIp;
  private String gateway;
  private String dnsName;
  private String vlanId;
  private Date effectiveDate;
  private Date expiredDate;
  private String t1Remarks;
  private BigDecimal totalIp;
  private BigDecimal totalT2Assign;
  private String rowId;
  private String networkTypeId;
  private String networkTypeName;
  private String networkZoneId;
  private String networkZoneName;
  private String t1TeamName;
  
  private String ipStatusOld;

 public IpLevel1() {
 }

	
 public IpLevel1(String level1Id) {
     this.level1Id = level1Id;
 }
 public IpLevel1(String level1Id, String ipVersion, String level1Start, String level1End, String binary1Start, String binary1End, String ipStatus, String companyId, String companyName, String ipTypeId, String ipTypeName, String t1TeamId, String t2TeamId, String vip, String networkIp, String gateway, String dnsName, String vlanId, Date effectiveDate, Date expiredDate, String t1Remarks, BigDecimal totalIp, BigDecimal totalT2Assign, String createBy, Date createDate, String updateBy, Date updateDate, String rowId, String networkTypeId, String networkTypeName, String networkZoneId, String networkZoneName) {
    this.level1Id = level1Id;
    this.ipVersion = ipVersion;
    this.level1Start = level1Start;
    this.level1End = level1End;
    this.binary1Start = binary1Start;
    this.binary1End = binary1End;
    this.ipStatus = ipStatus;
    this.companyId = companyId;
    this.companyName = companyName;
    this.ipTypeId = ipTypeId;
    this.ipTypeName = ipTypeName;
    this.t1TeamId = t1TeamId;
    this.t2TeamId = t2TeamId;
    this.vip = vip;
    this.networkIp = networkIp;
    this.gateway = gateway;
    this.dnsName = dnsName;
    this.vlanId = vlanId;
    this.effectiveDate = effectiveDate;
    this.expiredDate = expiredDate;
    this.t1Remarks = t1Remarks;
    this.totalIp = totalIp;
    this.totalT2Assign = totalT2Assign;
    this.rowId = rowId;
    this.networkTypeId = networkTypeId;
    this.networkTypeName = networkTypeName;
    this.networkZoneId = networkZoneId;
    this.networkZoneName = networkZoneName;
 }

	 @Id 
	 @Column(name="LEVEL1_ID", unique=true, nullable=false, length=5)
	 public String getLevel1Id() {
	     return this.level1Id;
	 }
	 
	 public void setLevel1Id(String level1Id) {
	     this.level1Id = level1Id;
	 }
	 @Version
	 @Column(name="VERSION", precision=10, scale=0)
	 public Long getVersion() {
	     return this.version;
	 }
	 
	 public void setVersion(Long version) {
	     this.version = version;
	 }
	 
	 @Column(name="IP_VERSION", length=3)
	 public String getIpVersion() {
	     return this.ipVersion;
	 }
	 
	 public void setIpVersion(String ipVersion) {
	     this.ipVersion = ipVersion;
	 }
	 
	 @Column(name="LEVEL1_START", length=21)
	 public String getLevel1Start() {
	     return this.level1Start;
	 }
	 
	 public void setLevel1Start(String level1Start) {
	     this.level1Start = level1Start;
	 }
	 
	 @Column(name="LEVEL1_END", length=21)
	 public String getLevel1End() {
	     return this.level1End;
	 }
	 
	 public void setLevel1End(String level1End) {
	     this.level1End = level1End;
	 }
	 
	 @Column(name="BINARY1_START", length=40)
	 public String getBinary1Start() {
	     return this.binary1Start;
	 }
	 
	 public void setBinary1Start(String binary1Start) {
	     this.binary1Start = binary1Start;
	 }
	 
	 @Column(name="BINARY1_END", length=40)
	 public String getBinary1End() {
	     return this.binary1End;
	 }
	 
	 public void setBinary1End(String binary1End) {
	     this.binary1End = binary1End;
	 }
	 
	 @Column(name="IP_STATUS", length=2)
	 public String getIpStatus() {
	     return this.ipStatus;
	 }
	 
	 public void setIpStatus(String ipStatus) {
	     this.ipStatus = ipStatus;
	 }
	 
	 @Column(name="COMPANY_ID")
	 public String getCompanyId() {
	     return this.companyId;
	 }
	 
	 public void setCompanyId(String companyId) {
	     this.companyId = companyId;
	 }
	 
	 @Column(name="COMPANY_NAME", length=1000)
	 public String getCompanyName() {
	     return this.companyName;
	 }
	 
	 public void setCompanyName(String companyName) {
	     this.companyName = companyName;
	 }
	 
	 @Column(name="IP_TYPE_ID")
	 public String getIpTypeId() {
	     return this.ipTypeId;
	 }
	 
	 public void setIpTypeId(String ipTypeId) {
	     this.ipTypeId = ipTypeId;
	 }
	 
	 @Column(name="IP_TYPE_NAME", length=1000)
	 public String getIpTypeName() {
	     return this.ipTypeName;
	 }
	 
	 public void setIpTypeName(String ipTypeName) {
	     this.ipTypeName = ipTypeName;
	 }
	 
	 @Column(name="T1_TEAM_ID", length=10)
	 public String getT1TeamId() {
	     return this.t1TeamId;
	 }
	 
	 public void setT1TeamId(String t1TeamId) {
	     this.t1TeamId = t1TeamId;
	 }
	 
	 @Column(name="T2_TEAM_ID", length=10)
	 public String getT2TeamId() {
	     return this.t2TeamId;
	 }
	 
	 public void setT2TeamId(String t2TeamId) {
	     this.t2TeamId = t2TeamId;
	 }
	 
	 @Column(name="T2_TEAM_NAME")
	 public String getT2TeamName() {
		return t2TeamName;
	}

	public void setT2TeamName(String t2TeamName) {
		this.t2TeamName = t2TeamName;
	}


	@Column(name="VIP", length=1)
	 public String getVip() {
	     return this.vip;
	 }
	 
	 public void setVip(String vip) {
	     this.vip = vip;
	 }
	 
	 @Column(name="NETWORK_IP", length=30)
	 public String getNetworkIp() {
	     return this.networkIp;
	 }
	 
	 public void setNetworkIp(String networkIp) {
	     this.networkIp = networkIp;
	 }
	 
	 @Column(name="GATEWAY", length=30)
	 public String getGateway() {
	     return this.gateway;
	 }
	 
	 public void setGateway(String gateway) {
	     this.gateway = gateway;
	 }
	 
	 @Column(name="DNS_NAME", length=30)
	 public String getDnsName() {
	     return this.dnsName;
	 }
	 
	 public void setDnsName(String dnsName) {
	     this.dnsName = dnsName;
	 }
	 
	 @Column(name="VLAN_ID", length=30)
	 public String getVlanId() {
	     return this.vlanId;
	 }
	 
	 public void setVlanId(String vlanId) {
	     this.vlanId = vlanId;
	 }
	 @Temporal(TemporalType.DATE)
	 @Column(name="EFFECTIVE_DATE", length=7)
	 public Date getEffectiveDate() {
	     return this.effectiveDate;
	 }
	 
	 public void setEffectiveDate(Date effectiveDate) {
	     this.effectiveDate = effectiveDate;
	 }
	 @Temporal(TemporalType.DATE)
	 @Column(name="EXPIRED_DATE", length=7)
	 public Date getExpiredDate() {
	     return this.expiredDate;
	 }
	 
	 public void setExpiredDate(Date expiredDate) {
	     this.expiredDate = expiredDate;
	 }
	 
	 @Column(name="T1_REMARKS", length=1000)
	 public String getT1Remarks() {
	     return this.t1Remarks;
	 }
	 
	 public void setT1Remarks(String t1Remarks) {
	     this.t1Remarks = t1Remarks;
	 }
	 
	 @Column(name="TOTAL_IP", precision=20, scale=0)
	 public BigDecimal getTotalIp() {
	     return this.totalIp;
	 }
	 
	 public void setTotalIp(BigDecimal totalIp) {
	     this.totalIp = totalIp;
	 }
	 
	 @Column(name="TOTAL_T2_ASSIGN", precision=20, scale=0)
	 public BigDecimal getTotalT2Assign() {
	     return this.totalT2Assign;
	 }
	 
	 public void setTotalT2Assign(BigDecimal totalT2Assign) {
	     this.totalT2Assign = totalT2Assign;
	 }
	 
	 @Column(name="ROW_ID", unique=true, length=50)
	 public String getRowId() {
	     return this.rowId;
	 }
	 
	 public void setRowId(String rowId) {
	     this.rowId = rowId;
	 }
	 
	 @Column(name="NETWORK_TYPE_ID")
	 public String getNetworkTypeId() {
	     return this.networkTypeId;
	 }
	 
	 public void setNetworkTypeId(String networkTypeId) {
	     this.networkTypeId = networkTypeId;
	 }
	 
	 @Column(name="NETWORK_TYPE_NAME", length=1000)
	 public String getNetworkTypeName() {
	     return this.networkTypeName;
	 }
	 
	 public void setNetworkTypeName(String networkTypeName) {
	     this.networkTypeName = networkTypeName;
	 }
	 
	 @Column(name="NETWORK_ZONE_ID")
	 public String getNetworkZoneId() {
	     return this.networkZoneId;
	 }
	 
	 public void setNetworkZoneId(String networkZoneId) {
	     this.networkZoneId = networkZoneId;
	 }
	 
	 @Column(name="NETWORK_ZONE_NAME", length=1000)
	 public String getNetworkZoneName() {
	     return this.networkZoneName;
	 }
	 
	 public void setNetworkZoneName(String networkZoneName) {
	     this.networkZoneName = networkZoneName;
	 }
 
   @Column(name="CREATE_BY")
   public String getCreatedBy() {
		return createdBy;
	}

	public void setCreatedBy(String createdBy) {
		this.createdBy = createdBy;
	}

	@Column(name="CREATE_DATE")
	public Date getCreated() {
		return created;
	}

	public void setCreated(Date created) {
		this.created = created;
	}

	@Column(name="UPDATE_BY")
	public String getLastUpdBy() {
		return lastUpdBy;
	}

	public void setLastUpdBy(String lastUpdBy) {
		this.lastUpdBy = lastUpdBy;
	}
	
	@Column(name="UPDATE_DATE")
	public Date getLastUpd() {
		return lastUpd;
	}
	
	public void setLastUpd(Date lastUpd) {
		this.lastUpd = lastUpd;
	}
	

	@Column(name="T1_TEAM_NAME")
	public String getT1TeamName() {
		return t1TeamName;
	}


	public void setT1TeamName(String t1TeamName) {
		this.t1TeamName = t1TeamName;
	}


	@Transient
	public String getIp1StartBinary(){
		String ip1Start = "";
		String ip[] = getLevel1Start().split("\\.");		
		ip1Start = Integer.toBinaryString(Integer.parseInt(ip[0]));
		for (int i = ip1Start.length() ; i<8 ; i++){
			ip1Start = "0"+ip1Start;
		}
		return ip1Start;
	}
	
	@Transient
	public String getIp2StartBinary(){
		String ip1Start = "";
		String ip[] = getLevel1Start().split("\\.");		
		ip1Start = Integer.toBinaryString(Integer.parseInt(ip[1]));
		for (int i = ip1Start.length() ; i<8 ; i++){
			ip1Start = "0"+ip1Start;
		}
		return ip1Start;
	}
	
	@Transient
	public String getIp3StartBinary(){
		String ip1Start = "";
		String ip[] = getLevel1Start().split("\\.");		
		ip1Start = Integer.toBinaryString(Integer.parseInt(ip[2]));
		for (int i = ip1Start.length() ; i<8 ; i++){
			ip1Start = "0"+ip1Start;
		}
		return ip1Start;
	}
	
	@Transient
	public String getIp4StartBinary(){
		String ip1Start = "";
		String ip[] = getLevel1Start().split("\\.");		
		ip1Start = Integer.toBinaryString(Integer.parseInt(ip[3]));
		for (int i = ip1Start.length() ; i<8 ; i++){
			ip1Start = "0"+ip1Start;
		}
		return ip1Start;
	}
	
	@Transient
	public String getIp1EndBinary(){
		String ip1Start = "";
		String ip[] = getLevel1End().split("\\.");		
		ip1Start = Integer.toBinaryString(Integer.parseInt(ip[0]));
		for (int i = ip1Start.length() ; i<8 ; i++){
			ip1Start = "0"+ip1Start;
		}
		return ip1Start;
	}
	
	@Transient
	public String getIp2EndBinary(){
		String ip1Start = "";
		String ip[] = getLevel1End().split("\\.");		
		ip1Start = Integer.toBinaryString(Integer.parseInt(ip[1]));
		for (int i = ip1Start.length() ; i<8 ; i++){
			ip1Start = "0"+ip1Start;
		}
		return ip1Start;
	}
	
	@Transient
	public String getIp3EndBinary(){
		String ip1Start = "";
		String ip[] = getLevel1End().split("\\.");		
		ip1Start = Integer.toBinaryString(Integer.parseInt(ip[2]));
		for (int i = ip1Start.length() ; i<8 ; i++){
			ip1Start = "0"+ip1Start;
		}
		return ip1Start;
	}
	
	@Transient
	public String getIp4EndBinary(){
		String ip1Start = "";
		String ip[] = getLevel1End().split("\\.");		
		ip1Start = Integer.toBinaryString(Integer.parseInt(ip[3]));
		for (int i = ip1Start.length() ; i<8 ; i++){
			ip1Start = "0"+ip1Start;
		}
		return ip1Start;
	}


	@JoinColumn(name = "T2_TEAM_ID", referencedColumnName = "TEAM_ID", nullable = false ,insertable=false,updatable=false)
	@ManyToOne(optional = false, fetch = FetchType.EAGER)
	public IpTeam getT2Team() {
		return t2Team;
	}


	public void setT2Team(IpTeam t2Team) {
		this.t2Team = t2Team;
	}

	@Transient
	public String getIpStatusOld() {
		return ipStatusOld;
	}


	public void setIpStatusOld(String ipStatusOld) {
		this.ipStatusOld = ipStatusOld;
	}


	@Override
    public Object clone() throws CloneNotSupportedException
    {
		IpLevel1 another = (IpLevel1) super.clone();
		another.setT2Team((IpTeam)getT2Team().clone());
        //? take care of any deep copies to be made here
        return another;
    }

	
	
}





