package th.co.ais.ipfm.domain1;


import java.math.BigDecimal;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Transient;
import javax.persistence.UniqueConstraint;
import javax.persistence.Version;


import th.co.ais.ipfm.domain.MasterDomain;

/**
* IpLevel1 generated by hbm2java
*/
@Entity
@Table(name="IP_LEVEL1"
 , uniqueConstraints = @UniqueConstraint(columnNames="ROW_ID") 
)
public class IpLevel1  extends MasterDomain implements java.io.Serializable ,Cloneable{


  private String level1Id;
  private Long version;
  private String ipVersion;
  private String level1Start;
  private String level1End;
  private String binary1Start;
  private String binary1End;
  private String ipStatus;
  private String companyId;
  private String companyName;
  private String ipTypeId;
  private String ipTypeName;
  private String t1TeamId;
  private String t2TeamId;
  private String t2TeamName;
  private IpTeam t2Team; 
  private String vip;
  private String networkIp;
  private String gateway;
  private String dnsName;
  private String vlanId;
  private Date effectiveDate;
  private Date expiredDate;
  private String t1Remarks;
  private BigDecimal totalIp;
  private BigDecimal totalT2Assign;
  private String rowId;
  private String networkTypeId;
  private String networkTypeName;
  private String networkZoneId;
  private String networkZoneName;
  private String t1TeamName;
  
  private String ipStatusOld;

 public IpLevel1() {
 }

	
 public IpLevel1(String level1Id) {
     this.level1Id = level1Id;
 }
 public IpLevel1(String level1Id, String ipVersion, String level1Start, String level1End, String binary1Start, String binary1End, String ipStatus, String companyId, String companyName, String ipTypeId, String ipTypeName, String t1TeamId, String t2TeamId, String vip, String networkIp, String gateway, String dnsName, String vlanId, Date effectiveDate, Date expiredDate, String t1Remarks, BigDecimal totalIp, BigDecimal totalT2Assign, String createBy, Date createDate, String updateBy, Date updateDate, String rowId, String networkTypeId, String networkTypeName, String networkZoneId, String networkZoneName) {
    this.level1Id = level1Id;
    this.ipVersion = ipVersion;
    this.level1Start = level1Start;
    this.level1End = level1End;
    this.binary1Start = binary1Start;
    this.binary1End = binary1End;
    this.ipStatus = ipStatus;
    this.companyId = companyId;
    this.companyName = companyName;
    this.ipTypeId = ipTypeId;
    this.ipTypeName = ipTypeName;
    this.t1TeamId = t1TeamId;
    this.t2TeamId = t2TeamId;
    this.vip = vip;
    this.networkIp = networkIp;
    this.gateway = gateway;
    this.dnsName = dnsName;
    this.vlanId = vlanId;
    this.effectiveDate = effectiveDate;
    this.expiredDate = expiredDate;
    this.t1Remarks = t1Remarks;
    this.totalIp = totalIp;
    this.totalT2Assign = totalT2Assign;
    this.rowId = rowId;
    this.networkTypeId = networkTypeId;
    this.networkTypeName = networkTypeName;
    this.networkZoneId = networkZoneId;
    this.networkZoneName = networkZoneName;
 }

	 @Id 
	 @Column(name="LEVEL1_ID", unique=true, nullable=false, length=5)
	 public String getLevel1Id() { // DMAP Comment : Dead Code Detected - The Following Method has no reference getLevel1Id
	     return this.level1Id;
	 }
	 
	 public void setLevel1Id(String level1Id) { // DMAP Comment : Dead Code Detected - The Following Method has no reference setLevel1Id
	     this.level1Id = level1Id;
	 }
	 @Version
	 @Column(name="VERSION", precision=10, scale=0)
	 public Long getVersion() { // DMAP Comment : Dead Code Detected - The Following Method has no reference getVersion
	     return this.version;
	 }
	 
	 public void setVersion(Long version) { // DMAP Comment : Dead Code Detected - The Following Method has no reference setVersion
	     this.version = version;
	 }
	 
	 @Column(name="IP_VERSION", length=3)
	 public String getIpVersion() { // DMAP Comment : Dead Code Detected - The Following Method has no reference getIpVersion
	     return this.ipVersion;
	 }
	 
	 public void setIpVersion(String ipVersion) { // DMAP Comment : Dead Code Detected - The Following Method has no reference setIpVersion
	     this.ipVersion = ipVersion;
	 }
	 
	 @Column(name="LEVEL1_START", length=21)
	 public String getLevel1Start() {
	     return this.level1Start;
	 }
	 
	 public void setLevel1Start(String level1Start) { // DMAP Comment : Dead Code Detected - The Following Method has no reference setLevel1Start
	     this.level1Start = level1Start;
	 }
	 
	 @Column(name="LEVEL1_END", length=21)
	 public String getLevel1End() {
	     return this.level1End;
	 }
	 
	 public void setLevel1End(String level1End) { // DMAP Comment : Dead Code Detected - The Following Method has no reference setLevel1End
	     this.level1End = level1End;
	 }
	 
	 @Column(name="BINARY1_START", length=40)
	 public String getBinary1Start() { // DMAP Comment : Dead Code Detected - The Following Method has no reference getBinary1Start
	     return this.binary1Start;
	 }
	 
	 public void setBinary1Start(String binary1Start) { // DMAP Comment : Dead Code Detected - The Following Method has no reference setBinary1Start
	     this.binary1Start = binary1Start;
	 }
	 
	 @Column(name="BINARY1_END", length=40)
	 public String getBinary1End() { // DMAP Comment : Dead Code Detected - The Following Method has no reference getBinary1End
	     return this.binary1End;
	 }
	 
	 public void setBinary1End(String binary1End) { // DMAP Comment : Dead Code Detected - The Following Method has no reference setBinary1End
	     this.binary1End = binary1End;
	 }
	 
	 @Column(name="IP_STATUS", length=2)
	 public String getIpStatus() { // DMAP Comment : Dead Code Detected - The Following Method has no reference getIpStatus
	     return this.ipStatus;
	 }
	 
	 public void setIpStatus(String ipStatus) { // DMAP Comment : Dead Code Detected - The Following Method has no reference setIpStatus
	     this.ipStatus = ipStatus;
	 }
	 
	 @Column(name="COMPANY_ID")
	 public String getCompanyId() { // DMAP Comment : Dead Code Detected - The Following Method has no reference getCompanyId
	     return this.companyId;
	 }
	 
	 public void setCompanyId(String companyId) { // DMAP Comment : Dead Code Detected - The Following Method has no reference setCompanyId
	     this.companyId = companyId;
	 }
	 
	 @Column(name="COMPANY_NAME", length=1000)
	 public String getCompanyName() { // DMAP Comment : Dead Code Detected - The Following Method has no reference getCompanyName
	     return this.companyName;
	 }
	 
	 public void setCompanyName(String companyName) { // DMAP Comment : Dead Code Detected - The Following Method has no reference setCompanyName
	     this.companyName = companyName;
	 }
	 
	 @Column(name="IP_TYPE_ID")
	 public String getIpTypeId() { // DMAP Comment : Dead Code Detected - The Following Method has no reference getIpTypeId
	     return this.ipTypeId;
	 }
	 
	 public void setIpTypeId(String ipTypeId) { // DMAP Comment : Dead Code Detected - The Following Method has no reference setIpTypeId
	     this.ipTypeId = ipTypeId;
	 }
	 
	 @Column(name="IP_TYPE_NAME", length=1000)
	 public String getIpTypeName() { // DMAP Comment : Dead Code Detected - The Following Method has no reference getIpTypeName
	     return this.ipTypeName;
	 }
	 
	 public void setIpTypeName(String ipTypeName) { // DMAP Comment : Dead Code Detected - The Following Method has no reference setIpTypeName
	     this.ipTypeName = ipTypeName;
	 }
	 
	 @Column(name="T1_TEAM_ID", length=10)
	 public String getT1TeamId() { // DMAP Comment : Dead Code Detected - The Following Method has no reference getT1TeamId
	     return this.t1TeamId;
	 }
	 
	 public void setT1TeamId(String t1TeamId) { // DMAP Comment : Dead Code Detected - The Following Method has no reference setT1TeamId
	     this.t1TeamId = t1TeamId;
	 }
	 
	 @Column(name="T2_TEAM_ID", length=10)
	 public String getT2TeamId() { // DMAP Comment : Dead Code Detected - The Following Method has no reference getT2TeamId
	     return this.t2TeamId;
	 }
	 
	 public void setT2TeamId(String t2TeamId) { // DMAP Comment : Dead Code Detected - The Following Method has no reference setT2TeamId
	     this.t2TeamId = t2TeamId;
	 }
	 
	 @Column(name="T2_TEAM_NAME")
	 public String getT2TeamName() { // DMAP Comment : Dead Code Detected - The Following Method has no reference getT2TeamName
		return t2TeamName;
	}

	public void setT2TeamName(String t2TeamName) { // DMAP Comment : Dead Code Detected - The Following Method has no reference setT2TeamName
		this.t2TeamName = t2TeamName;
	}


	@Column(name="VIP", length=1)
	 public String getVip() { // DMAP Comment : Dead Code Detected - The Following Method has no reference getVip
	     return this.vip;
	 }
	 
	 public void setVip(String vip) { // DMAP Comment : Dead Code Detected - The Following Method has no reference setVip
	     this.vip = vip;
	 }
	 
	 @Column(name="NETWORK_IP", length=30)
	 public String getNetworkIp() { // DMAP Comment : Dead Code Detected - The Following Method has no reference getNetworkIp
	     return this.networkIp;
	 }
	 
	 public void setNetworkIp(String networkIp) { // DMAP Comment : Dead Code Detected - The Following Method has no reference setNetworkIp
	     this.networkIp = networkIp;
	 }
	 
	 @Column(name="GATEWAY", length=30)
	 public String getGateway() { // DMAP Comment : Dead Code Detected - The Following Method has no reference getGateway
	     return this.gateway;
	 }
	 
	 public void setGateway(String gateway) { // DMAP Comment : Dead Code Detected - The Following Method has no reference setGateway
	     this.gateway = gateway;
	 }
	 
	 @Column(name="DNS_NAME", length=30)
	 public String getDnsName() { // DMAP Comment : Dead Code Detected - The Following Method has no reference getDnsName
	     return this.dnsName;
	 }
	 
	 public void setDnsName(String dnsName) { // DMAP Comment : Dead Code Detected - The Following Method has no reference setDnsName
	     this.dnsName = dnsName;
	 }
	 
	 @Column(name="VLAN_ID", length=30)
	 public String getVlanId() { // DMAP Comment : Dead Code Detected - The Following Method has no reference getVlanId
	     return this.vlanId;
	 }
	 
	 public void setVlanId(String vlanId) { // DMAP Comment : Dead Code Detected - The Following Method has no reference setVlanId
	     this.vlanId = vlanId;
	 }
	 @Temporal(TemporalType.DATE)
	 @Column(name="EFFECTIVE_DATE", length=7)
	 public Date getEffectiveDate() { // DMAP Comment : Dead Code Detected - The Following Method has no reference getEffectiveDate
	     return this.effectiveDate;
	 }
	 
	 public void setEffectiveDate(Date effectiveDate) { // DMAP Comment : Dead Code Detected - The Following Method has no reference setEffectiveDate
	     this.effectiveDate = effectiveDate;
	 }
	 @Temporal(TemporalType.DATE)
	 @Column(name="EXPIRED_DATE", length=7)
	 public Date getExpiredDate() { // DMAP Comment : Dead Code Detected - The Following Method has no reference getExpiredDate
	     return this.expiredDate;
	 }
	 
	 public void setExpiredDate(Date expiredDate) { // DMAP Comment : Dead Code Detected - The Following Method has no reference setExpiredDate
	     this.expiredDate = expiredDate;
	 }
	 
	 @Column(name="T1_REMARKS", length=1000)
	 public String getT1Remarks() { // DMAP Comment : Dead Code Detected - The Following Method has no reference getT1Remarks
	     return this.t1Remarks;
	 }
	 
	 public void setT1Remarks(String t1Remarks) { // DMAP Comment : Dead Code Detected - The Following Method has no reference setT1Remarks
	     this.t1Remarks = t1Remarks;
	 }
	 
	 @Column(name="TOTAL_IP", precision=20, scale=0)
	 public BigDecimal getTotalIp() { // DMAP Comment : Dead Code Detected - The Following Method has no reference getTotalIp
	     return this.totalIp;
	 }
	 
	 public void setTotalIp(BigDecimal totalIp) { // DMAP Comment : Dead Code Detected - The Following Method has no reference setTotalIp
	     this.totalIp = totalIp;
	 }
	 
	 @Column(name="TOTAL_T2_ASSIGN", precision=20, scale=0)
	 public BigDecimal getTotalT2Assign() { // DMAP Comment : Dead Code Detected - The Following Method has no reference getTotalT2Assign
	     return this.totalT2Assign;
	 }
	 
	 public void setTotalT2Assign(BigDecimal totalT2Assign) { // DMAP Comment : Dead Code Detected - The Following Method has no reference setTotalT2Assign
	     this.totalT2Assign = totalT2Assign;
	 }
	 
	 @Column(name="ROW_ID", unique=true, length=50)
	 public String getRowId() { // DMAP Comment : Dead Code Detected - The Following Method has no reference getRowId
	     return this.rowId;
	 }
	 
	 public void setRowId(String rowId) { // DMAP Comment : Dead Code Detected - The Following Method has no reference setRowId
	     this.rowId = rowId;
	 }
	 
	 @Column(name="NETWORK_TYPE_ID")
	 public String getNetworkTypeId() { // DMAP Comment : Dead Code Detected - The Following Method has no reference getNetworkTypeId
	     return this.networkTypeId;
	 }
	 
	 public void setNetworkTypeId(String networkTypeId) { // DMAP Comment : Dead Code Detected - The Following Method has no reference setNetworkTypeId
	     this.networkTypeId = networkTypeId;
	 }
	 
	 @Column(name="NETWORK_TYPE_NAME", length=1000)
	 public String getNetworkTypeName() { // DMAP Comment : Dead Code Detected - The Following Method has no reference getNetworkTypeName
	     return this.networkTypeName;
	 }
	 
	 public void setNetworkTypeName(String networkTypeName) { // DMAP Comment : Dead Code Detected - The Following Method has no reference setNetworkTypeName
	     this.networkTypeName = networkTypeName;
	 }
	 
	 @Column(name="NETWORK_ZONE_ID")
	 public String getNetworkZoneId() { // DMAP Comment : Dead Code Detected - The Following Method has no reference getNetworkZoneId
	     return this.networkZoneId;
	 }
	 
	 public void setNetworkZoneId(String networkZoneId) { // DMAP Comment : Dead Code Detected - The Following Method has no reference setNetworkZoneId
	     this.networkZoneId = networkZoneId;
	 }
	 
	 @Column(name="NETWORK_ZONE_NAME", length=1000)
	 public String getNetworkZoneName() { // DMAP Comment : Dead Code Detected - The Following Method has no reference getNetworkZoneName
	     return this.networkZoneName;
	 }
	 
	 public void setNetworkZoneName(String networkZoneName) { // DMAP Comment : Dead Code Detected - The Following Method has no reference setNetworkZoneName
	     this.networkZoneName = networkZoneName;
	 }
 
   @Column(name="CREATE_BY")
   public String getCreatedBy() { // DMAP Comment : Dead Code Detected - The Following Method has no reference getCreatedBy
		return createdBy;
	}

	public void setCreatedBy(String createdBy) { // DMAP Comment : Dead Code Detected - The Following Method has no reference setCreatedBy
		this.createdBy = createdBy;
	}

	@Column(name="CREATE_DATE")
	public Date getCreated() { // DMAP Comment : Dead Code Detected - The Following Method has no reference getCreated
		return created;
	}

	public void setCreated(Date created) { // DMAP Comment : Dead Code Detected - The Following Method has no reference setCreated
		this.created = created;
	}

	@Column(name="UPDATE_BY")
	public String getLastUpdBy() { // DMAP Comment : Dead Code Detected - The Following Method has no reference getLastUpdBy
		return lastUpdBy;
	}

	public void setLastUpdBy(String lastUpdBy) { // DMAP Comment : Dead Code Detected - The Following Method has no reference setLastUpdBy
		this.lastUpdBy = lastUpdBy;
	}
	
	@Column(name="UPDATE_DATE")
	public Date getLastUpd() { // DMAP Comment : Dead Code Detected - The Following Method has no reference getLastUpd
		return lastUpd;
	}
	
	public void setLastUpd(Date lastUpd) { // DMAP Comment : Dead Code Detected - The Following Method has no reference setLastUpd
		this.lastUpd = lastUpd;
	}
	

	@Column(name="T1_TEAM_NAME")
	public String getT1TeamName() { // DMAP Comment : Dead Code Detected - The Following Method has no reference getT1TeamName
		return t1TeamName;
	}


	public void setT1TeamName(String t1TeamName) { // DMAP Comment : Dead Code Detected - The Following Method has no reference setT1TeamName
		this.t1TeamName = t1TeamName;
	}


	@Transient
	public String getIp1StartBinary(){ // DMAP Comment : Dead Code Detected - The Following Method has no reference getIp1StartBinary
		String ip1Start = "";
		String ip[] = getLevel1Start().split("\\.");		
		ip1Start = Integer.toBinaryString(Integer.parseInt(ip[0]));
		for (int i = ip1Start.length() ; i<8 ; i++){
			ip1Start = "0"+ip1Start;
		}
		return ip1Start;
	}
	
	@Transient
	public String getIp2StartBinary(){ // DMAP Comment : Dead Code Detected - The Following Method has no reference getIp2StartBinary
		String ip1Start = "";
		String ip[] = getLevel1Start().split("\\.");		
		ip1Start = Integer.toBinaryString(Integer.parseInt(ip[1]));
		for (int i = ip1Start.length() ; i<8 ; i++){
			ip1Start = "0"+ip1Start;
		}
		return ip1Start;
	}
	
	@Transient
	public String getIp3StartBinary(){ // DMAP Comment : Dead Code Detected - The Following Method has no reference getIp3StartBinary
		String ip1Start = "";
		String ip[] = getLevel1Start().split("\\.");		
		ip1Start = Integer.toBinaryString(Integer.parseInt(ip[2]));
		for (int i = ip1Start.length() ; i<8 ; i++){
			ip1Start = "0"+ip1Start;
		}
		return ip1Start;
	}
	
	@Transient
	public String getIp4StartBinary(){ // DMAP Comment : Dead Code Detected - The Following Method has no reference getIp4StartBinary
		String ip1Start = "";
		String ip[] = getLevel1Start().split("\\.");		
		ip1Start = Integer.toBinaryString(Integer.parseInt(ip[3]));
		for (int i = ip1Start.length() ; i<8 ; i++){
			ip1Start = "0"+ip1Start;
		}
		return ip1Start;
	}
	
	@Transient
	public String getIp1EndBinary(){ // DMAP Comment : Dead Code Detected - The Following Method has no reference getIp1EndBinary
		String ip1Start = "";
		String ip[] = getLevel1End().split("\\.");		
		ip1Start = Integer.toBinaryString(Integer.parseInt(ip[0]));
		for (int i = ip1Start.length() ; i<8 ; i++){
			ip1Start = "0"+ip1Start;
		}
		return ip1Start;
	}
	
	@Transient
	public String getIp2EndBinary(){ // DMAP Comment : Dead Code Detected - The Following Method has no reference getIp2EndBinary
		String ip1Start = "";
		String ip[] = getLevel1End().split("\\.");		
		ip1Start = Integer.toBinaryString(Integer.parseInt(ip[1]));
		for (int i = ip1Start.length() ; i<8 ; i++){
			ip1Start = "0"+ip1Start;
		}
		return ip1Start;
	}
	
	@Transient
	public String getIp3EndBinary(){ // DMAP Comment : Dead Code Detected - The Following Method has no reference getIp3EndBinary
		String ip1Start = "";
		String ip[] = getLevel1End().split("\\.");		
		ip1Start = Integer.toBinaryString(Integer.parseInt(ip[2]));
		for (int i = ip1Start.length() ; i<8 ; i++){
			ip1Start = "0"+ip1Start;
		}
		return ip1Start;
	}
	
	@Transient
	public String getIp4EndBinary(){ // DMAP Comment : Dead Code Detected - The Following Method has no reference getIp4EndBinary
		String ip1Start = "";
		String ip[] = getLevel1End().split("\\.");		
		ip1Start = Integer.toBinaryString(Integer.parseInt(ip[3]));
		for (int i = ip1Start.length() ; i<8 ; i++){
			ip1Start = "0"+ip1Start;
		}
		return ip1Start;
	}


	@JoinColumn(name = "T2_TEAM_ID", referencedColumnName = "TEAM_ID", nullable = false ,insertable=false,updatable=false)
	@ManyToOne(optional = false, fetch = FetchType.EAGER)
	public IpTeam getT2Team() {
		return t2Team;
	}


	public void setT2Team(IpTeam t2Team) {
		this.t2Team = t2Team;
	}

	@Transient
	public String getIpStatusOld() { // DMAP Comment : Dead Code Detected - The Following Method has no reference getIpStatusOld
		return ipStatusOld;
	}


	public void setIpStatusOld(String ipStatusOld) { // DMAP Comment : Dead Code Detected - The Following Method has no reference setIpStatusOld
		this.ipStatusOld = ipStatusOld;
	}


	@Override
    public Object clone() throws CloneNotSupportedException
    {
		IpLevel1 another = (IpLevel1) super.clone();
		another.setT2Team((IpTeam)getT2Team().clone());
        //? take care of any deep copies to be made here
        return another;
    }

	
	
}





