package th.co.ais.ipfm.domain1;
// Generated 27 �.�. 2553, 17:13:55 by Hibernate Tools 3.2.1.GA


import java.util.Date;

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;
import javax.persistence.Version;

import org.hibernate.annotations.GenericGenerator;

import th.co.ais.ipfm.domain.MasterDomain;

/**
 * IpMasterTable generated by hbm2java
 */
@Entity
@Table(name="IP_MASTER_TABLE"
    , uniqueConstraints = @UniqueConstraint(columnNames="ROW_ID") 
)
public class IpMasterTable  extends MasterDomain  implements java.io.Serializable {


     private IpMasterTableId id;
     private Long version;
     private String shortDesc;
     private String refDesc;
     private String refType;
     private String tcp;
     private String udp;
     private String other;
     private Date holidayDate;
     private String activeStatus;
     private Integer orderData; 
     private String rowId;
     

    public IpMasterTable() {
    }

	
    public IpMasterTable(IpMasterTableId id) {
        this.id = id;
    }
    public IpMasterTable(IpMasterTableId id, String shortDesc, String refDesc, String refType, String tcp, String udp, String other, Date holidayDate, String activeStatus, String createBy, Date createDate, String updateBy, Date updateDate, String rowId) {
       this.id = id;
       this.shortDesc = shortDesc;
       this.refDesc = refDesc;
       this.refType = refType;
       this.tcp = tcp;
       this.udp = udp;
       this.other = other;
       this.holidayDate = holidayDate;
       this.activeStatus = activeStatus;
       this.rowId = rowId;
    }
   
     @EmbeddedId
    
    @AttributeOverrides( {
        @AttributeOverride(name="refTable", column=@Column(name="REF_TABLE", nullable=false, length=10) ), 
        @AttributeOverride(name="refKey", column=@Column(name="REF_KEY", nullable=false, length=30) ) } )
    public IpMasterTableId getId() { // DMAP Comment : Dead Code Detected - The Following Method has no reference getId
        return this.id;
    }
    
    public void setId(IpMasterTableId id) { // DMAP Comment : Dead Code Detected - The Following Method has no reference setId
        this.id = id;
    }
    @Version
    @Column(name="VERSION", precision=10, scale=0)
    public Long getVersion() { // DMAP Comment : Dead Code Detected - The Following Method has no reference getVersion
        return this.version;
    }
    
    public void setVersion(Long version) { // DMAP Comment : Dead Code Detected - The Following Method has no reference setVersion
        this.version = version;
    }
    
    @Column(name="SHORT_DESC", length=400)
    public String getShortDesc() { // DMAP Comment : Dead Code Detected - The Following Method has no reference getShortDesc
        return this.shortDesc;
    }
    
    public void setShortDesc(String shortDesc) { // DMAP Comment : Dead Code Detected - The Following Method has no reference setShortDesc
        this.shortDesc = shortDesc;
    }
    
    @Column(name="REF_DESC", length=1000)
    public String getRefDesc() { // DMAP Comment : Dead Code Detected - The Following Method has no reference getRefDesc
        return this.refDesc;
    }
    
    public void setRefDesc(String refDesc) { // DMAP Comment : Dead Code Detected - The Following Method has no reference setRefDesc
        this.refDesc = refDesc;
    }
    
    @Column(name="REF_TYPE", length=2)
    public String getRefType() { // DMAP Comment : Dead Code Detected - The Following Method has no reference getRefType
        return this.refType;
    }
    
    public void setRefType(String refType) { // DMAP Comment : Dead Code Detected - The Following Method has no reference setRefType
        this.refType = refType;
    }
    
    @Column(name="TCP", length=100)
    public String getTcp() { // DMAP Comment : Dead Code Detected - The Following Method has no reference getTcp
        return this.tcp;
    }
    
    public void setTcp(String tcp) { // DMAP Comment : Dead Code Detected - The Following Method has no reference setTcp
        this.tcp = tcp;
    }
    
    @Column(name="UDP", length=100)
    public String getUdp() { // DMAP Comment : Dead Code Detected - The Following Method has no reference getUdp
        return this.udp;
    }
    
    public void setUdp(String udp) { // DMAP Comment : Dead Code Detected - The Following Method has no reference setUdp
        this.udp = udp;
    }
    
    @Column(name="OTHER", length=100)
    public String getOther() { // DMAP Comment : Dead Code Detected - The Following Method has no reference getOther
        return this.other;
    }
    
    public void setOther(String other) { // DMAP Comment : Dead Code Detected - The Following Method has no reference setOther
        this.other = other;
    }
    @Temporal(TemporalType.DATE)
    @Column(name="HOLIDAY_DATE", length=7)
    public Date getHolidayDate() { // DMAP Comment : Dead Code Detected - The Following Method has no reference getHolidayDate
        return this.holidayDate;
    }
    
    public void setHolidayDate(Date holidayDate) { // DMAP Comment : Dead Code Detected - The Following Method has no reference setHolidayDate
        this.holidayDate = holidayDate;
    }
    
    @Column(name="ACTIVE_STATUS", length=1)
    public String getActiveStatus() { // DMAP Comment : Dead Code Detected - The Following Method has no reference getActiveStatus
        return this.activeStatus;
    }
    
    public void setActiveStatus(String activeStatus) { // DMAP Comment : Dead Code Detected - The Following Method has no reference setActiveStatus
        this.activeStatus = activeStatus;
    }
    
	@Column(name="CREATE_BY")
	public String getCreatedBy() { // DMAP Comment : Dead Code Detected - The Following Method has no reference getCreatedBy
		return createdBy;
	}

	public void setCreatedBy(String createdBy) { // DMAP Comment : Dead Code Detected - The Following Method has no reference setCreatedBy
		this.createdBy = createdBy;
	}

	@Column(name="CREATE_DATE")
	public Date getCreated() { // DMAP Comment : Dead Code Detected - The Following Method has no reference getCreated
		return created;
	}

	public void setCreated(Date created) { // DMAP Comment : Dead Code Detected - The Following Method has no reference setCreated
		this.created = created;
	}

	@Column(name="UPDATE_BY")
	public String getLastUpdBy() { // DMAP Comment : Dead Code Detected - The Following Method has no reference getLastUpdBy
		return lastUpdBy;
	}

	public void setLastUpdBy(String lastUpdBy) { // DMAP Comment : Dead Code Detected - The Following Method has no reference setLastUpdBy
		this.lastUpdBy = lastUpdBy;
	}
	
	@Column(name="UPDATE_DATE")
	public Date getLastUpd() { // DMAP Comment : Dead Code Detected - The Following Method has no reference getLastUpd
		return lastUpd;
	}
	
	public void setLastUpd(Date lastUpd) { // DMAP Comment : Dead Code Detected - The Following Method has no reference setLastUpd
		this.lastUpd = lastUpd;
	}

    @Column(name="ROW_ID", unique=true, length=50)
    public String getRowId() { // DMAP Comment : Dead Code Detected - The Following Method has no reference getRowId
        return this.rowId;
    }
    
    public void setRowId(String rowId) { // DMAP Comment : Dead Code Detected - The Following Method has no reference setRowId
        this.rowId = rowId;
    }

    @Column(name="ORDER_DATA")
    public Integer getOrderData() { // DMAP Comment : Dead Code Detected - The Following Method has no reference getOrderData
        return this.orderData;
    }
    
    public void setOrderData(Integer orderData) { // DMAP Comment : Dead Code Detected - The Following Method has no reference setOrderData
        this.orderData = orderData;
    }


}


