package th.co.ais.ipfm.domain1;
// Generated 27 �.�. 2553, 17:13:55 by Hibernate Tools 3.2.1.GA


import java.util.Date;

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;
import javax.persistence.Version;

import org.hibernate.annotations.GenericGenerator;

import th.co.ais.ipfm.domain.MasterDomain;

/**
 * IpMasterTable generated by hbm2java
 */
@Entity
@Table(name="IP_MASTER_TABLE"
    , uniqueConstraints = @UniqueConstraint(columnNames="ROW_ID") 
)
public class IpMasterTable  extends MasterDomain  implements java.io.Serializable {


     private IpMasterTableId id;
     private Long version;
     private String shortDesc;
     private String refDesc;
     private String refType;
     private String tcp;
     private String udp;
     private String other;
     private Date holidayDate;
     private String activeStatus;
     private Integer orderData; 
     private String rowId;
     

    public IpMasterTable() {
    }

	
    public IpMasterTable(IpMasterTableId id) {
        this.id = id;
    }
    public IpMasterTable(IpMasterTableId id, String shortDesc, String refDesc, String refType, String tcp, String udp, String other, Date holidayDate, String activeStatus, String createBy, Date createDate, String updateBy, Date updateDate, String rowId) {
       this.id = id;
       this.shortDesc = shortDesc;
       this.refDesc = refDesc;
       this.refType = refType;
       this.tcp = tcp;
       this.udp = udp;
       this.other = other;
       this.holidayDate = holidayDate;
       this.activeStatus = activeStatus;
       this.rowId = rowId;
    }
   
     @EmbeddedId
    
    @AttributeOverrides( {
        @AttributeOverride(name="refTable", column=@Column(name="REF_TABLE", nullable=false, length=10) ), 
        @AttributeOverride(name="refKey", column=@Column(name="REF_KEY", nullable=false, length=30) ) } )
    public IpMasterTableId getId() {
        return this.id;
    }
    
    public void setId(IpMasterTableId id) {
        this.id = id;
    }
    @Version
    @Column(name="VERSION", precision=10, scale=0)
    public Long getVersion() {
        return this.version;
    }
    
    public void setVersion(Long version) {
        this.version = version;
    }
    
    @Column(name="SHORT_DESC", length=400)
    public String getShortDesc() {
        return this.shortDesc;
    }
    
    public void setShortDesc(String shortDesc) {
        this.shortDesc = shortDesc;
    }
    
    @Column(name="REF_DESC", length=1000)
    public String getRefDesc() {
        return this.refDesc;
    }
    
    public void setRefDesc(String refDesc) {
        this.refDesc = refDesc;
    }
    
    @Column(name="REF_TYPE", length=2)
    public String getRefType() {
        return this.refType;
    }
    
    public void setRefType(String refType) {
        this.refType = refType;
    }
    
    @Column(name="TCP", length=100)
    public String getTcp() {
        return this.tcp;
    }
    
    public void setTcp(String tcp) {
        this.tcp = tcp;
    }
    
    @Column(name="UDP", length=100)
    public String getUdp() {
        return this.udp;
    }
    
    public void setUdp(String udp) {
        this.udp = udp;
    }
    
    @Column(name="OTHER", length=100)
    public String getOther() {
        return this.other;
    }
    
    public void setOther(String other) {
        this.other = other;
    }
    @Temporal(TemporalType.DATE)
    @Column(name="HOLIDAY_DATE", length=7)
    public Date getHolidayDate() {
        return this.holidayDate;
    }
    
    public void setHolidayDate(Date holidayDate) {
        this.holidayDate = holidayDate;
    }
    
    @Column(name="ACTIVE_STATUS", length=1)
    public String getActiveStatus() {
        return this.activeStatus;
    }
    
    public void setActiveStatus(String activeStatus) {
        this.activeStatus = activeStatus;
    }
    
	@Column(name="CREATE_BY")
	public String getCreatedBy() {
		return createdBy;
	}

	public void setCreatedBy(String createdBy) {
		this.createdBy = createdBy;
	}

	@Column(name="CREATE_DATE")
	public Date getCreated() {
		return created;
	}

	public void setCreated(Date created) {
		this.created = created;
	}

	@Column(name="UPDATE_BY")
	public String getLastUpdBy() {
		return lastUpdBy;
	}

	public void setLastUpdBy(String lastUpdBy) {
		this.lastUpdBy = lastUpdBy;
	}
	
	@Column(name="UPDATE_DATE")
	public Date getLastUpd() {
		return lastUpd;
	}
	
	public void setLastUpd(Date lastUpd) {
		this.lastUpd = lastUpd;
	}

    @Column(name="ROW_ID", unique=true, length=50)
    public String getRowId() {
        return this.rowId;
    }
    
    public void setRowId(String rowId) {
        this.rowId = rowId;
    }

    @Column(name="ORDER_DATA")
    public Integer getOrderData() {
        return this.orderData;
    }
    
    public void setOrderData(Integer orderData) {
        this.orderData = orderData;
    }


}


