package th.co.ais.ipfm.domain1;
// Generated 27 Ê.¤. 2553, 17:13:55 by Hibernate Tools 3.2.1.GA


import java.util.Date;
import java.util.List;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;
import javax.persistence.Version;

import th.co.ais.ipfm.domain.MasterDomain;

/**
 * IpRoleFunction generated by hbm2java
 */
@Entity
@Table(name="IP_ROLE_FUNCTION"
    , uniqueConstraints = @UniqueConstraint(columnNames="ROW_ID") 
)
public class IpRoleFunction extends MasterDomain implements java.io.Serializable {
     /**
	 * 
	 */
	private static final long serialVersionUID = 1L;
//	private IpRoleFunctionId id = new IpRoleFunctionId();
	private String roleId;
    private String funcId;
	private Integer version;
	private String rowId;	

	private List<IpRoleMember> memberCollection;
	private IpFunction ipFunction;
	private IpRole ipRole;
	
	@JoinColumn(name = "FUNC_ID", referencedColumnName = "FUNC_ID", nullable = false ,insertable=false, updatable=false)
	@ManyToOne(optional = false, fetch = FetchType.LAZY)
    public IpFunction getIpFunction() {
		return ipFunction;
	}
	public void setIpFunction(IpFunction ipFunction) {
		this.ipFunction = ipFunction;
	}
	
	@JoinColumn(name = "ROLE_ID", referencedColumnName = "ROLE_ID", nullable = false ,insertable=false, updatable=false)
	@ManyToOne(optional = false, fetch = FetchType.LAZY)
    public IpRole getIpRole() {
		return ipRole;
	}
	public void setIpRole(IpRole ipRole) {
		this.ipRole = ipRole;
	}
	
	@OneToMany(cascade = CascadeType.ALL, mappedBy = "roleId", fetch = FetchType.LAZY)			
	public List<IpRoleMember> getMemberCollection() {
		return memberCollection;
	}
	public void setMemberCollection(List<IpRoleMember> memberCollection) {
		this.memberCollection = memberCollection;
	}
	public IpRoleFunction() {}

	@Column(name="ROLE_ID", nullable=false, length=10)
	public String getRoleId() {
        return this.roleId;
    }
    
    public void setRoleId(String roleId) {
        this.roleId = roleId;
    }
    @Column(name="FUNC_ID", nullable=false, length=10)
    public String getFuncId() {
        return this.funcId;
    }
    
    public void setFuncId(String funcId) {
        this.funcId = funcId;
    }
	
    @Version
    @Column(name="VERSION", precision=10, scale=0)
    public Integer getVersion() {
        return this.version;
    }
	
	public void setVersion(Integer version) {
        this.version = version;
    }
    @Column(name="CREATE_BY")
	public String getCreatedBy() {
		return createdBy;
	}

	public void setCreatedBy(String createdBy) {
		this.createdBy = createdBy;
	}

	@Column(name="CREATE_DATE")
	public Date getCreated() {
		return created;
	}

	public void setCreated(Date created) {
		this.created = created;
	}

	@Column(name="UPDATE_BY")
	public String getLastUpdBy() {
		return lastUpdBy;
	}

	public void setLastUpdBy(String lastUpdBy) {
		this.lastUpdBy = lastUpdBy;
	}
	
	@Column(name="UPDATE_DATE")
	public Date getLastUpd() {
		return lastUpd;
	}
	
	public void setLastUpd(Date lastUpd) {
		this.lastUpd = lastUpd;
	}
    
    @Id
    @Column(name="ROW_ID", unique=true, length=50)    
    public String getRowId() {
        return this.rowId;
    }
    
    public void setRowId(String rowId) {
        this.rowId = rowId;
    }
    
	
}


