package th.co.ais.ipfm.domain1;
// Generated 27 Ê.¤. 2553, 17:13:55 by Hibernate Tools 3.2.1.GA


import java.util.Date;
import java.util.List;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;
import javax.persistence.Version;

import th.co.ais.ipfm.domain.MasterDomain;

/**
 * IpRoleFunction generated by hbm2java
 */
@Entity
@Table(name="IP_ROLE_FUNCTION"
    , uniqueConstraints = @UniqueConstraint(columnNames="ROW_ID") 
)
public class IpRoleFunction extends MasterDomain implements java.io.Serializable {
     /**
	 * 
	 */
	private static final long serialVersionUID = 1L; // DMAP Comment : Dead Code Detected - The Following Field has no reference serialVersionUID
//	private IpRoleFunctionId id = new IpRoleFunctionId();
	private String roleId;
    private String funcId;
	private Integer version;
	private String rowId;	

	private List<IpRoleMember> memberCollection;
	private IpFunction ipFunction;
	private IpRole ipRole;
	
	@JoinColumn(name = "FUNC_ID", referencedColumnName = "FUNC_ID", nullable = false ,insertable=false, updatable=false)
	@ManyToOne(optional = false, fetch = FetchType.LAZY)
    public IpFunction getIpFunction() { // DMAP Comment : Dead Code Detected - The Following Method has no reference getIpFunction
		return ipFunction;
	}
	public void setIpFunction(IpFunction ipFunction) { // DMAP Comment : Dead Code Detected - The Following Method has no reference setIpFunction
		this.ipFunction = ipFunction;
	}
	
	@JoinColumn(name = "ROLE_ID", referencedColumnName = "ROLE_ID", nullable = false ,insertable=false, updatable=false)
	@ManyToOne(optional = false, fetch = FetchType.LAZY)
    public IpRole getIpRole() { // DMAP Comment : Dead Code Detected - The Following Method has no reference getIpRole
		return ipRole;
	}
	public void setIpRole(IpRole ipRole) { // DMAP Comment : Dead Code Detected - The Following Method has no reference setIpRole
		this.ipRole = ipRole;
	}
	
	@OneToMany(cascade = CascadeType.ALL, mappedBy = "roleId", fetch = FetchType.LAZY)			
	public List<IpRoleMember> getMemberCollection() { // DMAP Comment : Dead Code Detected - The Following Method has no reference getMemberCollection
		return memberCollection;
	}
	public void setMemberCollection(List<IpRoleMember> memberCollection) { // DMAP Comment : Dead Code Detected - The Following Method has no reference setMemberCollection
		this.memberCollection = memberCollection;
	}
	public IpRoleFunction() {}

	@Column(name="ROLE_ID", nullable=false, length=10)
	public String getRoleId() { // DMAP Comment : Dead Code Detected - The Following Method has no reference getRoleId
        return this.roleId;
    }
    
    public void setRoleId(String roleId) { // DMAP Comment : Dead Code Detected - The Following Method has no reference setRoleId
        this.roleId = roleId;
    }
    @Column(name="FUNC_ID", nullable=false, length=10)
    public String getFuncId() { // DMAP Comment : Dead Code Detected - The Following Method has no reference getFuncId
        return this.funcId;
    }
    
    public void setFuncId(String funcId) { // DMAP Comment : Dead Code Detected - The Following Method has no reference setFuncId
        this.funcId = funcId;
    }
	
    @Version
    @Column(name="VERSION", precision=10, scale=0)
    public Integer getVersion() { // DMAP Comment : Dead Code Detected - The Following Method has no reference getVersion
        return this.version;
    }
	
	public void setVersion(Integer version) { // DMAP Comment : Dead Code Detected - The Following Method has no reference setVersion
        this.version = version;
    }
    @Column(name="CREATE_BY")
	public String getCreatedBy() { // DMAP Comment : Dead Code Detected - The Following Method has no reference getCreatedBy
		return createdBy;
	}

	public void setCreatedBy(String createdBy) { // DMAP Comment : Dead Code Detected - The Following Method has no reference setCreatedBy
		this.createdBy = createdBy;
	}

	@Column(name="CREATE_DATE")
	public Date getCreated() { // DMAP Comment : Dead Code Detected - The Following Method has no reference getCreated
		return created;
	}

	public void setCreated(Date created) { // DMAP Comment : Dead Code Detected - The Following Method has no reference setCreated
		this.created = created;
	}

	@Column(name="UPDATE_BY")
	public String getLastUpdBy() { // DMAP Comment : Dead Code Detected - The Following Method has no reference getLastUpdBy
		return lastUpdBy;
	}

	public void setLastUpdBy(String lastUpdBy) { // DMAP Comment : Dead Code Detected - The Following Method has no reference setLastUpdBy
		this.lastUpdBy = lastUpdBy;
	}
	
	@Column(name="UPDATE_DATE")
	public Date getLastUpd() { // DMAP Comment : Dead Code Detected - The Following Method has no reference getLastUpd
		return lastUpd;
	}
	
	public void setLastUpd(Date lastUpd) { // DMAP Comment : Dead Code Detected - The Following Method has no reference setLastUpd
		this.lastUpd = lastUpd;
	}
    
    @Id
    @Column(name="ROW_ID", unique=true, length=50)    
    public String getRowId() { // DMAP Comment : Dead Code Detected - The Following Method has no reference getRowId
        return this.rowId;
    }
    
    public void setRowId(String rowId) { // DMAP Comment : Dead Code Detected - The Following Method has no reference setRowId
        this.rowId = rowId;
    }
    
	
}


