package th.co.ais.ipfm.domain1;
// Generated 27 �.�. 2553, 17:13:55 by Hibernate Tools 3.2.1.GA


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;

/**
 * IpUrAttachment generated by hbm2java
 */
@Entity
public class IpSubUrAttachmentDto implements java.io.Serializable,Cloneable {


     /**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	
	 private String urNo;
	 private String subUrNo;
	 private String category;
	 private String fileName;
     private String fileLocation;
     private String urStatus;
     private String subUrStatus;
     private String action;
     private String createdBy;
     

    public IpSubUrAttachmentDto() {
    }
       
    @Column(name="UR_NO")
    public String getUrNo() {
		return urNo;
	}
	public void setUrNo(String urNo) {
		this.urNo = urNo;
	}

	@Column(name="SUB_UR_NO")
	public String getSubUrNo() {
		return subUrNo;
	}
	public void setSubUrNo(String subUrNo) {
		this.subUrNo = subUrNo;
	}

	@Column(name="CATEGORY")
	public String getCategory() {
		return category;
	}
	public void setCategory(String category) {
		this.category = category;
	}

	@Id
	@Column(name="FILE_NAME")
	public String getFileName() {
		return fileName;
	}
	public void setFileName(String fileName) {
		this.fileName = fileName;
	}

	@Column(name="FILE_LOCATION")
    public String getFileLocation() {
        return this.fileLocation;
    }
    public void setFileLocation(String fileLocation) {
        this.fileLocation = fileLocation;
    }
       
	@Column(name="CREATE_BY")
	public String getCreatedBy() {
		return createdBy;
	}

	public void setCreatedBy(String createdBy) {
		this.createdBy = createdBy;
	}
	
	@Column(name="UR_STATUS")
	public String getUrStatus() {
		return urStatus;
	}
	
	public void setUrStatus(String urStatus) {
		this.urStatus = urStatus;
	}
	
	@Column(name="SUB_UR_STATUS")
	public String getSubUrStatus() {
		return subUrStatus;
	}
	
	public void setSubUrStatus(String subUrStatus) {
		this.subUrStatus = subUrStatus;
	}
	
	@Column(name="ACTION")
	public String getAction() {
		return action;
	}
	
	public void setAction(String action) {
		this.action = action;
	}

}


