package th.co.ais.ipfm.domain1;
// Generated 27 Ê.¤. 2553, 17:13:55 by Hibernate Tools 3.2.1.GA


import java.math.BigDecimal;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.Locale;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Transient;
import javax.persistence.Version;

import org.hibernate.annotations.Formula;
import org.hibernate.annotations.GenericGenerator;

import th.co.ais.ipfm.domain.MasterDomain;

/**
 * IpUrActionHistory generated by hbm2java
 */
@Entity
@Table(name="IP_UR_ACTION_HISTORY"
)
public class IpUrActionHistory  extends MasterDomain implements java.io.Serializable ,Cloneable{


     private String rowId;
     private Long version;
     private String urNo;
     private String urType;
     private String subUrNo;
     private String subUrType;
     private BigDecimal actionSeq;
     private String reqestUserId;
     private String reqestUser;
     private Date reqestDate;
     private String actionUserId;
     private String actionUser;
     private String actionName;
     private String urStatus;
     private String actionRemark;
     private String userRemark;
     private Date olaDate;
     private Date slaDate;
     private String overOla;
     private String overSla;
     private String subject;
//     private String trunkNo;
//     private String piType;

    public IpUrActionHistory() {
    }

	
    public IpUrActionHistory(String rowId) {
        this.rowId = rowId;
    }
    public IpUrActionHistory(String rowId, String urNo, String urType, String subUrNo, String subUrType, BigDecimal actionSeq, String reqestUserId, String reqestUser, Date reqestDate, String actionUserId, String actionUser, String actionName, String urStatus, String actionRemark, String userRemark, Date olaDate, Date slaDate, String overOla, String overSla, String createBy, Date createDate, String updateBy, Date updateDate) {
       this.rowId = rowId;
       this.urNo = urNo;
       this.urType = urType;
       this.subUrNo = subUrNo;
       this.subUrType = subUrType;
       this.actionSeq = actionSeq;
       this.reqestUserId = reqestUserId;
       this.reqestUser = reqestUser;
       this.reqestDate = reqestDate;
       this.actionUserId = actionUserId;
       this.actionUser = actionUser;
       this.actionName = actionName;
       this.urStatus = urStatus;
       this.actionRemark = actionRemark;
       this.userRemark = userRemark;
       this.olaDate = olaDate;
       this.slaDate = slaDate;
       this.overOla = overOla;
       this.overSla = overSla;
    }
    
    public IpUrActionHistory(IpUrAction action){
		this.setUrNo(action.getUrNo());
		this.setUrType(action.getUrType());
		this.setSubUrNo(action.getSubUrNo());
		this.setSubUrType(action.getSubUrType());
		this.setActionSeq(action.getActionSeq());
		this.setReqestUserId(action.getReqestUserId());							
		this.setReqestUser(action.getReqestUser());							
		this.setReqestDate(action.getReqestDate());							
		this.setActionUserId(action.getActionUserId());							
		this.setActionUser(action.getActionUser());					
		this.setActionName(action.getActionName());							
		this.setUrStatus(action.getUrStatus());							
		this.setActionRemark(action.getActionRemark());							
		this.setUserRemark(action.getUserRemark());							
		this.setOlaDate(action.getOlaDate());							
		this.setSlaDate(action.getSlaDate());							
		this.setOverOla(null);
		this.setOverSla(null);
		this.setCreatedBy(action.getCreatedBy());
		this.setCreated(action.getCreated());						
		this.setLastUpdBy(action.getLastUpdBy());
		this.setLastUpd(action.getLastUpd());
		this.setSubject(action.getSubject());
	}
   
    @Id 
  	@GeneratedValue(generator="system-uuid")
	@GenericGenerator(name="system-uuid", strategy = "uuid")
    @Column(name="ROW_ID", unique=true, nullable=false, length=50)
    public String getRowId() {
        return this.rowId;
    }
    
    public void setRowId(String rowId) {
        this.rowId = rowId;
    }
    @Version
    @Column(name="VERSION", precision=10, scale=0)
    public Long getVersion() {
        return this.version;
    }
    
    public void setVersion(Long version) {
        this.version = version;
    }
    
    @Column(name="UR_NO", length=30)
    public String getUrNo() {
        return this.urNo;
    }
    
    public void setUrNo(String urNo) {
        this.urNo = urNo;
    }
    
    @Column(name="UR_TYPE", length=5)
    public String getUrType() {
        return this.urType;
    }
    
    public void setUrType(String urType) {
        this.urType = urType;
    }
    
    @Column(name="SUB_UR_NO", length=10)
    public String getSubUrNo() {
        return this.subUrNo;
    }
    
    public void setSubUrNo(String subUrNo) {
        this.subUrNo = subUrNo;
    }
    
    @Column(name="SUB_UR_TYPE", length=5)
    public String getSubUrType() {
        return this.subUrType;
    }
    
    public void setSubUrType(String subUrType) {
        this.subUrType = subUrType;
    }
    
    @Column(name="ACTION_SEQ", precision=22, scale=0)
    public BigDecimal getActionSeq() {
        return this.actionSeq;
    }
    
    public void setActionSeq(BigDecimal actionSeq) {
        this.actionSeq = actionSeq;
    }
    
    @Column(name="REQ_USER_ID", length=20)
    public String getReqestUserId() {
        return this.reqestUserId;
    }
    
    public void setReqestUserId(String reqestUserId) {
        this.reqestUserId = reqestUserId;
    }
    
    @Column(name="REQ_USER", length=100)
    public String getReqestUser() {
        return this.reqestUser;
    }
    
    public void setReqestUser(String reqestUser) {
        this.reqestUser = reqestUser;
    }

    @Column(name="REQ_DATE")
    public Date getReqestDate() {
        return this.reqestDate;
    }
    
    public void setReqestDate(Date reqestDate) {
        this.reqestDate = reqestDate;
    }
    
    @Column(name="ACTION_USER_ID", length=100)
    public String getActionUserId() {
        return this.actionUserId;
    }
    
    public void setActionUserId(String actionUserId) {
        this.actionUserId = actionUserId;
    }
    @Transient
    public String getActionUserDesc() {
		String str="";
		if (actionUser!=null && actionUser.trim().length()>0){
			if (actionUser.lastIndexOf(";")==actionUser.trim().length()-1){
				str = actionUser.substring(0, actionUser.length()-1).replaceAll(";", ", <BR>");
			}else{
				str = actionUser.replaceAll(";", ", <BR>");
			}
		}
		return str;
	}
    @Transient
    public String getActionUserSubstr() {
		String str="";
		if (getActionUserDesc()!=null && getActionUserDesc().trim().length()>0) 
			if(getActionUserDesc().trim().length()>30) str = getActionUserDesc().substring(0, 30)+"...";
			else str = getActionUserDesc();
		return str;
	}
    @Column(name="ACTION_USER", length=1000)
    public String getActionUser() {
        return this.actionUser;
    }
    
    public void setActionUser(String actionUser) {
        this.actionUser = actionUser;
    }
    
    @Column(name="ACTION_NAME", length=1000)
    public String getActionName() {
        return this.actionName;
    }
    
    public void setActionName(String actionName) {
        this.actionName = actionName;
    }
    
    @Column(name="UR_STATUS", length=20)
    public String getUrStatus() {
        return this.urStatus;
    }
    
    public void setUrStatus(String urStatus) {
        this.urStatus = urStatus;
    }
    @Transient
    public String getActionRemarkDesc(){
    	String str = "";
    	if (getActionRemark() ==null || getActionRemark().trim().length()==0) {
    		str = "Completed";
    	}else{
    		str = getActionRemark();
    	}
    	return str;
    }
    
    @Column(name="ACTION_REMARK", length=1000)
    public String getActionRemark() {
        return this.actionRemark;
    }
    
    public void setActionRemark(String actionRemark) {
        this.actionRemark = actionRemark;
    }
    
    @Column(name="USER_REMARK", length=1000)
    public String getUserRemark() {
        return this.userRemark;
    }
    
    public void setUserRemark(String userRemark) {
        this.userRemark = userRemark;
    }
    @Temporal(TemporalType.DATE)
    @Column(name="OLA_DATE", length=7)
    public Date getOlaDate() {
        return this.olaDate;
    }
    
    public void setOlaDate(Date olaDate) {
        this.olaDate = olaDate;
    }
    @Temporal(TemporalType.DATE)
    @Column(name="SLA_DATE", length=7)
    public Date getSlaDate() {
        return this.slaDate;
    }
    
    public void setSlaDate(Date slaDate) {
        this.slaDate = slaDate;
    }
    
    @Column(name="OVER_OLA", length=2)
    public String getOverOla() {
        return this.overOla;
    }
    
    public void setOverOla(String overOla) {
        this.overOla = overOla;
    }
    
    @Column(name="OVER_SLA", length=2)
    public String getOverSla() {
        return this.overSla;
    }
    
    public void setOverSla(String overSla) {
        this.overSla = overSla;
    }
	@Column(name="CREATE_BY")
	public String getCreatedBy() {
		return createdBy;
	}

	public void setCreatedBy(String createdBy) {
		this.createdBy = createdBy;
	}

	@Column(name="CREATE_DATE")
	public Date getCreated() {
		return created;
	}

	public void setCreated(Date created) {
		this.created = created;
	}

	@Column(name="UPDATE_BY")
	public String getLastUpdBy() {
		return lastUpdBy;
	}

	public void setLastUpdBy(String lastUpdBy) {
		this.lastUpdBy = lastUpdBy;
	}
	
	@Column(name="UPDATE_DATE")
	public Date getLastUpd() {
		return lastUpd;
	}
	
	public void setLastUpd(Date lastUpd) {
		this.lastUpd = lastUpd;
	}
	@Transient
	public String getLastUpdDes(){
		DateFormat dfm1 = new SimpleDateFormat("dd/MM/yyyy HH:mm:ss",new Locale("en","EN"));
		return dfm1.format(getLastUpd());
	}
	@Column(name="SUBJECT")
	public String getSubject() {
		return subject;
	}

	public void setSubject(String subject) {
		this.subject = subject;
	}


	@Override
    public Object clone() throws CloneNotSupportedException    {
		IpUrActionHistory another = (IpUrActionHistory) super.clone();
        return another;
    }

//	@Formula("(select i.trunk_No from IP_UR_PHYSICAL_INTERFACE i where i.sub_ur_no = sub_ur_no and i.ur_no = ur_no)")
//	public String getTrunkNo() {
//		return trunkNo;
//	}
//
//	public void setTrunkNo(String trunkNo) {
//		this.trunkNo = trunkNo;
//	}
//
//	@Formula("(select i.pi_type from IP_UR_PHYSICAL_INTERFACE i where i.sub_ur_no = sub_ur_no and i.ur_no = ur_no)")
//	public String getPiType() {
//		return piType;
//	}
//
//	public void setPiType(String piType) {
//		this.piType = piType;
//	}

}


