package th.co.ais.ipfm.domain1;
// Generated 27 Ê.¤. 2553, 17:13:55 by Hibernate Tools 3.2.1.GA


import java.math.BigDecimal;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.Locale;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinColumns;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Transient;
import javax.persistence.Version;

import org.hibernate.annotations.GenericGenerator;
import org.hibernate.annotations.NotFound;
import org.hibernate.annotations.NotFoundAction;

import th.co.ais.ipfm.domain.MasterDomain;

/**
 * IpUrAction generated by hbm2java
 */
@Entity
@Table(name="IP_UR_ACTION"
)
public class IpUrAction  extends MasterDomain implements java.io.Serializable,Cloneable {

	@Column(name="UR_NO", length=30)
	private String urNo; 
	
	@Column(name="UR_TYPE", length=5)
	private String urType; 
	
	@Column(name="SUB_UR_NO", length=10)
	private String subUrNo; 
	
	@Column(name="SUB_UR_TYPE", length=5)
	private String subUrType; 
	
	@Column(name="ACTION_SEQ", precision=22, scale=0)
	private BigDecimal actionSeq;
	
	@Column(name="REQ_USER_ID", length=20)
	private String reqestUserId; 
	
	@Column(name="REQ_USER", length=100)
	private String reqestUser; 
	
    @Column(name="REQ_DATE")
	private Date reqestDate; 
	
	@Column(name="ACTION_USER_ID", length=1000)
	private String actionUserId;
	
	@Column(name="ACTION_USER", length=1000)
	private String actionUser; 
	
	@Column(name="ACTION_NAME", length=4000)
	private String actionName; 
	
	@Column(name="UR_STATUS", length=20)
	private String urStatus; 
	
	@Column(name="ACTION_REMARK", length=1000)
	private String actionRemark; 
	
	@Column(name="USER_REMARK", length=1000)
	private String userRemark; 
	
	@Temporal(TemporalType.DATE)
	@Column(name="OLA_DATE", length=7)
	private Date olaDate; 
	
	@Temporal(TemporalType.DATE)
    @Column(name="SLA_DATE", length=7)
	private Date slaDate; 
	
	@Column(name="CALL_FUNCTION_ID", length=100)
	private String callFunctionId; 
	
	@Column(name="CALL_MODE", length=10)
	private String callMode; 
	
	@Id 
 	@GeneratedValue(generator="system-uuid")
	@GenericGenerator(name="system-uuid", strategy = "uuid")
    @Column(name="ROW_ID", unique=true, nullable=false, length=50)
	private String rowId; 
	
	@Version
    @Column(name="VERSION", precision=10, scale=0)
	private Long version; 
	
	@Column(name="SUBJECT", length=1000)
	private String subject; 
	
	@Column(name="CREATE_BY")
	private String createdBy;
	
    @Column(name="CREATE_DATE", length=10)
	private Date created;
	
	@Column(name="UPDATE_BY")
	private String lastUpdBy;
	
    @Column(name="UPDATE_DATE", length=10)
	private Date lastUpd;
	
	@ManyToOne(cascade=CascadeType.ALL,  fetch=FetchType.LAZY)
	@NotFound(action=NotFoundAction.IGNORE)
	@JoinColumns( {
    	@JoinColumn(name = "UR_NO", referencedColumnName = "UR_NO", nullable = false, insertable=false, updatable=false),
    	@JoinColumn(name = "SUB_UR_NO", referencedColumnName = "SUB_UR_NO" , nullable = false, insertable=false, updatable=false)
    })
    public IpUrFirewall firewall;
	
	@ManyToOne(cascade=CascadeType.ALL,  fetch=FetchType.LAZY)
	@NotFound(action=NotFoundAction.IGNORE)
	@JoinColumns( {
    	@JoinColumn(name = "UR_NO", referencedColumnName = "UR_NO", nullable = false, insertable=false, updatable=false),
    	@JoinColumn(name = "SUB_UR_NO", referencedColumnName = "SUB_UR_NO" , nullable = false, insertable=false, updatable=false)
    })
    public IpUrAccessListCdn accessListCdn;

	@ManyToOne(cascade=CascadeType.ALL,  fetch=FetchType.LAZY)
	@NotFound(action=NotFoundAction.IGNORE)
	@JoinColumns( {
    	@JoinColumn(name = "UR_NO", referencedColumnName = "UR_NO", nullable = false, insertable=false, updatable=false),
    	@JoinColumn(name = "SUB_UR_NO", referencedColumnName = "SUB_UR_NO" , nullable = false, insertable=false, updatable=false)
    })
    public IpUrAccessListTnp accessListTnp;

	@ManyToOne(cascade=CascadeType.ALL,  fetch=FetchType.LAZY)
	@NotFound(action=NotFoundAction.IGNORE)
	@JoinColumns( {
    	@JoinColumn(name = "UR_NO", referencedColumnName = "UR_NO", nullable = false, insertable=false, updatable=false),
    	@JoinColumn(name = "SUB_UR_NO", referencedColumnName = "SUB_UR_NO" , nullable = false, insertable=false, updatable=false)
    })
    public IpUrPhysicalInterface phyInterface;

	@ManyToOne(cascade=CascadeType.ALL,  fetch=FetchType.LAZY)
	@NotFound(action=NotFoundAction.IGNORE)
	@JoinColumns( {
    	@JoinColumn(name = "UR_NO", referencedColumnName = "UR_NO", nullable = false, insertable=false, updatable=false),
    	@JoinColumn(name = "SUB_UR_NO", referencedColumnName = "SUB_UR_NO" , nullable = false, insertable=false, updatable=false)
    })
    public IpUrInterfaceGateway gateway;

	@ManyToOne(cascade=CascadeType.ALL,  fetch=FetchType.LAZY)
	@NotFound(action=NotFoundAction.IGNORE)
	@JoinColumns( {
    	@JoinColumn(name = "UR_NO", referencedColumnName = "UR_NO", nullable = false, insertable=false, updatable=false),
    	@JoinColumn(name = "SUB_UR_NO", referencedColumnName = "SUB_UR_NO" , nullable = false, insertable=false, updatable=false)
    })
    public IpUrRouting routing;

	@ManyToOne(cascade=CascadeType.ALL,  fetch=FetchType.LAZY)
	@NotFound(action=NotFoundAction.IGNORE)
	@JoinColumns( {
    	@JoinColumn(name = "UR_NO", referencedColumnName = "UR_NO", nullable = false, insertable=false, updatable=false),
    	@JoinColumn(name = "SUB_UR_NO", referencedColumnName = "SUB_UR_NO" , nullable = false, insertable=false, updatable=false)
    })
    public IpUrF5 f5;	
	
	@Transient
	public int subStrLength = 20; // DMAP Comment : Dead Code Detected - The Following Field has no reference subStrLength

	public String getCreatedBy() { // DMAP Comment : Dead Code Detected - The Following Method has no reference getCreatedBy
		return createdBy;
	}

	public void setCreatedBy(String createdBy) { // DMAP Comment : Dead Code Detected - The Following Method has no reference setCreatedBy
		this.createdBy = createdBy;
	}

	public Date getCreated() { // DMAP Comment : Dead Code Detected - The Following Method has no reference getCreated
		return created;
	}

	public void setCreated(Date created) { // DMAP Comment : Dead Code Detected - The Following Method has no reference setCreated
		this.created = created;
	}

	public String getLastUpdBy() { // DMAP Comment : Dead Code Detected - The Following Method has no reference getLastUpdBy
		return lastUpdBy;
	}
	
	
	public void setLastUpdBy(String lastUpdBy) { // DMAP Comment : Dead Code Detected - The Following Method has no reference setLastUpdBy
		this.lastUpdBy = lastUpdBy;
	}
	public String getLastUpdDes(){ // DMAP Comment : Dead Code Detected - The Following Method has no reference getLastUpdDes
		DateFormat dfm = new SimpleDateFormat("dd/MM/yyyy",new Locale("en","EN"));
		return dfm.format(getLastUpd());
	}

	public Date getLastUpd() {
		return lastUpd;
	}

	public void setLastUpd(Date lastUpd) { // DMAP Comment : Dead Code Detected - The Following Method has no reference setLastUpd
		this.lastUpd = lastUpd;
	}

	public String getUrNo() { // DMAP Comment : Dead Code Detected - The Following Method has no reference getUrNo
		return urNo;
	}

	public void setUrNo(String urNo) { // DMAP Comment : Dead Code Detected - The Following Method has no reference setUrNo
		this.urNo = urNo;
	}

	public String getUrType() { // DMAP Comment : Dead Code Detected - The Following Method has no reference getUrType
		return urType;
	}

	public void setUrType(String urType) { // DMAP Comment : Dead Code Detected - The Following Method has no reference setUrType
		this.urType = urType;
	}

	public String getSubUrNo() { // DMAP Comment : Dead Code Detected - The Following Method has no reference getSubUrNo
		return subUrNo;
	}

	public void setSubUrNo(String subUrNo) { // DMAP Comment : Dead Code Detected - The Following Method has no reference setSubUrNo
		this.subUrNo = subUrNo;
	}

	public String getSubUrType() { // DMAP Comment : Dead Code Detected - The Following Method has no reference getSubUrType
		return subUrType;
	}

	public void setSubUrType(String subUrType) { // DMAP Comment : Dead Code Detected - The Following Method has no reference setSubUrType
		this.subUrType = subUrType;
	}

	public BigDecimal getActionSeq() { // DMAP Comment : Dead Code Detected - The Following Method has no reference getActionSeq
		return actionSeq;
	}

	public void setActionSeq(BigDecimal actionSeq) { // DMAP Comment : Dead Code Detected - The Following Method has no reference setActionSeq
		this.actionSeq = actionSeq;
	}

	public String getReqestUserId() { // DMAP Comment : Dead Code Detected - The Following Method has no reference getReqestUserId
		return reqestUserId;
	}

	public void setReqestUserId(String reqestUserId) { // DMAP Comment : Dead Code Detected - The Following Method has no reference setReqestUserId
		this.reqestUserId = reqestUserId;
	}

	public String getReqestUser() { // DMAP Comment : Dead Code Detected - The Following Method has no reference getReqestUser
		return reqestUser;
	}

	public void setReqestUser(String reqestUser) { // DMAP Comment : Dead Code Detected - The Following Method has no reference setReqestUser
		this.reqestUser = reqestUser;
	}

	public Date getReqestDate() { // DMAP Comment : Dead Code Detected - The Following Method has no reference getReqestDate
		return reqestDate;
	}

	public void setReqestDate(Date reqestDate) { // DMAP Comment : Dead Code Detected - The Following Method has no reference setReqestDate
		this.reqestDate = reqestDate;
	}

	public String getActionUserId() { // DMAP Comment : Dead Code Detected - The Following Method has no reference getActionUserId
		return actionUserId;
	}

	public void setActionUserId(String actionUserId) { // DMAP Comment : Dead Code Detected - The Following Method has no reference setActionUserId
		this.actionUserId = actionUserId;
	}
	@Transient
    public String getActionUserDesc() {
		String str="";
		if (actionUser!=null && actionUser.trim().length()>0){
			if (actionUser.lastIndexOf(";")==actionUser.trim().length()-1){
				str = actionUser.substring(0, actionUser.length()-1).replaceAll(";", ", <BR>");
			}else{
				str = actionUser.replaceAll(";", ", <BR>");
			}
		}
		return str;
	}
	@Transient
    public String getActionUserSubstr() { // DMAP Comment : Dead Code Detected - The Following Method has no reference getActionUserSubstr
		String str="";
		if (getActionUserDesc()!=null && getActionUserDesc().trim().length()>0) 
			if(getActionUserDesc().trim().length()>50) str = getActionUserDesc().substring(0, 50)+"...";
			else str = getActionUserDesc();
		return str;
	}

	public String getActionUser() { // DMAP Comment : Dead Code Detected - The Following Method has no reference getActionUser
		return actionUser;
	}

	public void setActionUser(String actionUser) { // DMAP Comment : Dead Code Detected - The Following Method has no reference setActionUser
		this.actionUser = actionUser;
	}

	public String getActionName() { // DMAP Comment : Dead Code Detected - The Following Method has no reference getActionName
		return actionName;
	}

	public void setActionName(String actionName) { // DMAP Comment : Dead Code Detected - The Following Method has no reference setActionName
		this.actionName = actionName;
	}

	public String getUrStatus() { // DMAP Comment : Dead Code Detected - The Following Method has no reference getUrStatus
		return urStatus;
	}

	public void setUrStatus(String urStatus) { // DMAP Comment : Dead Code Detected - The Following Method has no reference setUrStatus
		this.urStatus = urStatus;
	}

	public String getActionRemark() { // DMAP Comment : Dead Code Detected - The Following Method has no reference getActionRemark
		return actionRemark;
	}

	public void setActionRemark(String actionRemark) { // DMAP Comment : Dead Code Detected - The Following Method has no reference setActionRemark
		this.actionRemark = actionRemark;
	}

	public String getUserRemark() { // DMAP Comment : Dead Code Detected - The Following Method has no reference getUserRemark
		return userRemark;
	}

	public void setUserRemark(String userRemark) { // DMAP Comment : Dead Code Detected - The Following Method has no reference setUserRemark
		this.userRemark = userRemark;
	}

	public String getCallFunctionId() { // DMAP Comment : Dead Code Detected - The Following Method has no reference getCallFunctionId
		return callFunctionId;
	}

	public void setCallFunctionId(String callFunctionId) { // DMAP Comment : Dead Code Detected - The Following Method has no reference setCallFunctionId
		this.callFunctionId = callFunctionId;
	}

	public String getCallMode() { // DMAP Comment : Dead Code Detected - The Following Method has no reference getCallMode
		return callMode;
	}

	public void setCallMode(String callMode) { // DMAP Comment : Dead Code Detected - The Following Method has no reference setCallMode
		this.callMode = callMode;
	}

	public String getRowId() { // DMAP Comment : Dead Code Detected - The Following Method has no reference getRowId
		return rowId;
	}

	public void setRowId(String rowId) { // DMAP Comment : Dead Code Detected - The Following Method has no reference setRowId
		this.rowId = rowId;
	}


	public Long getVersion() { // DMAP Comment : Dead Code Detected - The Following Method has no reference getVersion
		return version;
	}

	public void setVersion(Long version) { // DMAP Comment : Dead Code Detected - The Following Method has no reference setVersion
		this.version = version;
	}

	public String getSubject() { // DMAP Comment : Dead Code Detected - The Following Method has no reference getSubject
		return subject;
	}

	public void setSubject(String subject) { // DMAP Comment : Dead Code Detected - The Following Method has no reference setSubject
		this.subject = subject;
	}

	public Date getOlaDate() { // DMAP Comment : Dead Code Detected - The Following Method has no reference getOlaDate
		return olaDate;
	}

	public void setOlaDate(Date olaDate) { // DMAP Comment : Dead Code Detected - The Following Method has no reference setOlaDate
		this.olaDate = olaDate;
	}

	public Date getSlaDate() { // DMAP Comment : Dead Code Detected - The Following Method has no reference getSlaDate
		return slaDate;
	}

	public void setSlaDate(Date slaDate) { // DMAP Comment : Dead Code Detected - The Following Method has no reference setSlaDate
		this.slaDate = slaDate;
	}

	public IpUrFirewall getFirewall() { // DMAP Comment : Dead Code Detected - The Following Method has no reference getFirewall
		return firewall;
	}

	public void setFirewall(IpUrFirewall firewall) { // DMAP Comment : Dead Code Detected - The Following Method has no reference setFirewall
		this.firewall = firewall;
	}

	public IpUrAccessListCdn getAccessListCdn() { // DMAP Comment : Dead Code Detected - The Following Method has no reference getAccessListCdn
		return accessListCdn;
	}

	public void setAccessListCdn(IpUrAccessListCdn accessListCdn) { // DMAP Comment : Dead Code Detected - The Following Method has no reference setAccessListCdn
		this.accessListCdn = accessListCdn;
	}

	public IpUrAccessListTnp getAccessListTnp() { // DMAP Comment : Dead Code Detected - The Following Method has no reference getAccessListTnp
		return accessListTnp;
	}

	public void setAccessListTnp(IpUrAccessListTnp accessListTnp) { // DMAP Comment : Dead Code Detected - The Following Method has no reference setAccessListTnp
		this.accessListTnp = accessListTnp;
	}

	public IpUrPhysicalInterface getPhyInterface() { // DMAP Comment : Dead Code Detected - The Following Method has no reference getPhyInterface
		return phyInterface;
	}

	public void setPhyInterface(IpUrPhysicalInterface phyInterface) { // DMAP Comment : Dead Code Detected - The Following Method has no reference setPhyInterface
		this.phyInterface = phyInterface;
	}

	public IpUrInterfaceGateway getGateway() { // DMAP Comment : Dead Code Detected - The Following Method has no reference getGateway
		return gateway;
	}

	public void setGateway(IpUrInterfaceGateway gateway) { // DMAP Comment : Dead Code Detected - The Following Method has no reference setGateway
		this.gateway = gateway;
	}

	public IpUrRouting getRouting() { // DMAP Comment : Dead Code Detected - The Following Method has no reference getRouting
		return routing;
	}

	public void setRouting(IpUrRouting routing) { // DMAP Comment : Dead Code Detected - The Following Method has no reference setRouting
		this.routing = routing;
	}

	public IpUrF5 getF5() { // DMAP Comment : Dead Code Detected - The Following Method has no reference getF5
		return f5;
	}

	public void setF5(IpUrF5 f5) { // DMAP Comment : Dead Code Detected - The Following Method has no reference setF5
		this.f5 = f5;
	}
	
	@Override
    public Object clone() throws CloneNotSupportedException
    {
		IpUrAction another = (IpUrAction) super.clone();
        return another;
    }

}



