package th.co.ais.ipfm.domain1;
// Generated 27 �.�. 2553, 17:13:55 by Hibernate Tools 3.2.1.GA


import java.util.Date;

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.JoinColumn;
import javax.persistence.JoinColumns;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Transient;
import javax.persistence.UniqueConstraint;
import javax.persistence.Version;

import org.hibernate.annotations.GenericGenerator;

import th.co.ais.ipfm.domain.MasterDomain;

/**
 * IpUrF5 generated by hbm2java
 */
@Entity
@Table(name="IP_UR_F5"
    , uniqueConstraints = @UniqueConstraint(columnNames="ROW_ID") 
)
public class IpUrF5 extends MasterDomain  implements java.io.Serializable , Cloneable {


    private IpUrF5Id id;
    private String vipAddress; 
    private String vipPort;
    private String isSnapIp; 
    private String snapIp; 
    private String isPersistence;
    private String method;
    private String poolIpAddress; 
    private String poolIpPort; 
    private String poolWeight; 
 	private String isAssign;
 	private String isImpact;
 	private String sysOwnerRemark; 
 	private String pmRemark; 
 	private String actmRemark; 
 	private String teamRemark;
    private IpUrStatus subUrStatus;
    private String subUrStatusTxt;
    private String urType; 
    private String rowId;
	private String isTnp;
	private String changeType;
	private Long version;
	
	private String isApprove;
	private String isReject;
	private boolean isSelected;
     
	
	private boolean impactSelected;
	
//	@Transient
//	public boolean isImpactSelected() {
//		if (getIsImpact()==null || getIsImpact().equalsIgnoreCase("N"))
//			return false;
//		else
//			return true;
//	}
	@Transient
	public boolean isImpactSelected() { // DMAP Comment : Dead Code Detected - The Following Method has no reference isImpactSelected
		return impactSelected;
	}
    public void setImpactSelected(boolean impactSelected) { // DMAP Comment : Dead Code Detected - The Following Method has no reference setImpactSelected
		this.impactSelected = impactSelected;
	}
 	
    @GeneratedValue(generator="system-uuid")
	@GenericGenerator(name="system-uuid", strategy = "uuid")
 	@Column(name="ROW_ID", unique=true, length=50)
 	public String getRowId() { // DMAP Comment : Dead Code Detected - The Following Method has no reference getRowId
 		return rowId;
 	}

 	public void setRowId(String rowId) { // DMAP Comment : Dead Code Detected - The Following Method has no reference setRowId
 		this.rowId = rowId;
 	}

    @Version
    @Column(name="VERSION", precision=10, scale=0)
 	public Long getVersion() { // DMAP Comment : Dead Code Detected - The Following Method has no reference getVersion
 		return version;
 	}

 	public void setVersion(Long version) { // DMAP Comment : Dead Code Detected - The Following Method has no reference setVersion
 		this.version = version;
 	}

	@EmbeddedId
    @AttributeOverrides( {
        @AttributeOverride(name="urNo", column=@Column(name="UR_NO", nullable=false, length=20) ), 
        @AttributeOverride(name="subUrNo", column=@Column(name="SUB_UR_NO", nullable=false, length=10) ) } )
	public IpUrF5Id getId() { // DMAP Comment : Dead Code Detected - The Following Method has no reference getId
		return id;
	}

	public void setId(IpUrF5Id id) { // DMAP Comment : Dead Code Detected - The Following Method has no reference setId
		this.id = id;
	}
	@Column(name="VIP_ADDRESS", length=100)
	public String getVipAddress() { // DMAP Comment : Dead Code Detected - The Following Method has no reference getVipAddress
		return vipAddress;
	}

	public void setVipAddress(String vipAddress) { // DMAP Comment : Dead Code Detected - The Following Method has no reference setVipAddress
		this.vipAddress = vipAddress;
	}
	@Column(name="VIP_PORT", length=10)
	public String getVipPort() { // DMAP Comment : Dead Code Detected - The Following Method has no reference getVipPort
		return vipPort;
	}

	public void setVipPort(String vipPort) { // DMAP Comment : Dead Code Detected - The Following Method has no reference setVipPort
		this.vipPort = vipPort;
	}
	@Column(name="IS_SNAP_IP", length=10)
	public String getIsSnapIp() { // DMAP Comment : Dead Code Detected - The Following Method has no reference getIsSnapIp
		return isSnapIp;
	}

	public void setIsSnapIp(String isSnapIp) { // DMAP Comment : Dead Code Detected - The Following Method has no reference setIsSnapIp
		this.isSnapIp = isSnapIp;
	}
	
	@Column(name="SNAP_IP", length=100)
	public String getSnapIp() { // DMAP Comment : Dead Code Detected - The Following Method has no reference getSnapIp
		return snapIp;
	}

	public void setSnapIp(String snapIp) { // DMAP Comment : Dead Code Detected - The Following Method has no reference setSnapIp
		this.snapIp = snapIp;
	}
	
	@Column(name="IS_PERSISTENCE", length=10)
	public String getIsPersistence() { // DMAP Comment : Dead Code Detected - The Following Method has no reference getIsPersistence
		return isPersistence;
	}

	public void setIsPersistence(String isPersistence) { // DMAP Comment : Dead Code Detected - The Following Method has no reference setIsPersistence
		this.isPersistence = isPersistence;
	}
	
	@Column(name="METHOD", length=10)
	public String getMethod() { // DMAP Comment : Dead Code Detected - The Following Method has no reference getMethod
		return method;
	}

	public void setMethod(String method) { // DMAP Comment : Dead Code Detected - The Following Method has no reference setMethod
		this.method = method;
	}

	@Column(name="POOL_IP_ADDRESS", length=100)
	public String getPoolIpAddress() { // DMAP Comment : Dead Code Detected - The Following Method has no reference getPoolIpAddress
		return poolIpAddress;
	}

	public void setPoolIpAddress(String poolIpAddress) { // DMAP Comment : Dead Code Detected - The Following Method has no reference setPoolIpAddress
		this.poolIpAddress = poolIpAddress;
	}

	@Column(name="POOL_IP_PORT", length=10)
	public String getPoolIpPort() { // DMAP Comment : Dead Code Detected - The Following Method has no reference getPoolIpPort
		return poolIpPort;
	}

	public void setPoolIpPort(String poolIpPort) { // DMAP Comment : Dead Code Detected - The Following Method has no reference setPoolIpPort
		this.poolIpPort = poolIpPort;
	}

	@Column(name="POOL_WEIGHT", length=10)
	public String getPoolWeight() { // DMAP Comment : Dead Code Detected - The Following Method has no reference getPoolWeight
		return poolWeight;
	}

	public void setPoolWeight(String poolWeight) { // DMAP Comment : Dead Code Detected - The Following Method has no reference setPoolWeight
		this.poolWeight = poolWeight;
	}
	
	@Column(name="IS_ASSIGN", length=10)
	public String getIsAssign() { // DMAP Comment : Dead Code Detected - The Following Method has no reference getIsAssign
		return isAssign;
	}

	public void setIsAssign(String isAssign) { // DMAP Comment : Dead Code Detected - The Following Method has no reference setIsAssign
		this.isAssign = isAssign;
	}
	
	@Column(name="IS_IMPACT", length=10)
	public String getIsImpact() { // DMAP Comment : Dead Code Detected - The Following Method has no reference getIsImpact
		return isImpact;
	}

	public void setIsImpact(String isImpact) { // DMAP Comment : Dead Code Detected - The Following Method has no reference setIsImpact
		this.isImpact = isImpact;
	}
	
	@Column(name="SYS_OWNER_REMARK", length=1000)
	public String getSysOwnerRemark() { // DMAP Comment : Dead Code Detected - The Following Method has no reference getSysOwnerRemark
		return sysOwnerRemark;
	}

	public void setSysOwnerRemark(String sysOwnerRemark) { // DMAP Comment : Dead Code Detected - The Following Method has no reference setSysOwnerRemark
		this.sysOwnerRemark = sysOwnerRemark;
	}

	@Column(name="PM_REMARK", length=1000)
	public String getPmRemark() { // DMAP Comment : Dead Code Detected - The Following Method has no reference getPmRemark
		return pmRemark;
	}

	public void setPmRemark(String pmRemark) { // DMAP Comment : Dead Code Detected - The Following Method has no reference setPmRemark
		this.pmRemark = pmRemark;
	}
	
	@Column(name="TEAM_REMARK", length=1000)
	public String getTeamRemark() { // DMAP Comment : Dead Code Detected - The Following Method has no reference getTeamRemark
		return teamRemark;
	}

	public void setTeamRemark(String teamRemark) { // DMAP Comment : Dead Code Detected - The Following Method has no reference setTeamRemark
		this.teamRemark = teamRemark;
	}

	@Column(name="ACTM_REMARK", length=1000)
	public String getActmRemark() { // DMAP Comment : Dead Code Detected - The Following Method has no reference getActmRemark
		return actmRemark;
	}

	public void setActmRemark(String actmRemark) { // DMAP Comment : Dead Code Detected - The Following Method has no reference setActmRemark
		this.actmRemark = actmRemark;
	}

 	@ManyToOne(optional = false, fetch = FetchType.LAZY)
    @JoinColumns( {
    	@JoinColumn(name = "SUB_UR_STATUS", referencedColumnName = "SUB_UR_STATUS_ID", nullable = true, insertable=false, updatable=false),
    	@JoinColumn(name = "UR_TYPE", referencedColumnName = "UR_TYPE" , nullable = true, insertable=false, updatable=false)
    })
	public IpUrStatus getSubUrStatus() { // DMAP Comment : Dead Code Detected - The Following Method has no reference getSubUrStatus
		return subUrStatus;
	}

	public void setSubUrStatus(IpUrStatus subUrStatus) { // DMAP Comment : Dead Code Detected - The Following Method has no reference setSubUrStatus
		this.subUrStatus = subUrStatus;
	}

	@Column(name="UR_TYPE", length=5)
	public String getUrType() { // DMAP Comment : Dead Code Detected - The Following Method has no reference getUrType
		return urType;
	}

	public void setUrType(String urType) { // DMAP Comment : Dead Code Detected - The Following Method has no reference setUrType
		this.urType = urType;
	}

	@Column(name="SUB_UR_STATUS", length=20)
	public String getSubUrStatusTxt() { // DMAP Comment : Dead Code Detected - The Following Method has no reference getSubUrStatusTxt
		return subUrStatusTxt;
	}

	public void setSubUrStatusTxt(String subUrStatusTxt) { // DMAP Comment : Dead Code Detected - The Following Method has no reference setSubUrStatusTxt
		this.subUrStatusTxt = subUrStatusTxt;
	}
	
	@Transient
	public String getIsApprove() { // DMAP Comment : Dead Code Detected - The Following Method has no reference getIsApprove
		return isApprove;
	}

	public void setIsApprove(String isApprove) { // DMAP Comment : Dead Code Detected - The Following Method has no reference setIsApprove
		this.isApprove = isApprove;
	}

	@Transient
	public String getIsReject() { // DMAP Comment : Dead Code Detected - The Following Method has no reference getIsReject
		return isReject;
	}

	public void setIsReject(String isReject) { // DMAP Comment : Dead Code Detected - The Following Method has no reference setIsReject
		this.isReject = isReject;
	}
 	
	@Transient
	public boolean getIsSelected() { // DMAP Comment : Dead Code Detected - The Following Method has no reference getIsSelected
		return isSelected;
	}

	public void setIsSelected(boolean isSelected) { // DMAP Comment : Dead Code Detected - The Following Method has no reference setIsSelected
		this.isSelected = isSelected;
	}

	@Column(name="CHANGE_TYPE", length=2)
	public String getChangeType() { // DMAP Comment : Dead Code Detected - The Following Method has no reference getChangeType
		return changeType;
	}

	public void setChangeType(String changeType) { // DMAP Comment : Dead Code Detected - The Following Method has no reference setChangeType
		this.changeType = changeType;
	}

	public void setSelected(boolean isSelected) { // DMAP Comment : Dead Code Detected - The Following Method has no reference setSelected
		this.isSelected = isSelected;
	}

	@Column(name="IS_TNP", length=2)
	public String getIsTnp() { // DMAP Comment : Dead Code Detected - The Following Method has no reference getIsTnp
		return isTnp;
	}

	public void setIsTnp(String isTnp) { // DMAP Comment : Dead Code Detected - The Following Method has no reference setIsTnp
		this.isTnp = isTnp;
	}

    @Column(name="CREATE_BY")
 	public String getCreatedBy() { // DMAP Comment : Dead Code Detected - The Following Method has no reference getCreatedBy
 		return createdBy;
 	}

 	public void setCreatedBy(String createdBy) { // DMAP Comment : Dead Code Detected - The Following Method has no reference setCreatedBy
 		this.createdBy = createdBy;
 	}

 	@Column(name="CREATE_DATE")
 	public Date getCreated() { // DMAP Comment : Dead Code Detected - The Following Method has no reference getCreated
 		return created;
 	}

 	public void setCreated(Date created) { // DMAP Comment : Dead Code Detected - The Following Method has no reference setCreated
 		this.created = created;
 	}

 	@Column(name="UPDATE_BY")
 	public String getLastUpdBy() { // DMAP Comment : Dead Code Detected - The Following Method has no reference getLastUpdBy
 		return lastUpdBy;
 	}

 	public void setLastUpdBy(String lastUpdBy) { // DMAP Comment : Dead Code Detected - The Following Method has no reference setLastUpdBy
 		this.lastUpdBy = lastUpdBy;
 	}
 		
 	@Column(name="UPDATE_DATE")
 	public Date getLastUpd() { // DMAP Comment : Dead Code Detected - The Following Method has no reference getLastUpd
 		return lastUpd;
 	}
 		
 	public void setLastUpd(Date lastUpd) { // DMAP Comment : Dead Code Detected - The Following Method has no reference setLastUpd
 		this.lastUpd = lastUpd;
 	}
	
    @Override
    public Object clone() throws CloneNotSupportedException
    {
    	IpUrF5 another = (IpUrF5) super.clone();
        //? take care of any deep copies to be made here
        return another;
    }
}


