package th.co.ais.ipfm.domain1;
// Generated 27 �.�. 2553, 17:13:55 by Hibernate Tools 3.2.1.GA


import java.util.Date;

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.JoinColumn;
import javax.persistence.JoinColumns;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Transient;
import javax.persistence.UniqueConstraint;
import javax.persistence.Version;

import org.hibernate.annotations.GenericGenerator;

import th.co.ais.ipfm.domain.MasterDomain;

/**
 * IpUrInterfaceGateway generated by hbm2java
 */
@Entity
@Table(name="IP_UR_INTERFACE_GATEWAY"
    , uniqueConstraints = @UniqueConstraint(columnNames="ROW_ID") 
)
public class IpUrInterfaceGateway extends MasterDomain  implements java.io.Serializable , Cloneable {

	@EmbeddedId
    @AttributeOverrides( {
        @AttributeOverride(name="urNo", column=@Column(name="UR_NO", nullable=false, length=20) ), 
        @AttributeOverride(name="subUrNo", column=@Column(name="SUB_UR_NO", nullable=false, length=10) ) } )	
    private IpUrInterfaceGatewayId id;

	@Column(name="IP_ADDRESS", length=50)
	private String ipAddress; 
	
	@Column(name="MASK", length=50)
	private String mask;
	
	@Column(name="NETWORK_TYPE_ID", length=50)
	private String networkTypeId; 
	
	@Column(name="NETWORK_TYPE_DESC", length=1000)
	private String networkTypeDesc; 
	
	@Column(name="LOCATION_NAME", length=200)
	private String locationName; 
	
	@Column(name="REQ_VLAN_ID", length=50)
	private String reqVlanId; 
	
	@Column(name="REQ_DESC", length=1000)
	private String reqDesc;
	
	@Column(name="IS_ASSIGN", length=10)
	private String isAssign;
	
	@Column(name="IS_IMPACT", length=10)
	private String isImpact;
	
	@Column(name="SYS_OWNER_REMARK", length=1000)
	private String sysOwnerRemark; 
	
	@Column(name="PM_REMARK", length=1000)
	private String pmRemark; 
	
	@Column(name="TEAM_REMARK", length=1000)
	private String teamRemark; 
	
	@Column(name="ACTM_REMARK", length=1000)
	private String actmRemark; 
		
	@ManyToOne(optional = false, fetch = FetchType.LAZY)
    @JoinColumns( {
    	@JoinColumn(name = "SUB_UR_STATUS", referencedColumnName = "SUB_UR_STATUS_ID", nullable = true, insertable=false, updatable=false),
    	@JoinColumn(name = "UR_TYPE", referencedColumnName = "UR_TYPE" , nullable = true, insertable=false, updatable=false)
    })
    private IpUrStatus subUrStatus;
	
	@Column(name="SUB_UR_STATUS", length=20)
    private String subUrStatusTxt;
    
    @Column(name="UR_TYPE", length=5)
    private String urType; 
    
	@Column(name="IS_TNP", length=2)
	private String isTnp;
	
    @GeneratedValue(generator="system-uuid")
	@GenericGenerator(name="system-uuid", strategy = "uuid")
	@Column(name="ROW_ID", unique=true, length=50)
    private String rowId;
    
	@Column(name="CHANGE_TYPE", length=2)
	private String changeType;
    
	@Transient
	private String isApprove;
	
	@Transient
	private String isReject;
	
	@Transient
	private boolean isSelected;
	
	@Transient
	private boolean impactSelected;
	
//	public boolean isImpactSelected() {
//		if (getIsImpact()==null || getIsImpact().equalsIgnoreCase("N"))
//			return false;
//		else
//			return true;
//	}
	public boolean isImpactSelected() { // DMAP Comment : Dead Code Detected - The Following Method has no reference isImpactSelected
		return impactSelected;
	}
    public void setImpactSelected(boolean impactSelected) { // DMAP Comment : Dead Code Detected - The Following Method has no reference setImpactSelected
		this.impactSelected = impactSelected;
	}
    
    @Version
    @Column(name="VERSION", precision=10, scale=0)
    private Long version;
    
    @Column(name="CREATE_BY")
	public String getCreatedBy() { // DMAP Comment : Dead Code Detected - The Following Method has no reference getCreatedBy
		return createdBy;
	}

	public void setCreatedBy(String createdBy) { // DMAP Comment : Dead Code Detected - The Following Method has no reference setCreatedBy
		this.createdBy = createdBy;
	}

	@Column(name="CREATE_DATE")
	public Date getCreated() { // DMAP Comment : Dead Code Detected - The Following Method has no reference getCreated
		return created;
	}

	public void setCreated(Date created) { // DMAP Comment : Dead Code Detected - The Following Method has no reference setCreated
		this.created = created;
	}

	@Column(name="UPDATE_BY")
	public String getLastUpdBy() { // DMAP Comment : Dead Code Detected - The Following Method has no reference getLastUpdBy
		return lastUpdBy;
	}

	public void setLastUpdBy(String lastUpdBy) { // DMAP Comment : Dead Code Detected - The Following Method has no reference setLastUpdBy
		this.lastUpdBy = lastUpdBy;
	}
		
	@Column(name="UPDATE_DATE")
	public Date getLastUpd() { // DMAP Comment : Dead Code Detected - The Following Method has no reference getLastUpd
		return lastUpd;
	}
		
	public void setLastUpd(Date lastUpd) { // DMAP Comment : Dead Code Detected - The Following Method has no reference setLastUpd
		this.lastUpd = lastUpd;
	}
	
	public String getRowId() { // DMAP Comment : Dead Code Detected - The Following Method has no reference getRowId
		return rowId;
	}

	public void setRowId(String rowId) { // DMAP Comment : Dead Code Detected - The Following Method has no reference setRowId
		this.rowId = rowId;
	}

	public Long getVersion() { // DMAP Comment : Dead Code Detected - The Following Method has no reference getVersion
		return version;
	}

	public void setVersion(Long version) { // DMAP Comment : Dead Code Detected - The Following Method has no reference setVersion
		this.version = version;
	}

	public IpUrInterfaceGatewayId getId() { // DMAP Comment : Dead Code Detected - The Following Method has no reference getId
		return id;
	}

	public void setId(IpUrInterfaceGatewayId id) { // DMAP Comment : Dead Code Detected - The Following Method has no reference setId
		this.id = id;
	}

	public String getIpAddress() { // DMAP Comment : Dead Code Detected - The Following Method has no reference getIpAddress
		return ipAddress;
	}

	public void setIpAddress(String ipAddress) { // DMAP Comment : Dead Code Detected - The Following Method has no reference setIpAddress
		this.ipAddress = ipAddress;
	}

	public String getMask() { // DMAP Comment : Dead Code Detected - The Following Method has no reference getMask
		return mask;
	}

	public void setMask(String mask) { // DMAP Comment : Dead Code Detected - The Following Method has no reference setMask
		this.mask = mask;
	}

	public String getNetworkTypeId() { // DMAP Comment : Dead Code Detected - The Following Method has no reference getNetworkTypeId
		return networkTypeId;
	}

	public void setNetworkTypeId(String networkTypeId) { // DMAP Comment : Dead Code Detected - The Following Method has no reference setNetworkTypeId
		this.networkTypeId = networkTypeId;
	}

	public String getNetworkTypeDesc() { // DMAP Comment : Dead Code Detected - The Following Method has no reference getNetworkTypeDesc
		return networkTypeDesc;
	}

	public void setNetworkTypeDesc(String networkTypeDesc) { // DMAP Comment : Dead Code Detected - The Following Method has no reference setNetworkTypeDesc
		this.networkTypeDesc = networkTypeDesc;
	}

	public String getLocationName() { // DMAP Comment : Dead Code Detected - The Following Method has no reference getLocationName
		return locationName;
	}

	public void setLocationName(String locationName) { // DMAP Comment : Dead Code Detected - The Following Method has no reference setLocationName
		this.locationName = locationName;
	}

	public String getReqVlanId() { // DMAP Comment : Dead Code Detected - The Following Method has no reference getReqVlanId
		return reqVlanId;
	}

	public void setReqVlanId(String reqVlanId) { // DMAP Comment : Dead Code Detected - The Following Method has no reference setReqVlanId
		this.reqVlanId = reqVlanId;
	}

	

	public String getReqDesc() { // DMAP Comment : Dead Code Detected - The Following Method has no reference getReqDesc
		return reqDesc;
	}

	public void setReqDesc(String reqDesc) { // DMAP Comment : Dead Code Detected - The Following Method has no reference setReqDesc
		this.reqDesc = reqDesc;
	}

	public String getIsAssign() { // DMAP Comment : Dead Code Detected - The Following Method has no reference getIsAssign
		return isAssign;
	}

	public void setIsAssign(String isAssign) { // DMAP Comment : Dead Code Detected - The Following Method has no reference setIsAssign
		this.isAssign = isAssign;
	}

	public String getIsImpact() { // DMAP Comment : Dead Code Detected - The Following Method has no reference getIsImpact
		return isImpact;
	}

	public void setIsImpact(String isImpact) { // DMAP Comment : Dead Code Detected - The Following Method has no reference setIsImpact
		this.isImpact = isImpact;
	}

	public String getSysOwnerRemark() { // DMAP Comment : Dead Code Detected - The Following Method has no reference getSysOwnerRemark
		return sysOwnerRemark;
	}

	public void setSysOwnerRemark(String sysOwnerRemark) { // DMAP Comment : Dead Code Detected - The Following Method has no reference setSysOwnerRemark
		this.sysOwnerRemark = sysOwnerRemark;
	}

	public String getPmRemark() { // DMAP Comment : Dead Code Detected - The Following Method has no reference getPmRemark
		return pmRemark;
	}

	public void setPmRemark(String pmRemark) { // DMAP Comment : Dead Code Detected - The Following Method has no reference setPmRemark
		this.pmRemark = pmRemark;
	}

	public String getActmRemark() { // DMAP Comment : Dead Code Detected - The Following Method has no reference getActmRemark
		return actmRemark;
	}

	public void setActmRemark(String actmRemark) { // DMAP Comment : Dead Code Detected - The Following Method has no reference setActmRemark
		this.actmRemark = actmRemark;
	}

	public IpUrStatus getSubUrStatus() { // DMAP Comment : Dead Code Detected - The Following Method has no reference getSubUrStatus
		return subUrStatus;
	}

	public void setSubUrStatus(IpUrStatus subUrStatus) { // DMAP Comment : Dead Code Detected - The Following Method has no reference setSubUrStatus
		this.subUrStatus = subUrStatus;
	}

	public String getSubUrStatusTxt() { // DMAP Comment : Dead Code Detected - The Following Method has no reference getSubUrStatusTxt
		return subUrStatusTxt;
	}

	public void setSubUrStatusTxt(String subUrStatusTxt) { // DMAP Comment : Dead Code Detected - The Following Method has no reference setSubUrStatusTxt
		this.subUrStatusTxt = subUrStatusTxt;
	}

	public String getUrType() { // DMAP Comment : Dead Code Detected - The Following Method has no reference getUrType
		return urType;
	}

	public void setUrType(String urType) { // DMAP Comment : Dead Code Detected - The Following Method has no reference setUrType
		this.urType = urType;
	}

	public String getIsApprove() { // DMAP Comment : Dead Code Detected - The Following Method has no reference getIsApprove
		return isApprove;
	}

	public void setIsApprove(String isApprove) { // DMAP Comment : Dead Code Detected - The Following Method has no reference setIsApprove
		this.isApprove = isApprove;
	}

	public String getIsReject() { // DMAP Comment : Dead Code Detected - The Following Method has no reference getIsReject
		return isReject;
	}

	public void setIsReject(String isReject) { // DMAP Comment : Dead Code Detected - The Following Method has no reference setIsReject
		this.isReject = isReject;
	}
	
	public boolean getIsSelected() { // DMAP Comment : Dead Code Detected - The Following Method has no reference getIsSelected
		return isSelected;
	}

	public void setIsSelected(boolean isSelected) { // DMAP Comment : Dead Code Detected - The Following Method has no reference setIsSelected
		this.isSelected = isSelected;
	}

	public String getChangeType() { // DMAP Comment : Dead Code Detected - The Following Method has no reference getChangeType
		return changeType;
	}

	public void setChangeType(String changeType) { // DMAP Comment : Dead Code Detected - The Following Method has no reference setChangeType
		this.changeType = changeType;
	}

	public void setSelected(boolean isSelected) { // DMAP Comment : Dead Code Detected - The Following Method has no reference setSelected
		this.isSelected = isSelected;
	}

	public String getIsTnp() { // DMAP Comment : Dead Code Detected - The Following Method has no reference getIsTnp
		return isTnp;
	}

	public void setIsTnp(String isTnp) { // DMAP Comment : Dead Code Detected - The Following Method has no reference setIsTnp
		this.isTnp = isTnp;
	}
	
    public String getTeamRemark() { // DMAP Comment : Dead Code Detected - The Following Method has no reference getTeamRemark
		return teamRemark;
	}

	public void setTeamRemark(String teamRemark) { // DMAP Comment : Dead Code Detected - The Following Method has no reference setTeamRemark
		this.teamRemark = teamRemark;
	}

	@Override
    public Object clone() throws CloneNotSupportedException
    {
    	IpUrInterfaceGateway another = (IpUrInterfaceGateway) super.clone();
        //? take care of any deep copies to be made here
        return another;
    }
	

}


