package th.co.ais.ipfm.domain1;
// Generated 27 Ê.¤. 2553, 17:13:55 by Hibernate Tools 3.2.1.GA


import java.math.BigDecimal;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.Locale;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Transient;
import javax.persistence.Version;

import org.hibernate.annotations.Formula;
import org.hibernate.annotations.GenericGenerator;

import th.co.ais.ipfm.domain.MasterDomain;

/**
 * IpUrActionHistory generated by hbm2java
 */
@Entity
@Table(name="IP_UR_ACTION_HISTORY"
)
public class IpUrActionHistory  extends MasterDomain implements java.io.Serializable ,Cloneable{


     private String rowId;
     private Long version;
     private String urNo;
     private String urType;
     private String subUrNo;
     private String subUrType;
     private BigDecimal actionSeq;
     private String reqestUserId;
     private String reqestUser;
     private Date reqestDate;
     private String actionUserId;
     private String actionUser;
     private String actionName;
     private String urStatus;
     private String actionRemark;
     private String userRemark;
     private Date olaDate;
     private Date slaDate;
     private String overOla;
     private String overSla;
     private String subject;
//     private String trunkNo;
//     private String piType;

    public IpUrActionHistory() {
    }

	
    public IpUrActionHistory(String rowId) {
        this.rowId = rowId;
    }
    public IpUrActionHistory(String rowId, String urNo, String urType, String subUrNo, String subUrType, BigDecimal actionSeq, String reqestUserId, String reqestUser, Date reqestDate, String actionUserId, String actionUser, String actionName, String urStatus, String actionRemark, String userRemark, Date olaDate, Date slaDate, String overOla, String overSla, String createBy, Date createDate, String updateBy, Date updateDate) {
       this.rowId = rowId;
       this.urNo = urNo;
       this.urType = urType;
       this.subUrNo = subUrNo;
       this.subUrType = subUrType;
       this.actionSeq = actionSeq;
       this.reqestUserId = reqestUserId;
       this.reqestUser = reqestUser;
       this.reqestDate = reqestDate;
       this.actionUserId = actionUserId;
       this.actionUser = actionUser;
       this.actionName = actionName;
       this.urStatus = urStatus;
       this.actionRemark = actionRemark;
       this.userRemark = userRemark;
       this.olaDate = olaDate;
       this.slaDate = slaDate;
       this.overOla = overOla;
       this.overSla = overSla;
    }
    
    public IpUrActionHistory(IpUrAction action){
		this.setUrNo(action.getUrNo());
		this.setUrType(action.getUrType());
		this.setSubUrNo(action.getSubUrNo());
		this.setSubUrType(action.getSubUrType());
		this.setActionSeq(action.getActionSeq());
		this.setReqestUserId(action.getReqestUserId());							
		this.setReqestUser(action.getReqestUser());							
		this.setReqestDate(action.getReqestDate());							
		this.setActionUserId(action.getActionUserId());							
		this.setActionUser(action.getActionUser());					
		this.setActionName(action.getActionName());							
		this.setUrStatus(action.getUrStatus());							
		this.setActionRemark(action.getActionRemark());							
		this.setUserRemark(action.getUserRemark());							
		this.setOlaDate(action.getOlaDate());							
		this.setSlaDate(action.getSlaDate());							
		this.setOverOla(null);
		this.setOverSla(null);
		this.setCreatedBy(action.getCreatedBy());
		this.setCreated(action.getCreated());						
		this.setLastUpdBy(action.getLastUpdBy());
		this.setLastUpd(action.getLastUpd());
		this.setSubject(action.getSubject());
	}
   
    @Id 
  	@GeneratedValue(generator="system-uuid")
	@GenericGenerator(name="system-uuid", strategy = "uuid")
    @Column(name="ROW_ID", unique=true, nullable=false, length=50)
    public String getRowId() { // DMAP Comment : Dead Code Detected - The Following Method has no reference getRowId
        return this.rowId;
    }
    
    public void setRowId(String rowId) { // DMAP Comment : Dead Code Detected - The Following Method has no reference setRowId
        this.rowId = rowId;
    }
    @Version
    @Column(name="VERSION", precision=10, scale=0)
    public Long getVersion() { // DMAP Comment : Dead Code Detected - The Following Method has no reference getVersion
        return this.version;
    }
    
    public void setVersion(Long version) { // DMAP Comment : Dead Code Detected - The Following Method has no reference setVersion
        this.version = version;
    }
    
    @Column(name="UR_NO", length=30)
    public String getUrNo() { // DMAP Comment : Dead Code Detected - The Following Method has no reference getUrNo
        return this.urNo;
    }
    
    public void setUrNo(String urNo) { // DMAP Comment : Dead Code Detected - The Following Method has no reference setUrNo
        this.urNo = urNo;
    }
    
    @Column(name="UR_TYPE", length=5)
    public String getUrType() { // DMAP Comment : Dead Code Detected - The Following Method has no reference getUrType
        return this.urType;
    }
    
    public void setUrType(String urType) { // DMAP Comment : Dead Code Detected - The Following Method has no reference setUrType
        this.urType = urType;
    }
    
    @Column(name="SUB_UR_NO", length=10)
    public String getSubUrNo() { // DMAP Comment : Dead Code Detected - The Following Method has no reference getSubUrNo
        return this.subUrNo;
    }
    
    public void setSubUrNo(String subUrNo) { // DMAP Comment : Dead Code Detected - The Following Method has no reference setSubUrNo
        this.subUrNo = subUrNo;
    }
    
    @Column(name="SUB_UR_TYPE", length=5)
    public String getSubUrType() { // DMAP Comment : Dead Code Detected - The Following Method has no reference getSubUrType
        return this.subUrType;
    }
    
    public void setSubUrType(String subUrType) { // DMAP Comment : Dead Code Detected - The Following Method has no reference setSubUrType
        this.subUrType = subUrType;
    }
    
    @Column(name="ACTION_SEQ", precision=22, scale=0)
    public BigDecimal getActionSeq() { // DMAP Comment : Dead Code Detected - The Following Method has no reference getActionSeq
        return this.actionSeq;
    }
    
    public void setActionSeq(BigDecimal actionSeq) { // DMAP Comment : Dead Code Detected - The Following Method has no reference setActionSeq
        this.actionSeq = actionSeq;
    }
    
    @Column(name="REQ_USER_ID", length=20)
    public String getReqestUserId() { // DMAP Comment : Dead Code Detected - The Following Method has no reference getReqestUserId
        return this.reqestUserId;
    }
    
    public void setReqestUserId(String reqestUserId) { // DMAP Comment : Dead Code Detected - The Following Method has no reference setReqestUserId
        this.reqestUserId = reqestUserId;
    }
    
    @Column(name="REQ_USER", length=100)
    public String getReqestUser() { // DMAP Comment : Dead Code Detected - The Following Method has no reference getReqestUser
        return this.reqestUser;
    }
    
    public void setReqestUser(String reqestUser) { // DMAP Comment : Dead Code Detected - The Following Method has no reference setReqestUser
        this.reqestUser = reqestUser;
    }

    @Column(name="REQ_DATE")
    public Date getReqestDate() { // DMAP Comment : Dead Code Detected - The Following Method has no reference getReqestDate
        return this.reqestDate;
    }
    
    public void setReqestDate(Date reqestDate) { // DMAP Comment : Dead Code Detected - The Following Method has no reference setReqestDate
        this.reqestDate = reqestDate;
    }
    
    @Column(name="ACTION_USER_ID", length=100)
    public String getActionUserId() { // DMAP Comment : Dead Code Detected - The Following Method has no reference getActionUserId
        return this.actionUserId;
    }
    
    public void setActionUserId(String actionUserId) { // DMAP Comment : Dead Code Detected - The Following Method has no reference setActionUserId
        this.actionUserId = actionUserId;
    }
    @Transient
    public String getActionUserDesc() {
		String str="";
		if (actionUser!=null && actionUser.trim().length()>0){
			if (actionUser.lastIndexOf(";")==actionUser.trim().length()-1){
				str = actionUser.substring(0, actionUser.length()-1).replaceAll(";", ", <BR>");
			}else{
				str = actionUser.replaceAll(";", ", <BR>");
			}
		}
		return str;
	}
    @Transient
    public String getActionUserSubstr() { // DMAP Comment : Dead Code Detected - The Following Method has no reference getActionUserSubstr
		String str="";
		if (getActionUserDesc()!=null && getActionUserDesc().trim().length()>0) 
			if(getActionUserDesc().trim().length()>30) str = getActionUserDesc().substring(0, 30)+"...";
			else str = getActionUserDesc();
		return str;
	}
    @Column(name="ACTION_USER", length=1000)
    public String getActionUser() { // DMAP Comment : Dead Code Detected - The Following Method has no reference getActionUser
        return this.actionUser;
    }
    
    public void setActionUser(String actionUser) { // DMAP Comment : Dead Code Detected - The Following Method has no reference setActionUser
        this.actionUser = actionUser;
    }
    
    @Column(name="ACTION_NAME", length=1000)
    public String getActionName() { // DMAP Comment : Dead Code Detected - The Following Method has no reference getActionName
        return this.actionName;
    }
    
    public void setActionName(String actionName) { // DMAP Comment : Dead Code Detected - The Following Method has no reference setActionName
        this.actionName = actionName;
    }
    
    @Column(name="UR_STATUS", length=20)
    public String getUrStatus() { // DMAP Comment : Dead Code Detected - The Following Method has no reference getUrStatus
        return this.urStatus;
    }
    
    public void setUrStatus(String urStatus) { // DMAP Comment : Dead Code Detected - The Following Method has no reference setUrStatus
        this.urStatus = urStatus;
    }
    @Transient
    public String getActionRemarkDesc(){ // DMAP Comment : Dead Code Detected - The Following Method has no reference getActionRemarkDesc
    	String str = "";
    	if (getActionRemark() ==null || getActionRemark().trim().length()==0) {
    		str = "Completed";
    	}else{
    		str = getActionRemark();
    	}
    	return str;
    }
    
    @Column(name="ACTION_REMARK", length=1000)
    public String getActionRemark() {
        return this.actionRemark;
    }
    
    public void setActionRemark(String actionRemark) { // DMAP Comment : Dead Code Detected - The Following Method has no reference setActionRemark
        this.actionRemark = actionRemark;
    }
    
    @Column(name="USER_REMARK", length=1000)
    public String getUserRemark() { // DMAP Comment : Dead Code Detected - The Following Method has no reference getUserRemark
        return this.userRemark;
    }
    
    public void setUserRemark(String userRemark) { // DMAP Comment : Dead Code Detected - The Following Method has no reference setUserRemark
        this.userRemark = userRemark;
    }
    @Temporal(TemporalType.DATE)
    @Column(name="OLA_DATE", length=7)
    public Date getOlaDate() { // DMAP Comment : Dead Code Detected - The Following Method has no reference getOlaDate
        return this.olaDate;
    }
    
    public void setOlaDate(Date olaDate) { // DMAP Comment : Dead Code Detected - The Following Method has no reference setOlaDate
        this.olaDate = olaDate;
    }
    @Temporal(TemporalType.DATE)
    @Column(name="SLA_DATE", length=7)
    public Date getSlaDate() { // DMAP Comment : Dead Code Detected - The Following Method has no reference getSlaDate
        return this.slaDate;
    }
    
    public void setSlaDate(Date slaDate) { // DMAP Comment : Dead Code Detected - The Following Method has no reference setSlaDate
        this.slaDate = slaDate;
    }
    
    @Column(name="OVER_OLA", length=2)
    public String getOverOla() { // DMAP Comment : Dead Code Detected - The Following Method has no reference getOverOla
        return this.overOla;
    }
    
    public void setOverOla(String overOla) { // DMAP Comment : Dead Code Detected - The Following Method has no reference setOverOla
        this.overOla = overOla;
    }
    
    @Column(name="OVER_SLA", length=2)
    public String getOverSla() { // DMAP Comment : Dead Code Detected - The Following Method has no reference getOverSla
        return this.overSla;
    }
    
    public void setOverSla(String overSla) { // DMAP Comment : Dead Code Detected - The Following Method has no reference setOverSla
        this.overSla = overSla;
    }
	@Column(name="CREATE_BY")
	public String getCreatedBy() { // DMAP Comment : Dead Code Detected - The Following Method has no reference getCreatedBy
		return createdBy;
	}

	public void setCreatedBy(String createdBy) { // DMAP Comment : Dead Code Detected - The Following Method has no reference setCreatedBy
		this.createdBy = createdBy;
	}

	@Column(name="CREATE_DATE")
	public Date getCreated() { // DMAP Comment : Dead Code Detected - The Following Method has no reference getCreated
		return created;
	}

	public void setCreated(Date created) { // DMAP Comment : Dead Code Detected - The Following Method has no reference setCreated
		this.created = created;
	}

	@Column(name="UPDATE_BY")
	public String getLastUpdBy() { // DMAP Comment : Dead Code Detected - The Following Method has no reference getLastUpdBy
		return lastUpdBy;
	}

	public void setLastUpdBy(String lastUpdBy) { // DMAP Comment : Dead Code Detected - The Following Method has no reference setLastUpdBy
		this.lastUpdBy = lastUpdBy;
	}
	
	@Column(name="UPDATE_DATE")
	public Date getLastUpd() {
		return lastUpd;
	}
	
	public void setLastUpd(Date lastUpd) { // DMAP Comment : Dead Code Detected - The Following Method has no reference setLastUpd
		this.lastUpd = lastUpd;
	}
	@Transient
	public String getLastUpdDes(){ // DMAP Comment : Dead Code Detected - The Following Method has no reference getLastUpdDes
		DateFormat dfm1 = new SimpleDateFormat("dd/MM/yyyy HH:mm:ss",new Locale("en","EN"));
		return dfm1.format(getLastUpd());
	}
	@Column(name="SUBJECT")
	public String getSubject() { // DMAP Comment : Dead Code Detected - The Following Method has no reference getSubject
		return subject;
	}

	public void setSubject(String subject) { // DMAP Comment : Dead Code Detected - The Following Method has no reference setSubject
		this.subject = subject;
	}


	@Override
    public Object clone() throws CloneNotSupportedException    {
		IpUrActionHistory another = (IpUrActionHistory) super.clone();
        return another;
    }

//	@Formula("(select i.trunk_No from IP_UR_PHYSICAL_INTERFACE i where i.sub_ur_no = sub_ur_no and i.ur_no = ur_no)")
//	public String getTrunkNo() {
//		return trunkNo;
//	}
//
//	public void setTrunkNo(String trunkNo) {
//		this.trunkNo = trunkNo;
//	}
//
//	@Formula("(select i.pi_type from IP_UR_PHYSICAL_INTERFACE i where i.sub_ur_no = sub_ur_no and i.ur_no = ur_no)")
//	public String getPiType() {
//		return piType;
//	}
//
//	public void setPiType(String piType) {
//		this.piType = piType;
//	}

}


