package th.co.ais.ipfm.domain1;
// Generated 27 Ê.¤. 2553, 17:13:55 by Hibernate Tools 3.2.1.GA


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * IpUrAccessListTnpId generated by hbm2java
 */
@Embeddable
public class IpUrAccessListTnpId  implements java.io.Serializable {


     private String urNo;
     private String subUrNo;

    public IpUrAccessListTnpId() {
    }

    public IpUrAccessListTnpId(String urNo, String subUrNo) {
       this.urNo = urNo;
       this.subUrNo = subUrNo;
    }
   

    @Column(name="UR_NO", nullable=false, length=30)
    public String getUrNo() {
        return this.urNo;
    }
    
    public void setUrNo(String urNo) {
        this.urNo = urNo;
    }

    @Column(name="SUB_UR_NO", nullable=false, length=10)
    public String getSubUrNo() {
        return this.subUrNo;
    }
    
    public void setSubUrNo(String subUrNo) {
        this.subUrNo = subUrNo;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof IpUrAccessListTnpId) ) return false;
		 IpUrAccessListTnpId castOther = ( IpUrAccessListTnpId ) other; 
         
		 return ( (this.getUrNo()==castOther.getUrNo()) || ( this.getUrNo()!=null && castOther.getUrNo()!=null && this.getUrNo().equals(castOther.getUrNo()) ) )
 && ( (this.getSubUrNo()==castOther.getSubUrNo()) || ( this.getSubUrNo()!=null && castOther.getSubUrNo()!=null && this.getSubUrNo().equals(castOther.getSubUrNo()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getUrNo() == null ? 0 : this.getUrNo().hashCode() );
         result = 37 * result + ( getSubUrNo() == null ? 0 : this.getSubUrNo().hashCode() );
         return result;
   }   


}


