package th.co.ais.ipfm.domain1;
// Generated 27 �.�. 2553, 17:13:55 by Hibernate Tools 3.2.1.GA


import java.util.Date;

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.JoinColumn;
import javax.persistence.JoinColumns;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Transient;
import javax.persistence.UniqueConstraint;
import javax.persistence.Version;

import org.hibernate.annotations.GenericGenerator;

import th.co.ais.ipfm.domain.MasterDomain;

/**
 * IpUrInterfaceGateway generated by hbm2java
 */
@Entity
@Table(name="IP_UR_INTERFACE_GATEWAY"
    , uniqueConstraints = @UniqueConstraint(columnNames="ROW_ID") 
)
public class IpUrInterfaceGateway extends MasterDomain  implements java.io.Serializable , Cloneable {

	@EmbeddedId
    @AttributeOverrides( {
        @AttributeOverride(name="urNo", column=@Column(name="UR_NO", nullable=false, length=20) ), 
        @AttributeOverride(name="subUrNo", column=@Column(name="SUB_UR_NO", nullable=false, length=10) ) } )	
    private IpUrInterfaceGatewayId id;

	@Column(name="IP_ADDRESS", length=50)
	private String ipAddress; 
	
	@Column(name="MASK", length=50)
	private String mask;
	
	@Column(name="NETWORK_TYPE_ID", length=50)
	private String networkTypeId; 
	
	@Column(name="NETWORK_TYPE_DESC", length=1000)
	private String networkTypeDesc; 
	
	@Column(name="LOCATION_NAME", length=200)
	private String locationName; 
	
	@Column(name="REQ_VLAN_ID", length=50)
	private String reqVlanId; 
	
	@Column(name="REQ_DESC", length=1000)
	private String reqDesc;
	
	@Column(name="IS_ASSIGN", length=10)
	private String isAssign;
	
	@Column(name="IS_IMPACT", length=10)
	private String isImpact;
	
	@Column(name="SYS_OWNER_REMARK", length=1000)
	private String sysOwnerRemark; 
	
	@Column(name="PM_REMARK", length=1000)
	private String pmRemark; 
	
	@Column(name="TEAM_REMARK", length=1000)
	private String teamRemark; 
	
	@Column(name="ACTM_REMARK", length=1000)
	private String actmRemark; 
		
	@ManyToOne(optional = false, fetch = FetchType.LAZY)
    @JoinColumns( {
    	@JoinColumn(name = "SUB_UR_STATUS", referencedColumnName = "SUB_UR_STATUS_ID", nullable = true, insertable=false, updatable=false),
    	@JoinColumn(name = "UR_TYPE", referencedColumnName = "UR_TYPE" , nullable = true, insertable=false, updatable=false)
    })
    private IpUrStatus subUrStatus;
	
	@Column(name="SUB_UR_STATUS", length=20)
    private String subUrStatusTxt;
    
    @Column(name="UR_TYPE", length=5)
    private String urType; 
    
	@Column(name="IS_TNP", length=2)
	private String isTnp;
	
    @GeneratedValue(generator="system-uuid")
	@GenericGenerator(name="system-uuid", strategy = "uuid")
	@Column(name="ROW_ID", unique=true, length=50)
    private String rowId;
    
	@Column(name="CHANGE_TYPE", length=2)
	private String changeType;
    
	@Transient
	private String isApprove;
	
	@Transient
	private String isReject;
	
	@Transient
	private boolean isSelected;
	
	@Transient
	private boolean impactSelected;
	
//	public boolean isImpactSelected() {
//		if (getIsImpact()==null || getIsImpact().equalsIgnoreCase("N"))
//			return false;
//		else
//			return true;
//	}
	public boolean isImpactSelected() {
		return impactSelected;
	}
    public void setImpactSelected(boolean impactSelected) {
		this.impactSelected = impactSelected;
	}
    
    @Version
    @Column(name="VERSION", precision=10, scale=0)
    private Long version;
    
    @Column(name="CREATE_BY")
	public String getCreatedBy() {
		return createdBy;
	}

	public void setCreatedBy(String createdBy) {
		this.createdBy = createdBy;
	}

	@Column(name="CREATE_DATE")
	public Date getCreated() {
		return created;
	}

	public void setCreated(Date created) {
		this.created = created;
	}

	@Column(name="UPDATE_BY")
	public String getLastUpdBy() {
		return lastUpdBy;
	}

	public void setLastUpdBy(String lastUpdBy) {
		this.lastUpdBy = lastUpdBy;
	}
		
	@Column(name="UPDATE_DATE")
	public Date getLastUpd() {
		return lastUpd;
	}
		
	public void setLastUpd(Date lastUpd) {
		this.lastUpd = lastUpd;
	}
	
	public String getRowId() {
		return rowId;
	}

	public void setRowId(String rowId) {
		this.rowId = rowId;
	}

	public Long getVersion() {
		return version;
	}

	public void setVersion(Long version) {
		this.version = version;
	}

	public IpUrInterfaceGatewayId getId() {
		return id;
	}

	public void setId(IpUrInterfaceGatewayId id) {
		this.id = id;
	}

	public String getIpAddress() {
		return ipAddress;
	}

	public void setIpAddress(String ipAddress) {
		this.ipAddress = ipAddress;
	}

	public String getMask() {
		return mask;
	}

	public void setMask(String mask) {
		this.mask = mask;
	}

	public String getNetworkTypeId() {
		return networkTypeId;
	}

	public void setNetworkTypeId(String networkTypeId) {
		this.networkTypeId = networkTypeId;
	}

	public String getNetworkTypeDesc() {
		return networkTypeDesc;
	}

	public void setNetworkTypeDesc(String networkTypeDesc) {
		this.networkTypeDesc = networkTypeDesc;
	}

	public String getLocationName() {
		return locationName;
	}

	public void setLocationName(String locationName) {
		this.locationName = locationName;
	}

	public String getReqVlanId() {
		return reqVlanId;
	}

	public void setReqVlanId(String reqVlanId) {
		this.reqVlanId = reqVlanId;
	}

	

	public String getReqDesc() {
		return reqDesc;
	}

	public void setReqDesc(String reqDesc) {
		this.reqDesc = reqDesc;
	}

	public String getIsAssign() {
		return isAssign;
	}

	public void setIsAssign(String isAssign) {
		this.isAssign = isAssign;
	}

	public String getIsImpact() {
		return isImpact;
	}

	public void setIsImpact(String isImpact) {
		this.isImpact = isImpact;
	}

	public String getSysOwnerRemark() {
		return sysOwnerRemark;
	}

	public void setSysOwnerRemark(String sysOwnerRemark) {
		this.sysOwnerRemark = sysOwnerRemark;
	}

	public String getPmRemark() {
		return pmRemark;
	}

	public void setPmRemark(String pmRemark) {
		this.pmRemark = pmRemark;
	}

	public String getActmRemark() {
		return actmRemark;
	}

	public void setActmRemark(String actmRemark) {
		this.actmRemark = actmRemark;
	}

	public IpUrStatus getSubUrStatus() {
		return subUrStatus;
	}

	public void setSubUrStatus(IpUrStatus subUrStatus) {
		this.subUrStatus = subUrStatus;
	}

	public String getSubUrStatusTxt() {
		return subUrStatusTxt;
	}

	public void setSubUrStatusTxt(String subUrStatusTxt) {
		this.subUrStatusTxt = subUrStatusTxt;
	}

	public String getUrType() {
		return urType;
	}

	public void setUrType(String urType) {
		this.urType = urType;
	}

	public String getIsApprove() {
		return isApprove;
	}

	public void setIsApprove(String isApprove) {
		this.isApprove = isApprove;
	}

	public String getIsReject() {
		return isReject;
	}

	public void setIsReject(String isReject) {
		this.isReject = isReject;
	}
	
	public boolean getIsSelected() {
		return isSelected;
	}

	public void setIsSelected(boolean isSelected) {
		this.isSelected = isSelected;
	}

	public String getChangeType() {
		return changeType;
	}

	public void setChangeType(String changeType) {
		this.changeType = changeType;
	}

	public void setSelected(boolean isSelected) {
		this.isSelected = isSelected;
	}

	public String getIsTnp() {
		return isTnp;
	}

	public void setIsTnp(String isTnp) {
		this.isTnp = isTnp;
	}
	
    public String getTeamRemark() {
		return teamRemark;
	}

	public void setTeamRemark(String teamRemark) {
		this.teamRemark = teamRemark;
	}

	@Override
    public Object clone() throws CloneNotSupportedException
    {
    	IpUrInterfaceGateway another = (IpUrInterfaceGateway) super.clone();
        //? take care of any deep copies to be made here
        return another;
    }
	

}


