package th.co.ais.ipfm.domain1;
// Generated 27 �.�. 2553, 17:13:55 by Hibernate Tools 3.2.1.GA


import java.util.Date;
import java.util.List;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;
import javax.persistence.Version;

import org.hibernate.annotations.GenericGenerator;

import th.co.ais.ipfm.domain.MasterDomain;

/**
 * IpUrNwConfig generated by hbm2java
 */
@Entity
@Table(name="IP_UR_NW_CONFIG"
    , uniqueConstraints = @UniqueConstraint(columnNames="ROW_ID") 
)
public class IpUrNwConfig  extends MasterDomain implements java.io.Serializable {
	

	private String urNo;
	private String reqUserId;
	private String reqUserName;
	private String reqEmail;
	private String reqMobile;
	private String reqTel;
	private String reqDept;
	private String reqSection;  
	private String reqPosition;
	private String reqTeamId;    
	private String reqTeamName;
	private String reqSubject;
	private String reqObjective;
	private String reqRequirement;
	private String isPeriod;    
	private Date periodStart;
	private Date periodEnd;
	private String reqFor;
	private String isAttach;
	private Date reqDate;
	private String mrgRemark;
	private String urStatusTxt;
	private String urStatusName;
    private String urType;
	private String rowId;
	private Long version;
	private String fwSts; 
	private String alSts; 
	private String atSts; 
	private String piSts; 
	private String igSts; 
	private String rtSts; 
	private String f5Sts;
	private String overSla;
	private String isImpact;
	private String tnpStatus;
	private String approveManager;
	
	List<IpUrFirewall> listFirewall;
	List<IpUrAccessListCdn> listAccessListCdn;
	List<IpUrAccessListTnp> listAccessListTnp;
	List<IpUrPhysicalInterface> listPhyInterface;
	List<IpUrInterfaceGateway> listIntfGateway;
	List<IpUrRouting> listRouting;
	List<IpUrF5> listF5;

    public IpUrNwConfig() {
    }

	
    public IpUrNwConfig(String urNo) {
        this.urNo = urNo;
    }

	@Id 
	@Column(name="UR_NO")
	public String getUrNo() {
		return urNo;
	}

	public void setUrNo(String urNo) {
		this.urNo = urNo;
	}

	@Column(name="REQ_USER_ID")
	public String getReqUserId() {
		return reqUserId;
	}

	public void setReqUserId(String reqUserId) {
		this.reqUserId = reqUserId;
	}

	@Column(name="REQ_USER_NAME")
	public String getReqUserName() {
		return reqUserName;
	}

	public void setReqUserName(String reqUserName) {
		this.reqUserName = reqUserName;
	}

	@Column(name="REQ_EMAIL")
	public String getReqEmail() {
		return reqEmail;
	}

	public void setReqEmail(String reqEmail) {
		this.reqEmail = reqEmail;
	}

	@Column(name="REQ_MOBILE")
	public String getReqMobile() {
		return reqMobile;
	}

	public void setReqMobile(String reqMobile) {
		this.reqMobile = reqMobile;
	}

	@Column(name="REQ_TEL")
	public String getReqTel() {
		return reqTel;
	}

	public void setReqTel(String reqTel) {
		this.reqTel = reqTel;
	}

	@Column(name="REQ_DEPT")
	public String getReqDept() {
		return reqDept;
	}

	public void setReqDept(String reqDept) {
		this.reqDept = reqDept;
	}

	@Column(name="REQ_SECTION")
	public String getReqSection() {
		return reqSection;
	}

	public void setReqSection(String reqSection) {
		this.reqSection = reqSection;
	}

	@Column(name="REQ_POSITION")
	public String getReqPosition() {
		return reqPosition;
	}

	public void setReqPosition(String reqPosition) {
		this.reqPosition = reqPosition;
	}

	@Column(name="REQ_TEAM_ID")
	public String getReqTeamId() {
		return reqTeamId;
	}

	public void setReqTeamId(String reqTeamId) {
		this.reqTeamId = reqTeamId;
	}

	@Column(name="REQ_TEAM_NAME")
	public String getReqTeamName() {
		return reqTeamName;
	}

	public void setReqTeamName(String reqTeamName) {
		this.reqTeamName = reqTeamName;
	}

	@Column(name="REQ_SUBJECT")
	public String getReqSubject() {
		return reqSubject;
	}

	public void setReqSubject(String reqSubject) {
		this.reqSubject = reqSubject;
	}

	@Column(name="REQ_OBJECTIVE")
	public String getReqObjective() {
		return reqObjective;
	}

	public void setReqObjective(String reqObjective) {
		this.reqObjective = reqObjective;
	}

	@Column(name="REQ_REQUIREMENT")
	public String getReqRequirement() {
		return reqRequirement;
	}

	public void setReqRequirement(String reqRequirement) {
		this.reqRequirement = reqRequirement;
	}

	@Column(name="IS_PERIOD")
	public String getIsPeriod() {
		return isPeriod;
	}

	public void setIsPeriod(String isPeriod) {
		this.isPeriod = isPeriod;
	}
	@Column(name="IS_ATTACH")
	public String getIsAttach() {
		return isAttach;
	}

	public void setIsAttach(String isAttach) {
		this.isAttach = isAttach;
	}

	@Temporal(TemporalType.DATE)
    @Column(name="REQ_DATE")
	public Date getReqDate() {
		return reqDate;
	}

	public void setReqDate(Date reqDate) {
		this.reqDate = reqDate;
	}

	@Column(name="MRG_REMARK")
	public String getMrgRemark() {
		return mrgRemark;
	}

	public void setMrgRemark(String mrgRemark) {
		this.mrgRemark = mrgRemark;
	}
	
	@GeneratedValue(generator="system-uuid")
	@GenericGenerator(name="system-uuid", strategy = "uuid")
	@Column(name="ROW_ID", unique=true, length=50)
	public String getRowId() {
		return rowId;
	}

	public void setRowId(String rowId) {
		this.rowId = rowId;
	}

	@Version
    @Column(name="VERSION", precision=10, scale=0)
	public Long getVersion() {
		return version;
	}

	public void setVersion(Long version) {
		this.version = version;
	}

	@Temporal(TemporalType.DATE)
    @Column(name="PERIOD_END")
	public Date getPeriodEnd() {
		return periodEnd;
	}

	public void setPeriodEnd(Date periodEnd) {
		this.periodEnd = periodEnd;
	}

	@Temporal(TemporalType.DATE)
    @Column(name="PERIOD_START")
	public Date getPeriodStart() {
		return periodStart;
	}

	public void setPeriodStart(Date periodStart) {
		this.periodStart = periodStart;
	}

	@Column(name="REQ_FOR", length=20)
	public String getReqFor() {
		return reqFor;
	}

	public void setReqFor(String reqFor) {
		this.reqFor = reqFor;
	}

	@Column(name="FW_STS")
	public String getFwSts() {
		return fwSts;
	}

	public void setFwSts(String fwSts) {
		this.fwSts = fwSts;
	}

	@Column(name="AL_STS")
	public String getAlSts() {
		return alSts;
	}

	public void setAlSts(String alSts) {
		this.alSts = alSts;
	}

	@Column(name="AT_STS")
	public String getAtSts() {
		return atSts;
	}

	public void setAtSts(String atSts) {
		this.atSts = atSts;
	}

	@Column(name="PI_STS")
	public String getPiSts() {
		return piSts;
	}

	public void setPiSts(String piSts) {
		this.piSts = piSts;
	}

	@Column(name="IG_STS")
	public String getIgSts() {
		return igSts;
	}

	public void setIgSts(String igSts) {
		this.igSts = igSts;
	}

	@Column(name="RT_STS")
	public String getRtSts() {
		return rtSts;
	}

	public void setRtSts(String rtSts) {
		this.rtSts = rtSts;
	}

	@Column(name="F5_STS")
	public String getF5Sts() {
		return f5Sts;
	}

	public void setF5Sts(String f5Sts) {
		this.f5Sts = f5Sts;
	}

	@Column(name="CREATE_BY")
	public String getCreatedBy() {
		return createdBy;
	}

	public void setCreatedBy(String createdBy) {
		this.createdBy = createdBy;
	}

	 @Column(name="CREATE_DATE")
	public Date getCreated() {
		return created;
	}

	public void setCreated(Date created) {
		this.created = created;
	}

	@Column(name="UPDATE_BY")
	public String getLastUpdBy() {
		return lastUpdBy;
	}

	public void setLastUpdBy(String lastUpdBy) {
		this.lastUpdBy = lastUpdBy;
	}
		
	 @Column(name="UPDATE_DATE")
	public Date getLastUpd() {
		return lastUpd;
	}
		
	public void setLastUpd(Date lastUpd) {
		this.lastUpd = lastUpd;
	}

	@Column(name="UR_TYPE")
	public String getUrType() {
		return urType;
	}

	public void setUrType(String urType) {
		this.urType = urType;
	}

	@Column(name="UR_STATUS")
	public String getUrStatusTxt() {
		return urStatusTxt;
	}

	public void setUrStatusTxt(String urStatusTxt) {
		this.urStatusTxt = urStatusTxt;
	}

	@Column(name="UR_STATUS_NAME")
	public String getUrStatusName() {
		return urStatusName;
	}

	public void setUrStatusName(String urStatusName) {
		this.urStatusName = urStatusName;
	}

	@Column(name="OVER_SLA")
	public String getOverSla() {
		return overSla;
	}

	public void setOverSla(String overSla) {
		this.overSla = overSla;
	}

	@OneToMany
	@JoinColumn(name="UR_NO", referencedColumnName="UR_NO", nullable=true, insertable=false, updatable=false)
	public List<IpUrFirewall> getListFirewall() {
		return listFirewall;
	}

	public void setListFirewall(List<IpUrFirewall> listFirewall) {
		this.listFirewall = listFirewall;
	}

	@OneToMany
	@JoinColumn(name="UR_NO", referencedColumnName="UR_NO", nullable=true, insertable=false, updatable=false)
	public List<IpUrAccessListCdn> getListAccessListCdn() {
		return listAccessListCdn;
	}

	public void setListAccessListCdn(List<IpUrAccessListCdn> listAccessListCdn) {
		this.listAccessListCdn = listAccessListCdn;
	}

	@OneToMany
	@JoinColumn(name="UR_NO", referencedColumnName="UR_NO", nullable=true, insertable=false, updatable=false)
	public List<IpUrAccessListTnp> getListAccessListTnp() {
		return listAccessListTnp;
	}

	public void setListAccessListTnp(List<IpUrAccessListTnp> listAccessListTnp) {
		this.listAccessListTnp = listAccessListTnp;
	}

	@OneToMany
	@JoinColumn(name="UR_NO", referencedColumnName="UR_NO", nullable=true, insertable=false, updatable=false)
	public List<IpUrPhysicalInterface> getListPhyInterface() {
		return listPhyInterface;
	}

	public void setListPhyInterface(List<IpUrPhysicalInterface> listPhyInterface) {
		this.listPhyInterface = listPhyInterface;
	}

	@OneToMany
	@JoinColumn(name="UR_NO", referencedColumnName="UR_NO", nullable=true, insertable=false, updatable=false)
	public List<IpUrInterfaceGateway> getListIntfGateway() {
		return listIntfGateway;
	}

	public void setListIntfGateway(List<IpUrInterfaceGateway> listIntfGateway) {
		this.listIntfGateway = listIntfGateway;
	}

	@OneToMany
	@JoinColumn(name="UR_NO", referencedColumnName="UR_NO", nullable=true, insertable=false, updatable=false)
	public List<IpUrRouting> getListRouting() {
		return listRouting;
	}

	public void setListRouting(List<IpUrRouting> listRouting) {
		this.listRouting = listRouting;
	}

	@OneToMany
	@JoinColumn(name="UR_NO", referencedColumnName="UR_NO", nullable=true, insertable=false, updatable=false)
	public List<IpUrF5> getListF5() {
		return listF5;
	}

	public void setListF5(List<IpUrF5> listF5) {
		this.listF5 = listF5;
	}

	@Column(name="IS_IMPACT")
	public String getIsImpact() {
		return isImpact;
	}

	public void setIsImpact(String isImpact) {
		this.isImpact = isImpact;
	}

	@Column(name="TNP_STATUS")
	public String getTnpStatus() {
		return tnpStatus;
	}

	public void setTnpStatus(String tnpStatus) {
		this.tnpStatus = tnpStatus;
	}

	@Column(name="APPROVE_MANAGER")
	public String getApproveManager() {
		return approveManager;
	}

	public void setApproveManager(String approveManager) {
		this.approveManager = approveManager;
	}


}


