package th.co.ais.ipfm.domain1;
// Generated 27 �.�. 2553, 17:13:55 by Hibernate Tools 3.2.1.GA


import java.util.Date;

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;
import javax.persistence.Version;

import th.co.ais.ipfm.domain.MasterDomain;

/**
 * IpUrAttachment generated by hbm2java
 */
@Entity
@Table(name="IP_UR_ATTACHMENT"
    , uniqueConstraints = @UniqueConstraint(columnNames="ROW_ID") 
)
public class IpUrAttachment  extends MasterDomain  implements java.io.Serializable,Cloneable {


     private IpUrAttachmentId id;
     private Long version;
     private String rowId;
     private String description;
     private String fileLocation;
     private String fileName;
     

    public IpUrAttachment() {
    }

	
    public IpUrAttachment(IpUrAttachmentId id) {
        this.id = id;
    }
    public IpUrAttachment(IpUrAttachmentId id, String rowId, String description, String fileLocation, String fileName, String createBy, Date createDate, String updateBy, Date updateDate) {
       this.id = id;
       this.rowId = rowId;
       this.description = description;
       this.fileLocation = fileLocation;
       this.fileName = fileName;
    }
   
     @EmbeddedId
    
    @AttributeOverrides( {
        @AttributeOverride(name="urNo", column=@Column(name="UR_NO", nullable=false, length=20) ), 
        @AttributeOverride(name="seq", column=@Column(name="SEQ", nullable=false, precision=22, scale=0) ), 
        @AttributeOverride(name="category", column=@Column(name="CATEGORY", nullable=false, length=20) ) } )
    public IpUrAttachmentId getId() {
        return this.id;
    }
    
    public void setId(IpUrAttachmentId id) {
        this.id = id;
    }
    @Version
    @Column(name="VERSION", precision=10, scale=0)
    public Long getVersion() {
        return this.version;
    }
    
    public void setVersion(Long version) {
        this.version = version;
    }
    
    @Column(name="ROW_ID", unique=true, length=50)
    public String getRowId() {
        return this.rowId;
    }
    
    public void setRowId(String rowId) {
        this.rowId = rowId;
    }
    
    @Column(name="DESCRIPTION", length=1000)
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }
    
    @Column(name="FILE_LOCATION", length=200)
    public String getFileLocation() {
        return this.fileLocation;
    }
    
    public void setFileLocation(String fileLocation) {
        this.fileLocation = fileLocation;
    }
    
    @Column(name="FILE_NAME", length=100)
    public String getFileName() {
        return this.fileName;
    }
    
    public void setFileName(String fileName) {
        this.fileName = fileName;
    }
	@Column(name="CREATE_BY")
	public String getCreatedBy() {
		return createdBy;
	}

	public void setCreatedBy(String createdBy) {
		this.createdBy = createdBy;
	}

	@Column(name="CREATE_DATE")
	public Date getCreated() {
		return created;
	}

	public void setCreated(Date created) {
		this.created = created;
	}

	@Column(name="UPDATE_BY")
	public String getLastUpdBy() {
		return lastUpdBy;
	}

	public void setLastUpdBy(String lastUpdBy) {
		this.lastUpdBy = lastUpdBy;
	}
	
	@Column(name="UPDATE_DATE")
	public Date getLastUpd() {
		return lastUpd;
	}
	
	public void setLastUpd(Date lastUpd) {
		this.lastUpd = lastUpd;
	}

	@Override
    public Object clone() throws CloneNotSupportedException
    {
		IpUrAttachment another = (IpUrAttachment) super.clone();
		another.setId((IpUrAttachmentId)getId().clone());
        return another;
    }

}


