package th.co.ais.ipfm.domain1;
// Generated 27 �.�. 2553, 17:13:55 by Hibernate Tools 3.2.1.GA


import java.util.Date;

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.JoinColumn;
import javax.persistence.JoinColumns;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Transient;
import javax.persistence.UniqueConstraint;
import javax.persistence.Version;

import org.hibernate.annotations.GenericGenerator;

/**
 * IpUrFirewall generated by hbm2java
 */
@Entity
@Table(name="IP_UR_FIREWALL"
    , uniqueConstraints = @UniqueConstraint(columnNames="ROW_ID") 
)
public class IpUrFirewall implements java.io.Serializable, Cloneable {

	@EmbeddedId
    @AttributeOverrides( {
        @AttributeOverride(name="urNo", column=@Column(name="UR_NO", nullable=false, length=20) ), 
        @AttributeOverride(name="subUrNo", column=@Column(name="SUB_UR_NO", nullable=false, length=10) ) } )
    private IpUrFirewallId id;
	
	@Column(name="SOURCE_IP", length=25)
    private String sourceIp;
	
	@Column(name="SOURCE_IP_1", length=20)
    private String sourceIp1;
	
	@Column(name="SOURCE_IP_2", length=20)
    private String sourceIp2;
	
	@Column(name="SOURCE_HOST_NAME", length=1000)
    private String sourceHostName;
	
	@Column(name="SOURCE_EMAIL", length=100)
    private String sourceEmail;
	
	@Column(name="SOURCE_VIP", length=3)
    private String sourceVip;
	
	@Column(name="SOURCE_NAT_IP", length=5)
    private String sourceNatIp;

	@Column(name="DEST_IP", length=25)
	private String destIp;
	
	@Column(name="DEST_IP_1", length=20)
    private String destIp1;
	
	@Column(name="DEST_IP_2", length=20)
    private String destIp2;
	
	@Column(name="DEST_HOST_NAME", length=1000)
    private String destHostName;
	
	@Column(name="DEST_EMAIL", length=100)
    private String destEmail;
	
	@Column(name="DEST_VIP", length=3)
    private String destVip;
	
	@Column(name="DEST_NAT_IP", length=20)
    private String destNatIp;
	
	@Column(name="SERVICE_STATUS", length=1)
    private String serviceStatus;
	
	@Column(name="SERVICE_ID", length=100)
    private String serviceId;
	
	@Column(name="SERVICE_NAME", length=100)
    private String serviceName;
	
	@Column(name="SERVICE_DESC", length=1000)
    private String serviceDesc;
	
	@Column(name="SERVICE_TCP_STATUS", length=1)
    private String serviceTcpStatus;
	
	@Column(name="SERVICE_TCP_PORT", length=100)
    private String serviceTcpPort;
	
	@Column(name="SERVICE_UDP_STATUS", length=1)
    private String serviceUdpStatus;
	
	@Column(name="SERVICE_UDP_PORT", length=100)
    private String serviceUdpPort;
	
	@Column(name="SERVICE_OTHER_STATUS", length=1)
    private String serviceOtherStatus;
	
	@Column(name="SERVICE_OTHER_PORT", length=100)
    private String serviceOtherPort;
	
	@Column(name="IS_ASSIGN", length=1)
	private String isAssign;
	
	@Column(name="IS_IMPACT", length=1)
	private String isImpact;
    
	@Column(name="SYS_OWNER_REMARK", length=1000)
	private String sysOwnerRemark;
    
    @Column(name="PM_REMARK", length=1000)
    private String pmRemark;
    
    @Column(name="ACTM_REMARK", length=1000)
    private String actmRemark;
    
    @Column(name="TEAM_REMARK", length=1000)
    private String teamRemark;
    
    @ManyToOne(optional = false, fetch = FetchType.LAZY)
    @JoinColumns( {
    	@JoinColumn(name = "SUB_UR_STATUS", referencedColumnName = "SUB_UR_STATUS_ID", nullable = true, insertable=false, updatable=false),
    	@JoinColumn(name = "UR_TYPE", referencedColumnName = "UR_TYPE" , nullable = true, insertable=false, updatable=false)
    })
    private IpUrStatus subUrStatus;
    
    @Column(name="SUB_UR_STATUS", length=20)
    private String subUrStatusTxt;
    
    @Column(name="UR_TYPE", length=5)
    private String urType;
    
    @GeneratedValue(generator="system-uuid")
	@GenericGenerator(name="system-uuid", strategy = "uuid")
    @Column(name="ROW_ID", unique=true, length=50)
    private String rowId;
    
    @Version
    @Column(name="VERSION", precision=10, scale=0)
    private Long version;
    
    @Column(name="CREATE_BY")
	private String createdBy;
	
    @Column(name="CREATE_DATE", length=10)
	private Date created;
	
	@Column(name="UPDATE_BY")
	private String lastUpdBy;
	
    @Column(name="UPDATE_DATE", length=10)
	private Date lastUpd;
	
	@Column(name="IS_TNP", length=2)
	private String isTnp;
	
	@Column(name="CHANGE_TYPE", length=2)
	private String changeType;
	
	// additional for approve
	@Transient
	private String isApprove;
	
	@Transient
	private String isReject;
	
	@Transient
	private boolean isSelected;
	
	@Transient
	private boolean impactSelected;
	
	@Transient
	private String serviceTcpPortStr;
	
	@Transient
	private String serviceUdpPortStr;
	
	@Transient
	private String serviceOtherPortStr;
	
//	public boolean isImpactSelected() {
//		if (getIsImpact()==null || getIsImpact().equalsIgnoreCase("N"))
//			return false;
//		else
//			return true;
//	}
	public boolean isImpactSelected() {
		return impactSelected;
	}
    public void setImpactSelected(boolean impactSelected) {
		this.impactSelected = impactSelected;
	}
    public IpUrFirewall() {
    }

	public IpUrFirewallId getId() {
		return id;
	}

	public void setId(IpUrFirewallId id) {
		this.id = id;
	}

	public String getSourceIp() {
		return sourceIp;
	}

	public void setSourceIp(String sourceIp) {
		this.sourceIp = sourceIp;
	}

	public String getSourceIp1() {
		return sourceIp1;
	}

	public void setSourceIp1(String sourceIp1) {
		this.sourceIp1 = sourceIp1;
	}

	public String getSourceIp2() {
		return sourceIp2;
	}

	public void setSourceIp2(String sourceIp2) {
		this.sourceIp2 = sourceIp2;
	}

	public String getSourceHostName() {
		return sourceHostName;
	}

	public void setSourceHostName(String sourceHostName) {
		this.sourceHostName = sourceHostName;
	}

	public String getSourceEmail() {
		return sourceEmail;
	}

	public void setSourceEmail(String sourceEmail) {
		this.sourceEmail = sourceEmail;
	}

	public String getSourceVip() {
		return sourceVip;
	}

	public void setSourceVip(String sourceVip) {
		this.sourceVip = sourceVip;
	}

	public String getSourceNatIp() {
		return sourceNatIp;
	}

	public void setSourceNatIp(String sourceNatIp) {
		this.sourceNatIp = sourceNatIp;
	}

	public String getDestIp() {
		return destIp;
	}

	public void setDestIp(String destIp) {
		this.destIp = destIp;
	}

	public String getDestIp1() {
		return destIp1;
	}

	public void setDestIp1(String destIp1) {
		this.destIp1 = destIp1;
	}

	public String getDestIp2() {
		return destIp2;
	}

	public void setDestIp2(String destIp2) {
		this.destIp2 = destIp2;
	}

	public String getDestHostName() {
		return destHostName;
	}

	public void setDestHostName(String destHostName) {
		this.destHostName = destHostName;
	}

	public String getDestEmail() {
		return destEmail;
	}

	public void setDestEmail(String destEmail) {
		this.destEmail = destEmail;
	}

	public String getDestVip() {
		return destVip;
	}

	public void setDestVip(String destVip) {
		this.destVip = destVip;
	}

	public String getDestNatIp() {
		return destNatIp;
	}

	public void setDestNatIp(String destNatIp) {
		this.destNatIp = destNatIp;
	}

	public String getServiceStatus() {
		return serviceStatus;
	}

	public void setServiceStatus(String serviceStatus) {
		this.serviceStatus = serviceStatus;
	}

	public String getServiceId() {
		return serviceId;
	}

	public void setServiceId(String serviceId) {
		this.serviceId = serviceId;
	}

	public String getServiceName() {
		return serviceName;
	}

	public void setServiceName(String serviceName) {
		this.serviceName = serviceName;
	}

	public String getServiceDesc() {
		return serviceDesc;
	}

	public void setServiceDesc(String serviceDesc) {
		this.serviceDesc = serviceDesc;
	}

	public String getServiceTcpStatus() {
		return serviceTcpStatus;
	}

	public void setServiceTcpStatus(String serviceTcpStatus) {
		this.serviceTcpStatus = serviceTcpStatus;
	}

	public String getServiceTcpPort() {
		return serviceTcpPort;
	}

	public void setServiceTcpPort(String serviceTcpPort) {
		this.serviceTcpPort = serviceTcpPort;
	}

	public String getServiceUdpStatus() {
		return serviceUdpStatus;
	}

	public void setServiceUdpStatus(String serviceUdpStatus) {
		this.serviceUdpStatus = serviceUdpStatus;
	}

	public String getServiceUdpPort() {
		return serviceUdpPort;
	}

	public void setServiceUdpPort(String serviceUdpPort) {
		this.serviceUdpPort = serviceUdpPort;
	}

	public String getServiceOtherStatus() {
		return serviceOtherStatus;
	}

	public void setServiceOtherStatus(String serviceOtherStatus) {
		this.serviceOtherStatus = serviceOtherStatus;
	}

	public String getServiceOtherPort() {
		return serviceOtherPort;
	}

	public void setServiceOtherPort(String serviceOtherPort) {
		this.serviceOtherPort = serviceOtherPort;
	}

	public String getIsAssign() {
		return isAssign;
	}

	public void setIsAssign(String isAssign) {
		this.isAssign = isAssign;
	}

	public String getIsImpact() {
		return isImpact;
	}

	public void setIsImpact(String isImpact) {
		this.isImpact = isImpact;
	}

	public String getSysOwnerRemark() {
		return sysOwnerRemark;
	}

	public void setSysOwnerRemark(String sysOwnerRemark) {
		this.sysOwnerRemark = sysOwnerRemark;
	}

	public String getPmRemark() {
		return pmRemark;
	}

	public void setPmRemark(String pmRemark) {
		this.pmRemark = pmRemark;
	}

	public String getActmRemark() {
		return actmRemark;
	}

	public void setActmRemark(String actmRemark) {
		this.actmRemark = actmRemark;
	}

	public IpUrStatus getSubUrStatus() {
		return subUrStatus;
	}

	public void setSubUrStatus(IpUrStatus subUrStatus) {
		this.subUrStatus = subUrStatus;
	}

	public String getRowId() {
		return rowId;
	}

	public void setRowId(String rowId) {
		this.rowId = rowId;
	}

	public Long getVersion() {
		return version;
	}

	public void setVersion(Long version) {
		this.version = version;
	}

	public String getCreatedBy() {
		return createdBy;
	}

	public void setCreatedBy(String createdBy) {
		this.createdBy = createdBy;
	}

	public Date getCreated() {
		return created;
	}

	public void setCreated(Date created) {
		this.created = created;
	}

	public String getLastUpdBy() {
		return lastUpdBy;
	}

	public void setLastUpdBy(String lastUpdBy) {
		this.lastUpdBy = lastUpdBy;
	}

	public Date getLastUpd() {
		return lastUpd;
	}

	public void setLastUpd(Date lastUpd) {
		this.lastUpd = lastUpd;
	}

	public String getUrType() {
		return urType;
	}

	public void setUrType(String urType) {
		this.urType = urType;
	}

	public String getSubUrStatusTxt() {
		return subUrStatusTxt;
	}

	public void setSubUrStatusTxt(String subUrStatusTxt) {
		this.subUrStatusTxt = subUrStatusTxt;
	}

	public String getIsApprove() {
		return isApprove;
	}

	public void setIsApprove(String isApprove) {
		this.isApprove = isApprove;
	}

	public String getIsReject() {
		return isReject;
	}

	public void setIsReject(String isReject) {
		this.isReject = isReject;
	}

	public boolean getIsSelected() {
		return isSelected;
	}

	public void setIsSelected(boolean isSelected) {
		this.isSelected = isSelected;
	}

	public String getIsTnp() {
		return isTnp;
	}

	public void setIsTnp(String isTnp) {
		this.isTnp = isTnp;
	}

	public void setSelected(boolean isSelected) {
		this.isSelected = isSelected;
	}

	public String getChangeType() {
		return changeType;
	}

	public void setChangeType(String changeType) {
		this.changeType = changeType;
	}

    public String getTeamRemark() {
		return teamRemark;
	}

	public void setTeamRemark(String teamRemark) {
		this.teamRemark = teamRemark;
	}

	@Override
    public Object clone() throws CloneNotSupportedException
    {
    	IpUrFirewall another = (IpUrFirewall) super.clone();
        //? take care of any deep copies to be made here
        return another;
    }
	public String getServiceTcpPortStr() {
		return serviceTcpPortStr;
	}
	public void setServiceTcpPortStr(String serviceTcpPortStr) {
		this.serviceTcpPortStr = serviceTcpPortStr;
	}
	public String getServiceUdpPortStr() {
		return serviceUdpPortStr;
	}
	public void setServiceUdpPortStr(String serviceUdpPortStr) {
		this.serviceUdpPortStr = serviceUdpPortStr;
	}
	public String getServiceOtherPortStr() {
		return serviceOtherPortStr;
	}
	public void setServiceOtherPortStr(String serviceOtherPortStr) {
		this.serviceOtherPortStr = serviceOtherPortStr;
	}
    
	
    


}


