package th.co.ais.ipfm.domain1;
// Generated 27 �.�. 2553, 17:13:55 by Hibernate Tools 3.2.1.GA


import java.util.Date;

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.JoinColumn;
import javax.persistence.JoinColumns;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Transient;
import javax.persistence.UniqueConstraint;
import javax.persistence.Version;

import org.hibernate.annotations.GenericGenerator;

import th.co.ais.ipfm.domain.MasterDomain;

/**
 * IpUrAccessListCdn generated by hbm2java
 */
@Entity
@Table(name="IP_UR_ACCESS_LIST_CDN"
    , uniqueConstraints = @UniqueConstraint(columnNames="ROW_ID") 
)
public class IpUrAccessListCdn extends MasterDomain    implements java.io.Serializable, Cloneable {


    private IpUrAccessListCdnId id;
    private Long version;
    private String sourceIp;
    private String sourceHostName;
    private String sourceEmail;
    private String destIp;
    private String destHostName;
    private String destEmail;
    private String sysOwnerRemark;
    private String isImpact;
    private String pmRemark;
    private String teamRemark;
    private String rowId;

    private String sourceIp1; 
    private String sourceIp2; 
    private String destIp1; 
    private String destIp2; 
    private String isAssign; 
    private String actmRemark; 
     
    private IpUrStatus subUrStatus;
    private String urType;
    private String subUrStatusTxt;
     
 	
	private String isApprove;
	private String isReject;
	private boolean isSelected;
	
	
	private String isTnp;
	private String changeType;
	
	
	private boolean impactSelected;
	
//	@Transient
//	public boolean isImpactSelected() {
//		if (getIsImpact()==null || getIsImpact().equalsIgnoreCase("N"))
//			return false;
//		else
//			return true;
//	}
	@Transient
	public boolean isImpactSelected() { // DMAP Comment : Dead Code Detected - The Following Method has no reference isImpactSelected
		return impactSelected;
	}
    public void setImpactSelected(boolean impactSelected) { // DMAP Comment : Dead Code Detected - The Following Method has no reference setImpactSelected
		this.impactSelected = impactSelected;
	}

	public IpUrAccessListCdn() {
    }

	
    public IpUrAccessListCdn(IpUrAccessListCdnId id) {
        this.id = id;
    }
    public IpUrAccessListCdn(IpUrAccessListCdnId id, String reqType, String sourceIp, String sourceHostName, String sourceEmail, String destIp, String destHostName, String destEmail, String sysOwnerRemark, String isImpact, String pmRemark, String createBy, Date createDate, String updateBy, Date updateDate, String rowId) {
       this.id = id;
       this.sourceIp = sourceIp;
       this.sourceHostName = sourceHostName;
       this.sourceEmail = sourceEmail;
       this.destIp = destIp;
       this.destHostName = destHostName;
       this.destEmail = destEmail;
       this.sysOwnerRemark = sysOwnerRemark;
       this.isImpact = isImpact;
       this.pmRemark = pmRemark;
       this.rowId = rowId;
    }
   
    @EmbeddedId
    @AttributeOverrides( {
        @AttributeOverride(name="urNo", column=@Column(name="UR_NO", nullable=false, length=30) ), 
        @AttributeOverride(name="subUrNo", column=@Column(name="SUB_UR_NO", nullable=false, length=10) ) } )
    public IpUrAccessListCdnId getId() { // DMAP Comment : Dead Code Detected - The Following Method has no reference getId
        return this.id;
    }
    
    public void setId(IpUrAccessListCdnId id) { // DMAP Comment : Dead Code Detected - The Following Method has no reference setId
        this.id = id;
    }
    @Version
    @Column(name="VERSION", precision=10, scale=0)
    public Long getVersion() { // DMAP Comment : Dead Code Detected - The Following Method has no reference getVersion
        return this.version;
    }
    
    public void setVersion(Long version) { // DMAP Comment : Dead Code Detected - The Following Method has no reference setVersion
        this.version = version;
    }
    
    
    @Column(name="SOURCE_IP", length=21)
    public String getSourceIp() { // DMAP Comment : Dead Code Detected - The Following Method has no reference getSourceIp
        return this.sourceIp;
    }
    
    public void setSourceIp(String sourceIp) { // DMAP Comment : Dead Code Detected - The Following Method has no reference setSourceIp
        this.sourceIp = sourceIp;
    }
    
    @Column(name="SOURCE_HOST_NAME", length=1000)
    public String getSourceHostName() { // DMAP Comment : Dead Code Detected - The Following Method has no reference getSourceHostName
        return this.sourceHostName;
    }
    
    public void setSourceHostName(String sourceHostName) { // DMAP Comment : Dead Code Detected - The Following Method has no reference setSourceHostName
        this.sourceHostName = sourceHostName;
    }
    
    @Column(name="SOURCE_EMAIL", length=100)
    public String getSourceEmail() { // DMAP Comment : Dead Code Detected - The Following Method has no reference getSourceEmail
        return this.sourceEmail;
    }
    
    public void setSourceEmail(String sourceEmail) { // DMAP Comment : Dead Code Detected - The Following Method has no reference setSourceEmail
        this.sourceEmail = sourceEmail;
    }
    
    @Column(name="DEST_IP", length=21)
    public String getDestIp() { // DMAP Comment : Dead Code Detected - The Following Method has no reference getDestIp
        return this.destIp;
    }
    
    public void setDestIp(String destIp) { // DMAP Comment : Dead Code Detected - The Following Method has no reference setDestIp
        this.destIp = destIp;
    }
    
    @Column(name="DEST_HOST_NAME", length=1000)
    public String getDestHostName() { // DMAP Comment : Dead Code Detected - The Following Method has no reference getDestHostName
        return this.destHostName;
    }
    
    public void setDestHostName(String destHostName) { // DMAP Comment : Dead Code Detected - The Following Method has no reference setDestHostName
        this.destHostName = destHostName;
    }
    
    @Column(name="DEST_EMAIL", length=100)
    public String getDestEmail() { // DMAP Comment : Dead Code Detected - The Following Method has no reference getDestEmail
        return this.destEmail;
    }
    
    public void setDestEmail(String destEmail) { // DMAP Comment : Dead Code Detected - The Following Method has no reference setDestEmail
        this.destEmail = destEmail;
    }
    
    @Column(name="SYS_OWNER_REMARK", length=1000)
    public String getSysOwnerRemark() { // DMAP Comment : Dead Code Detected - The Following Method has no reference getSysOwnerRemark
        return this.sysOwnerRemark;
    }
    
    public void setSysOwnerRemark(String sysOwnerRemark) { // DMAP Comment : Dead Code Detected - The Following Method has no reference setSysOwnerRemark
        this.sysOwnerRemark = sysOwnerRemark;
    }
    
    @Column(name="IS_IMPACT", length=1)
    public String getIsImpact() { // DMAP Comment : Dead Code Detected - The Following Method has no reference getIsImpact
        return this.isImpact;
    }
    
    public void setIsImpact(String isImpact) { // DMAP Comment : Dead Code Detected - The Following Method has no reference setIsImpact
        this.isImpact = isImpact;
    }
    @Column(name="TEAM_REMARK", length=1000)
    public String getTeamRemark() { // DMAP Comment : Dead Code Detected - The Following Method has no reference getTeamRemark
		return teamRemark;
	}

	public void setTeamRemark(String teamRemark) { // DMAP Comment : Dead Code Detected - The Following Method has no reference setTeamRemark
		this.teamRemark = teamRemark;
	}

	@Column(name="PM_REMARK", length=1000)
    public String getPmRemark() { // DMAP Comment : Dead Code Detected - The Following Method has no reference getPmRemark
        return this.pmRemark;
    }
    
    public void setPmRemark(String pmRemark) { // DMAP Comment : Dead Code Detected - The Following Method has no reference setPmRemark
        this.pmRemark = pmRemark;
    }
    
    @Column(name="CREATE_BY")
	public String getCreatedBy() { // DMAP Comment : Dead Code Detected - The Following Method has no reference getCreatedBy
		return createdBy;
	}

	public void setCreatedBy(String createdBy) { // DMAP Comment : Dead Code Detected - The Following Method has no reference setCreatedBy
		this.createdBy = createdBy;
	}

	@Column(name="CREATE_DATE")
	public Date getCreated() { // DMAP Comment : Dead Code Detected - The Following Method has no reference getCreated
		return created;
	}

	public void setCreated(Date created) { // DMAP Comment : Dead Code Detected - The Following Method has no reference setCreated
		this.created = created;
	}

	@Column(name="UPDATE_BY")
	public String getLastUpdBy() { // DMAP Comment : Dead Code Detected - The Following Method has no reference getLastUpdBy
		return lastUpdBy;
	}

	public void setLastUpdBy(String lastUpdBy) { // DMAP Comment : Dead Code Detected - The Following Method has no reference setLastUpdBy
		this.lastUpdBy = lastUpdBy;
	}
		
	@Column(name="UPDATE_DATE")
	public Date getLastUpd() { // DMAP Comment : Dead Code Detected - The Following Method has no reference getLastUpd
		return lastUpd;
	}
		
	public void setLastUpd(Date lastUpd) { // DMAP Comment : Dead Code Detected - The Following Method has no reference setLastUpd
		this.lastUpd = lastUpd;
	}
	
	@GeneratedValue(generator="system-uuid")
	@GenericGenerator(name="system-uuid", strategy = "uuid")
    @Column(name="ROW_ID", unique=true, length=50)
    public String getRowId() { // DMAP Comment : Dead Code Detected - The Following Method has no reference getRowId
        return this.rowId;
    }
    
    public void setRowId(String rowId) { // DMAP Comment : Dead Code Detected - The Following Method has no reference setRowId
        this.rowId = rowId;
    }

    @Column(name="SOURCE_IP_1", length=50)
	public String getSourceIp1() { // DMAP Comment : Dead Code Detected - The Following Method has no reference getSourceIp1
		return sourceIp1;
	}


	public void setSourceIp1(String sourceIp1) { // DMAP Comment : Dead Code Detected - The Following Method has no reference setSourceIp1
		this.sourceIp1 = sourceIp1;
	}

	@Column(name="SOURCE_IP_2", length=50)
	public String getSourceIp2() { // DMAP Comment : Dead Code Detected - The Following Method has no reference getSourceIp2
		return sourceIp2;
	}


	public void setSourceIp2(String sourceIp2) { // DMAP Comment : Dead Code Detected - The Following Method has no reference setSourceIp2
		this.sourceIp2 = sourceIp2;
	}

	@Column(name="DEST_IP_1", length=50)
	public String getDestIp1() { // DMAP Comment : Dead Code Detected - The Following Method has no reference getDestIp1
		return destIp1;
	}

	
	public void setDestIp1(String destIp1) { // DMAP Comment : Dead Code Detected - The Following Method has no reference setDestIp1
		this.destIp1 = destIp1;
	}

	@Column(name="DEST_IP_2", length=50)
	public String getDestIp2() { // DMAP Comment : Dead Code Detected - The Following Method has no reference getDestIp2
		return destIp2;
	}

	public void setDestIp2(String destIp2) { // DMAP Comment : Dead Code Detected - The Following Method has no reference setDestIp2
		this.destIp2 = destIp2;
	}

	@Column(name="IS_ASSIGN", length=50)
	public String getIsAssign() { // DMAP Comment : Dead Code Detected - The Following Method has no reference getIsAssign
		return isAssign;
	}

	
	public void setIsAssign(String isAssign) { // DMAP Comment : Dead Code Detected - The Following Method has no reference setIsAssign
		this.isAssign = isAssign;
	}

	@Column(name="ACTM_REMARK", length=1000)
	public String getActmRemark() { // DMAP Comment : Dead Code Detected - The Following Method has no reference getActmRemark
		return actmRemark;
	}

	
	public void setActmRemark(String actmRemark) { // DMAP Comment : Dead Code Detected - The Following Method has no reference setActmRemark
		this.actmRemark = actmRemark;
	}

	@ManyToOne(optional = false, fetch = FetchType.LAZY)
    @JoinColumns( {
    	@JoinColumn(name = "SUB_UR_STATUS", referencedColumnName = "SUB_UR_STATUS_ID", nullable = true, insertable=false, updatable=false),
    	@JoinColumn(name = "UR_TYPE", referencedColumnName = "UR_TYPE" , nullable = true, insertable=false, updatable=false)
    })
	public IpUrStatus getSubUrStatus() { // DMAP Comment : Dead Code Detected - The Following Method has no reference getSubUrStatus
		return subUrStatus;
	}
	
	public void setSubUrStatus(IpUrStatus subUrStatus) { // DMAP Comment : Dead Code Detected - The Following Method has no reference setSubUrStatus
		this.subUrStatus = subUrStatus;
	}

	@Column(name="UR_TYPE", length=5)
	public String getUrType() { // DMAP Comment : Dead Code Detected - The Following Method has no reference getUrType
		return urType;
	}


	public void setUrType(String urType) { // DMAP Comment : Dead Code Detected - The Following Method has no reference setUrType
		this.urType = urType;
	}
	
	@Column(name="SUB_UR_STATUS", length=20)
    public String getSubUrStatusTxt() { // DMAP Comment : Dead Code Detected - The Following Method has no reference getSubUrStatusTxt
		return subUrStatusTxt;
	}


	public void setSubUrStatusTxt(String subUrStatusTxt) { // DMAP Comment : Dead Code Detected - The Following Method has no reference setSubUrStatusTxt
		this.subUrStatusTxt = subUrStatusTxt;
	}

	@Transient
	public String getIsApprove() { // DMAP Comment : Dead Code Detected - The Following Method has no reference getIsApprove
		return isApprove;
	}


	public void setIsApprove(String isApprove) { // DMAP Comment : Dead Code Detected - The Following Method has no reference setIsApprove
		this.isApprove = isApprove;
	}

	@Transient
	public String getIsReject() { // DMAP Comment : Dead Code Detected - The Following Method has no reference getIsReject
		return isReject;
	}

	
	public void setIsReject(String isReject) { // DMAP Comment : Dead Code Detected - The Following Method has no reference setIsReject
		this.isReject = isReject;
	}

	@Transient
	public boolean getIsSelected() { // DMAP Comment : Dead Code Detected - The Following Method has no reference getIsSelected
		return isSelected;
	}

	public void setIsSelected(boolean isSelected) { // DMAP Comment : Dead Code Detected - The Following Method has no reference setIsSelected
		this.isSelected = isSelected;
	}

	@Column(name="CHANGE_TYPE", length=2)
	public String getChangeType() { // DMAP Comment : Dead Code Detected - The Following Method has no reference getChangeType
		return changeType;
	}


	public void setChangeType(String changeType) { // DMAP Comment : Dead Code Detected - The Following Method has no reference setChangeType
		this.changeType = changeType;
	}


	public void setSelected(boolean isSelected) { // DMAP Comment : Dead Code Detected - The Following Method has no reference setSelected
		this.isSelected = isSelected;
	}

	@Column(name="IS_TNP", length=2)
	public String getIsTnp() { // DMAP Comment : Dead Code Detected - The Following Method has no reference getIsTnp
		return isTnp;
	}


	public void setIsTnp(String isTnp) { // DMAP Comment : Dead Code Detected - The Following Method has no reference setIsTnp
		this.isTnp = isTnp;
	}
	
    @Override
    public Object clone() throws CloneNotSupportedException
    {
    	IpUrAccessListCdn another = (IpUrAccessListCdn) super.clone();
        //? take care of any deep copies to be made here
        return another;
    }


}


