package th.co.ais.ipfm.domain1;
// Generated 27 Ê.¤. 2553, 17:13:55 by Hibernate Tools 3.2.1.GA


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Transient;

/**
 * IpWfConfig generated by hbm2java
 */
@Entity
@Table(name="IPV_NETWORK_IP") 
public class IpvNetworkIp implements java.io.Serializable, Cloneable{


    private String networkIp;
    private String tier2TeamId;
    private String systemOwnerId;
    private String systemOwnerTeamId;
    private Integer networkIp1;
    private Integer networkIp2;
    private Integer networkIp3;
    private Integer networkIp4;
     
    
    public IpvNetworkIp() {
    }
    
    @Id 
    @Column(name="NETWORK_IP", unique=true, nullable=false, length=13)
    public String getNetworkIp() {
		return networkIp;
	}
    
	public void setNetworkIp(String networkIp) {
		this.networkIp = networkIp;
	}
	
	@Column(name="T2_TEAM_ID")
	public String getTier2TeamId() {
		return tier2TeamId;
	}

	public void setTier2TeamId(String tier2TeamId) {
		this.tier2TeamId = tier2TeamId;
	}

	@Column(name="SYSTEM_OWNER_ID")
	public String getSystemOwnerId() {
		return systemOwnerId;
	}

	public void setSystemOwnerId(String systemOwnerId) {
		this.systemOwnerId = systemOwnerId;
	}
	@Column(name="SYSTEM_OWNER_TEAM_ID")
	public String getSystemOwnerTeamId() {
		return systemOwnerTeamId;
	}

	public void setSystemOwnerTeamId(String systemOwnerTeamId) {
		this.systemOwnerTeamId = systemOwnerTeamId;
	}
	@Column(name="NETWORK_IP1")
	public Integer getNetworkIp1() {
		return networkIp1;
	}

	public void setNetworkIp1(Integer networkIp1) {
		this.networkIp1 = networkIp1;
	}
	@Column(name="NETWORK_IP2")
	public Integer getNetworkIp2() {
		return networkIp2;
	}

	public void setNetworkIp2(Integer networkIp2) {
		this.networkIp2 = networkIp2;
	}
	@Column(name="NETWORK_IP3")
	public Integer getNetworkIp3() {
		return networkIp3;
	}

	public void setNetworkIp3(Integer networkIp3) {
		this.networkIp3 = networkIp3;
	}
	@Column(name="NETWORK_IP4")
	public Integer getNetworkIp4() {
		return networkIp4;
	}

	public void setNetworkIp4(Integer networkIp4) {
		this.networkIp4 = networkIp4;
	}
	
	
}


