package th.co.ais.ipfm.domain1;
// Generated 27 Ê.¤. 2553, 17:13:55 by Hibernate Tools 3.2.1.GA


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * IpWfConfigDetailId generated by hbm2java
 */
@Embeddable
public class IpWfConfigDetailId  implements java.io.Serializable {


     private String nodeId;
     private String urType;

    public IpWfConfigDetailId() {
    }

    public IpWfConfigDetailId(String nodeId, String urType) {
       this.nodeId = nodeId;
       this.urType = urType;
    }
   

    @Column(name="NODE_ID", nullable=false, length=5)
    public String getNodeId() {
        return this.nodeId;
    }
    
    public void setNodeId(String nodeId) {
        this.nodeId = nodeId;
    }

    @Column(name="UR_TYPE", nullable=false, length=5)
    public String getUrType() {
        return this.urType;
    }
    
    public void setUrType(String urType) {
        this.urType = urType;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof IpWfConfigDetailId) ) return false;
		 IpWfConfigDetailId castOther = ( IpWfConfigDetailId ) other; 
         
		 return ( (this.getNodeId()==castOther.getNodeId()) || ( this.getNodeId()!=null && castOther.getNodeId()!=null && this.getNodeId().equals(castOther.getNodeId()) ) )
 && ( (this.getUrType()==castOther.getUrType()) || ( this.getUrType()!=null && castOther.getUrType()!=null && this.getUrType().equals(castOther.getUrType()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getNodeId() == null ? 0 : this.getNodeId().hashCode() );
         result = 37 * result + ( getUrType() == null ? 0 : this.getUrType().hashCode() );
         return result;
   }   


}


