package th.co.ais.ipfm.domain1;
// Generated 27 Ê.¤. 2553, 17:13:55 by Hibernate Tools 3.2.1.GA


import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Transient;
import javax.persistence.UniqueConstraint;
import javax.persistence.Version;

import org.hibernate.annotations.GenericGenerator;

import th.co.ais.ipfm.domain.MasterDomain;

/**
 * IpWfConfig generated by hbm2java
 */
@Entity
@Table(name="IP_WF_CONFIG"
    , uniqueConstraints = @UniqueConstraint(columnNames="ROW_ID") 
)
public class IpWfConfig extends MasterDomain  implements java.io.Serializable {


     private String urType;
     private Long version;
     private BigDecimal sla;
     private String smsStatus;
     private String smsMobileNoList;
     private String rowId;
     private String pmTeam;
     private String impactStatus;
     
     private int slaTnpWithoutImpact;
     private int slaTnpWithImpact;
     private int cdnWithoutImpact;
     private int cdnWithImpact;
     

    public IpWfConfig() {
    }

	
    public IpWfConfig(String urType) {
        this.urType = urType;
    }
    public IpWfConfig(String urType, BigDecimal sla, String smsStatus, String smsMobileNoList, String createBy, Date createDate, String updateBy, Date updateDate, String rowId) {
       this.urType = urType;
       this.sla = sla;
       this.smsStatus = smsStatus;
       this.smsMobileNoList = smsMobileNoList;
       this.rowId = rowId;
    }
    
    @Id 
    @Column(name="UR_TYPE", unique=true, nullable=false, length=5)
    public String getUrType() {
        return this.urType;
    }
    
    public void setUrType(String urType) {
        this.urType = urType;
    }
    @Version
    @Column(name="VERSION", precision=10, scale=0)
    public Long getVersion() {
        return this.version;
    }
    
    public void setVersion(Long version) {
        this.version = version;
    }
    
    @Column(name="SLA", precision=22, scale=0)
    public BigDecimal getSla() {
        return this.sla;
    }
    
    public void setSla(BigDecimal sla) {
        this.sla = sla;
    }
    
    @Column(name="SMS_STATUS", length=1)
    public String getSmsStatus() {
        return this.smsStatus;
    }
    
    public void setSmsStatus(String smsStatus) {
        this.smsStatus = smsStatus;
    }
    
    @Column(name="SMS_MOBILE_NO_LIST", length=1000)
    public String getSmsMobileNoList() {
        return this.smsMobileNoList;
    }
    
    public void setSmsMobileNoList(String smsMobileNoList) {
        this.smsMobileNoList = smsMobileNoList;
    }
   
    @Column(name="ROW_ID", unique=true, length=50)
    public String getRowId() {
        return this.rowId;
    }
    
    public void setRowId(String rowId) {
        this.rowId = rowId;
    }

    @Column(name="CREATE_BY")
	public String getCreatedBy() {
		return createdBy;
	}

	public void setCreatedBy(String createdBy) {
		this.createdBy = createdBy;
	}

	@Column(name="CREATE_DATE")
	public Date getCreated() {
		return created;
	}

	public void setCreated(Date created) {
		this.created = created;
	}

	@Column(name="UPDATE_BY")
	public String getLastUpdBy() {
		return lastUpdBy;
	}

	public void setLastUpdBy(String lastUpdBy) {
		this.lastUpdBy = lastUpdBy;
	}
	
	@Column(name="UPDATE_DATE")
	public Date getLastUpd() {
		return lastUpd;
	}
	
	public void setLastUpd(Date lastUpd) {
		this.lastUpd = lastUpd;
	}

	@Column(name="PM_TEAM")
	public String getPmTeam() {
		return pmTeam;
	}

	public void setPmTeam(String pmTeam) {
		this.pmTeam = pmTeam;
	}

	@Column(name="IMPACT_STATUS") 
	public String getImpactStatus() {
		return impactStatus;
	}

	public void setImpactStatus(String impactStatus) {
		this.impactStatus = impactStatus;
	}

	@Transient
	public int getSlaTnpWithoutImpact() {
		return slaTnpWithoutImpact;
	}

	public void setSlaTnpWithoutImpact(int slaTnpWithoutImpact) {
		this.slaTnpWithoutImpact = slaTnpWithoutImpact;
	}
	@Transient
	public int getSlaTnpWithImpact() {
		return slaTnpWithImpact;
	}

	public void setSlaTnpWithImpact(int slaTnpWithImpact) {
		this.slaTnpWithImpact = slaTnpWithImpact;
	}

	@Transient
	public int getCdnWithoutImpact() {
		return cdnWithoutImpact;
	}

	public void setCdnWithoutImpact(int cdnWithoutImpact) {
		this.cdnWithoutImpact = cdnWithoutImpact;
	}
	@Transient
	public int getCdnWithImpact() {
		return cdnWithImpact;
	}

	public void setCdnWithImpact(int cdnWithImpact) {
		this.cdnWithImpact = cdnWithImpact;
	}

	
}


