package th.co.ais.ipfm.domain1;
// Generated 27 Ê.¤. 2553, 17:13:55 by Hibernate Tools 3.2.1.GA


import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Transient;
import javax.persistence.UniqueConstraint;
import javax.persistence.Version;

import org.hibernate.annotations.GenericGenerator;

import th.co.ais.ipfm.domain.MasterDomain;

/**
 * IpWfConfigDetail generated by hbm2java
 */
@Entity
@Table(name="IP_WF_CONFIG_DETAIL"
    , uniqueConstraints = @UniqueConstraint(columnNames="ROW_ID") 
)
public class IpWfConfigDetail extends MasterDomain   implements java.io.Serializable {

    private IpWfConfigDetailId id;
    private Long version;
    private String nodeDesc;
    private String emailStatus;
	private String rowId;
	private BigDecimal ola;

	
    @EmbeddedId
    @AttributeOverrides( {
        @AttributeOverride(name="nodeId", column=@Column(name="NODE_ID", nullable=false, length=5) ), 
        @AttributeOverride(name="urType", column=@Column(name="UR_TYPE", nullable=false, length=5) ) } )
	public IpWfConfigDetailId getId() {
		return id;
	}

	public void setId(IpWfConfigDetailId id) {
		this.id = id;
	}

    @Version
    @Column(name="VERSION", precision=10, scale=0)
	public Long getVersion() {
		return version;
	}

	public void setVersion(Long version) {
		this.version = version;
	}

	@Column(name="NODE_DESC", length=1000)
	public String getNodeDesc() {
		return nodeDesc;
	}

	public void setNodeDesc(String nodeDesc) {
		this.nodeDesc = nodeDesc;
	}

	@Column(name="EMAIL_STATUS", length=1)
	public String getEmailStatus() {
		return emailStatus;
	}

	public void setEmailStatus(String emailStatus) {
		this.emailStatus = emailStatus;
	}

	@Column(name="ROW_ID", length=50)
	public String getRowId() {
		return rowId;
	}

	public void setRowId(String rowId) {
		this.rowId = rowId;
	}
	
	@Column(name="OLA")
	public BigDecimal getOla() {
		return ola;
	}

	public void setOla(BigDecimal ola) {
		this.ola = ola;
	}
	
    @Column(name="CREATE_BY")
	public String getCreatedBy() {
		return createdBy;
	}

	public void setCreatedBy(String createdBy) {
		this.createdBy = createdBy;
	}


	@Column(name="UPDATE_BY")
	public String getLastUpdBy() {
		return lastUpdBy;
	}

	public void setLastUpdBy(String lastUpdBy) {
		this.lastUpdBy = lastUpdBy;
	}
	
	@Column(name="UPDATE_DATE")
	public Date getLastUpd() {
		return lastUpd;
	}
	
	public void setLastUpd(Date lastUpd) {
		this.lastUpd = lastUpd;
	}

	@Column(name="CREATE_DATE")
	public Date getCreated() {
		return created;
	}

	public void setCreated(Date created) {
		this.created = created;
	}
	
}


